// Live-Postgres contract coverage for the single lookup persistence boundary.
// `setupAppStateTestDb` applies the production migration chain to a fresh
// per-test database and points `getAppDb()` at it, so the service's real
// `withAppTx` transactions, row locks, generated byte counts, and constraints
// are all exercised without a second container.

import { Client, type Notification } from "pg";
import { describe, expect, it } from "vitest";
import { setupAppStateTestDb } from "@/lib/db/__tests__/appStateTestDb";
import { LOOKUP_STREAM_CHANNEL } from "@/lib/db/pg";
import {
	type LookupColumnId,
	lookupColumnIdSchema,
	lookupTableIdSchema,
} from "@/lib/domain/lookupIds";
import {
	LOOKUP_MAX_COLUMNS,
	LOOKUP_MAX_ROWS,
	LOOKUP_MAX_TABLE_BYTES,
} from "../constants";
import { LookupError } from "../errors";
import {
	addLookupColumn,
	createLookupRow,
	createLookupTable,
	deleteLookupRow,
	getLookupDefinitions,
	getLookupManifest,
	getLookupTable,
	moveLookupColumn,
	moveLookupRow,
	readLookupDefinitionsInTransaction,
	replaceLookupRows,
	updateLookupColumnLabel,
	updateLookupColumnWireName,
	updateLookupRow,
	updateLookupTableName,
	updateLookupTableTag,
} from "../service";
import type {
	LookupColumnDraft,
	LookupRevision,
	LookupRowValues,
	LookupScope,
	LookupTableSnapshot,
} from "../types";

const h = setupAppStateTestDb("lookup_service_");

const OWNER_A: LookupScope = {
	projectId: "project-a",
	actorId: "owner-a",
	role: "owner",
};
const VIEWER_A: LookupScope = {
	projectId: "project-a",
	actorId: "viewer-a",
	role: "viewer",
};
const OWNER_B: LookupScope = {
	projectId: "project-b",
	actorId: "owner-b",
	role: "owner",
};

const TEXT_COLUMN: LookupColumnDraft = {
	wireName: "name",
	label: "Name",
	dataType: "text",
};

const MISSING_TABLE_ID = lookupTableIdSchema.parse(
	"018f0f43-7b7c-7abc-8def-0123456789ab",
);
const MISSING_COLUMN_ID = lookupColumnIdSchema.parse(
	"018f0f43-7b7c-7abc-8def-0123456789ab",
);

function rowValues(
	entries: readonly (readonly [LookupColumnId, string | number])[],
): LookupRowValues {
	const values: LookupRowValues = {};
	for (const [id, value] of entries) values[id] = value;
	return values;
}

async function createTable(
	scope: LookupScope = OWNER_A,
	overrides: {
		name?: string;
		tag?: string;
		columns?: LookupColumnDraft[];
	} = {},
): Promise<LookupTableSnapshot> {
	return createLookupTable(scope, {
		name: overrides.name ?? "Facilities",
		tag: overrides.tag ?? "facilities",
		columns: overrides.columns ?? [TEXT_COLUMN],
	});
}

async function expectLookupError(
	promise: Promise<unknown>,
	code: LookupError["code"],
): Promise<LookupError> {
	let caught: unknown;
	try {
		await promise;
	} catch (error) {
		caught = error;
	}
	expect(caught).toBeInstanceOf(LookupError);
	expect(caught).toMatchObject({ code });
	return caught as LookupError;
}

describe("lookup persistence service", () => {
	it("keeps every read Project-scoped and treats a foreign UUID like a missing UUID", async () => {
		const tableA = await createTable(OWNER_A, {
			name: "Zulu",
			tag: "shared_tag",
		});
		const tableB = await createTable(OWNER_B, {
			name: "Alpha",
			tag: "shared_tag",
		});
		const earlierA = await createTable(OWNER_A, {
			name: "alpha",
			tag: "alpha_table",
		});

		const manifestA = await getLookupManifest(OWNER_A);
		expect(manifestA.projectRevision).toBe("2");
		expect(manifestA.tables.map(({ id }) => id)).toEqual([
			earlierA.id,
			tableA.id,
		]);
		expect(manifestA.tables).not.toContainEqual(
			expect.objectContaining({ id: tableB.id }),
		);
		expect(
			(await getLookupManifest(OWNER_B)).tables.map(({ id }) => id),
		).toEqual([tableB.id]);

		const foreign = await expectLookupError(
			getLookupTable(OWNER_A, tableB.id),
			"not_found",
		);
		const missing = await expectLookupError(
			getLookupTable(OWNER_A, MISSING_TABLE_ID),
			"not_found",
		);
		expect(foreign.message).toBe(missing.message);
	});

	it("returns only requested rows-free definitions in deterministic UUID order", async () => {
		const first = await createTable(OWNER_A, {
			name: "Zulu",
			tag: "zulu",
			columns: [
				TEXT_COLUMN,
				{ wireName: "rank", label: "Rank", dataType: "int" },
			],
		});
		const second = await createTable(OWNER_A, {
			name: "Alpha",
			tag: "alpha",
		});
		const foreign = await createTable(OWNER_B, {
			name: "Foreign",
			tag: "foreign",
		});
		await createLookupRow(OWNER_A, {
			tableId: first.id,
			expectedTableRevision: first.tableRevision,
			toIndex: 0,
			values: rowValues([[first.columns[0].id, "not projected"]]),
		});

		const snapshot = await getLookupDefinitions(OWNER_A, [
			foreign.id,
			second.id,
			MISSING_TABLE_ID,
			first.id,
			second.id,
		]);
		const expectedIds = [first.id, second.id].sort();
		expect(snapshot).toMatchObject({
			projectId: OWNER_A.projectId,
			projectRevision: "3",
		});
		expect(snapshot.definitions.map(({ id }) => id)).toEqual(expectedIds);
		for (const definition of snapshot.definitions) {
			expect(definition).not.toHaveProperty("rows");
			expect(definition).not.toHaveProperty("rowsRevision");
		}
		const firstDefinition = snapshot.definitions.find(
			({ id }) => id === first.id,
		);
		expect(firstDefinition).toEqual({
			id: first.id,
			name: first.name,
			tag: first.tag,
			definitionRevision: first.definitionRevision,
			columns: first.columns,
		});
		const composed = await h
			.db()
			.transaction()
			.execute((tx) =>
				readLookupDefinitionsInTransaction(tx, OWNER_A.projectId, [
					second.id,
					first.id,
				]),
			);
		expect(composed).toEqual(snapshot);

		const foreignOnly = await getLookupDefinitions(OWNER_A, [foreign.id]);
		const missingOnly = await getLookupDefinitions(OWNER_A, [MISSING_TABLE_ID]);
		const empty = await getLookupDefinitions(OWNER_A, []);
		expect(foreignOnly).toEqual(missingOnly);
		expect(empty).toEqual({
			projectId: OWNER_A.projectId,
			projectRevision: "3",
			definitions: [],
		});
		expect(empty).toEqual(missingOnly);
		expect(foreignOnly.definitions).toEqual([]);
	});

	it("accepts an already-authorized scope without reimplementing role policy", async () => {
		const table = await createTable(VIEWER_A);
		const renamed = await updateLookupTableName(VIEWER_A, {
			tableId: table.id,
			expectedTableRevision: table.tableRevision,
			name: "Clinics",
		});
		expect(renamed.projectRevision).toBe("2");
		expect((await getLookupTable(VIEWER_A, table.id)).name).toBe("Clinics");
	});

	it("advances exactly once, makes no-ops revisionless, rolls rejection back, and reports a fresh conflict token", async () => {
		const table = await createTable();
		expect(table.projectRevision).toBe("1");
		expect(table.definitionRevision).toBe("1");
		expect(table.rowsRevision).toBe("1");

		const noOp = await updateLookupTableName(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: table.tableRevision,
			name: table.name,
		});
		expect(noOp.projectRevision).toBe("1");
		expect((await getLookupManifest(OWNER_A)).projectRevision).toBe("1");

		const renamed = await updateLookupTableName(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: table.tableRevision,
			name: "Clinics",
		});
		expect(renamed).toMatchObject({
			projectRevision: "2",
			definitionRevision: "2",
			rowsRevision: "1",
			tableRevision: "2",
		});

		const conflict = await expectLookupError(
			updateLookupTableTag(OWNER_A, {
				tableId: table.id,
				expectedTableRevision: table.tableRevision,
				tag: "clinics",
			}),
			"conflict",
		);
		expect(conflict.currentRevisions).toEqual({
			definitionRevision: "2",
			rowsRevision: "1",
			tableRevision: "2",
		});
		expect((await getLookupManifest(OWNER_A)).projectRevision).toBe("2");

		await expectLookupError(
			createLookupRow(OWNER_A, {
				tableId: table.id,
				expectedTableRevision: renamed.tableRevision,
				toIndex: 0,
				values: rowValues([[MISSING_COLUMN_ID, "foreign column"]]),
			}),
			"invalid_input",
		);
		const afterRollback = await getLookupTable(OWNER_A, table.id);
		expect(afterRollback.projectRevision).toBe("2");
		expect(afterRollback.rows).toEqual([]);
		expect(afterRollback.dataBytes).toBe(0);
	});

	it("notifies exact committed revisions while no-ops, rejections, and rollbacks stay silent", async () => {
		const listener = new Client({ connectionString: h.uri() });
		const notifications: Array<{
			channel: string;
			payload: { projectId: string; revision: string };
		}> = [];
		const collect = (notification: Notification) => {
			if (
				notification.channel === LOOKUP_STREAM_CHANNEL &&
				notification.payload
			) {
				notifications.push({
					channel: notification.channel,
					payload: JSON.parse(notification.payload),
				});
			}
		};
		const waitForCount = async (count: number): Promise<void> => {
			if (notifications.length >= count) return;
			await new Promise<void>((resolve, reject) => {
				const timeout = setTimeout(() => {
					listener.off("notification", check);
					reject(
						new Error(`Timed out waiting for ${count} lookup notifications.`),
					);
				}, 2_000);
				timeout.unref();
				const check = () => {
					if (notifications.length < count) return;
					clearTimeout(timeout);
					listener.off("notification", check);
					resolve();
				};
				listener.on("notification", check);
			});
		};

		await listener.connect();
		listener.on("notification", collect);
		try {
			await listener.query(`LISTEN ${LOOKUP_STREAM_CHANNEL}`);
			const table = await createTable(OWNER_A, {
				columns: [
					TEXT_COLUMN,
					{ wireName: "b", label: "B", dataType: "text" },
					{ wireName: "c", label: "C", dataType: "text" },
					{ wireName: "d", label: "D", dataType: "text" },
				],
			});
			await waitForCount(1);

			await updateLookupTableName(OWNER_A, {
				tableId: table.id,
				expectedTableRevision: table.tableRevision,
				name: table.name,
			});
			await expectLookupError(
				updateLookupTableTag(OWNER_A, {
					tableId: table.id,
					expectedTableRevision: "0" as LookupRevision,
					tag: "stale_tag",
				}),
				"conflict",
			);
			await expectLookupError(
				createLookupRow(OWNER_A, {
					tableId: table.id,
					expectedTableRevision: table.tableRevision,
					toIndex: 0,
					values: rowValues(
						table.columns.map(({ id }) => [id, "x".repeat(65_536)]),
					),
				}),
				"storage_limit",
			);

			const renamed = await updateLookupTableName(OWNER_A, {
				tableId: table.id,
				expectedTableRevision: table.tableRevision,
				name: "Clinics",
			});
			await waitForCount(2);
			expect(notifications).toEqual([
				{
					channel: LOOKUP_STREAM_CHANNEL,
					payload: { projectId: OWNER_A.projectId, revision: "1" },
				},
				{
					channel: LOOKUP_STREAM_CHANNEL,
					payload: {
						projectId: OWNER_A.projectId,
						revision: renamed.projectRevision,
					},
				},
			]);
		} finally {
			await listener.query("UNLISTEN *");
			listener.off("notification", collect);
			await listener.end();
		}
	});

	it("serializes exact tag uniqueness while allowing case-distinct and cross-Project tags", async () => {
		const attempts = await Promise.allSettled([
			createTable(OWNER_A, { name: "First", tag: "Facility" }),
			createTable(OWNER_A, { name: "Second", tag: "Facility" }),
		]);
		const fulfilled = attempts.filter(
			(result) => result.status === "fulfilled",
		);
		const rejected = attempts.filter((result) => result.status === "rejected");
		expect(fulfilled).toHaveLength(1);
		expect(rejected).toHaveLength(1);
		expect((rejected[0] as PromiseRejectedResult).reason).toMatchObject({
			code: "tag_taken",
		});
		expect((await getLookupManifest(OWNER_A)).projectRevision).toBe("1");

		await expect(
			Promise.all([
				createTable(OWNER_A, { name: "Lower", tag: "facility" }),
				createTable(OWNER_B, { name: "Other Project", tag: "Facility" }),
			]),
		).resolves.toHaveLength(2);
	});

	it("orders columns and rows by server keys while preserving stable UUIDs through edits and moves", async () => {
		const table = await createTable(OWNER_A, {
			columns: [
				TEXT_COLUMN,
				{ wireName: "code", label: "Code", dataType: "text" },
			],
		});
		const nameId = table.columns[0].id;
		const codeId = table.columns[1].id;
		const added = await addLookupColumn(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: table.tableRevision,
			column: { wireName: "rank", label: "Rank", dataType: "int" },
		});
		const movedColumn = await moveLookupColumn(OWNER_A, {
			tableId: table.id,
			columnId: added.columnId,
			expectedTableRevision: added.tableRevision,
			toIndex: 0,
		});
		let snapshot = await getLookupTable(OWNER_A, table.id);
		expect(snapshot.columns.map(({ id }) => id)).toEqual([
			added.columnId,
			nameId,
			codeId,
		]);

		const rowA = await createLookupRow(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: movedColumn.tableRevision,
			toIndex: 0,
			values: rowValues([
				[nameId, "A"],
				[codeId, "a"],
				[added.columnId, 1],
			]),
		});
		const rowB = await createLookupRow(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: rowA.tableRevision,
			toIndex: 0,
			values: rowValues([[nameId, "B"]]),
		});
		const rowC = await createLookupRow(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: rowB.tableRevision,
			toIndex: 1,
			values: rowValues([[nameId, "C"]]),
		});
		snapshot = await getLookupTable(OWNER_A, table.id);
		expect(snapshot.rows.map(({ id }) => id)).toEqual([
			rowB.rowId,
			rowC.rowId,
			rowA.rowId,
		]);

		const movedRow = await moveLookupRow(OWNER_A, {
			tableId: table.id,
			rowId: rowA.rowId,
			expectedTableRevision: rowC.tableRevision,
			toIndex: 0,
		});
		const updatedRow = await updateLookupRow(OWNER_A, {
			tableId: table.id,
			rowId: rowA.rowId,
			expectedTableRevision: movedRow.tableRevision,
			values: rowValues([[nameId, "A updated"]]),
		});
		snapshot = await getLookupTable(OWNER_A, table.id);
		expect(snapshot.rows.map(({ id }) => id)).toEqual([
			rowA.rowId,
			rowB.rowId,
			rowC.rowId,
		]);
		expect(snapshot.rows[0]).toMatchObject({
			id: rowA.rowId,
			values: rowValues([[nameId, "A updated"]]),
		});
		expect(snapshot.rowsRevision).toBe(updatedRow.rowsRevision);
	});

	it("persists column labels and exact wire names without changing stable identity", async () => {
		const table = await createTable(OWNER_A, {
			columns: [
				TEXT_COLUMN,
				{ wireName: "code", label: "Code", dataType: "text" },
			],
		});
		const [nameId, codeId] = table.columns.map(({ id }) => id);
		const labeled = await updateLookupColumnLabel(OWNER_A, {
			tableId: table.id,
			columnId: nameId,
			expectedTableRevision: table.tableRevision,
			label: "Facility name",
		});
		expect(labeled).toMatchObject({
			projectRevision: "2",
			definitionRevision: "2",
			rowsRevision: "1",
		});
		const labelNoOp = await updateLookupColumnLabel(OWNER_A, {
			tableId: table.id,
			columnId: nameId,
			expectedTableRevision: labeled.tableRevision,
			label: "Facility name",
		});
		expect(labelNoOp.projectRevision).toBe(labeled.projectRevision);

		await expectLookupError(
			updateLookupColumnWireName(OWNER_A, {
				tableId: table.id,
				columnId: codeId,
				expectedTableRevision: labeled.tableRevision,
				wireName: "name",
			}),
			"invalid_input",
		);
		const renamed = await updateLookupColumnWireName(OWNER_A, {
			tableId: table.id,
			columnId: codeId,
			expectedTableRevision: labeled.tableRevision,
			wireName: "Name",
		});
		expect(renamed.projectRevision).toBe("3");
		const snapshot = await getLookupTable(OWNER_A, table.id);
		expect(snapshot.columns).toEqual([
			{
				id: nameId,
				wireName: "name",
				label: "Facility name",
				dataType: "text",
			},
			{
				id: codeId,
				wireName: "Name",
				label: "Code",
				dataType: "text",
			},
		]);

		const foreignTable = await createTable(OWNER_B);
		const foreign = await expectLookupError(
			updateLookupColumnLabel(OWNER_A, {
				tableId: table.id,
				columnId: foreignTable.columns[0].id,
				expectedTableRevision: snapshot.tableRevision,
				label: "Foreign",
			}),
			"not_found",
		);
		const missing = await expectLookupError(
			updateLookupColumnLabel(OWNER_A, {
				tableId: table.id,
				columnId: MISSING_COLUMN_ID,
				expectedTableRevision: snapshot.tableRevision,
				label: "Missing",
			}),
			"not_found",
		);
		expect(foreign.message).toBe(missing.message);
		expect((await getLookupManifest(OWNER_A)).projectRevision).toBe("3");
	});

	it("uses Postgres-generated byte counts, rejects an oversized row atomically, and returns capacity on shrink/delete", async () => {
		const table = await createTable(OWNER_A, {
			columns: [
				TEXT_COLUMN,
				{ wireName: "b", label: "B", dataType: "text" },
				{ wireName: "c", label: "C", dataType: "text" },
				{ wireName: "d", label: "D", dataType: "text" },
			],
		});
		const [a, b, c, d] = table.columns.map(({ id }) => id);
		await expectLookupError(
			createLookupRow(OWNER_A, {
				tableId: table.id,
				expectedTableRevision: table.tableRevision,
				toIndex: 0,
				values: rowValues([
					[a, "x".repeat(65_536)],
					[b, "x".repeat(65_536)],
					[c, "x".repeat(65_536)],
					[d, "x".repeat(65_536)],
				]),
			}),
			"storage_limit",
		);
		expect(await getLookupTable(OWNER_A, table.id)).toMatchObject({
			projectRevision: "1",
			rowCount: 0,
			dataBytes: 0,
		});

		const created = await createLookupRow(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: table.tableRevision,
			toIndex: 0,
			values: rowValues([[a, "x".repeat(8_000)]]),
		});
		let snapshot = await getLookupTable(OWNER_A, table.id);
		const raw = await h
			.db()
			.selectFrom("lookup_rows")
			.select("value_bytes")
			.where("project_id", "=", OWNER_A.projectId)
			.where("table_id", "=", table.id)
			.where("id", "=", created.rowId)
			.executeTakeFirstOrThrow();
		expect(snapshot.rows[0].valueBytes).toBe(raw.value_bytes);
		expect(snapshot.dataBytes).toBe(raw.value_bytes);
		const beforeShrink = snapshot.dataBytes;

		const shrunk = await updateLookupRow(OWNER_A, {
			tableId: table.id,
			rowId: created.rowId,
			expectedTableRevision: created.tableRevision,
			values: rowValues([[a, "small"]]),
		});
		snapshot = await getLookupTable(OWNER_A, table.id);
		expect(snapshot.dataBytes).toBeLessThan(beforeShrink);
		await deleteLookupRow(OWNER_A, {
			tableId: table.id,
			rowId: created.rowId,
			expectedTableRevision: shrunk.tableRevision,
		});
		expect(await getLookupTable(OWNER_A, table.id)).toMatchObject({
			rowCount: 0,
			dataBytes: 0,
		});
	});

	it("enforces the locked column, row, and table caps without spending a revision on rejection", async () => {
		const table = await createTable();
		const columnId = table.columns[0].id;
		const rows = Array.from({ length: LOOKUP_MAX_ROWS - 1 }, () =>
			rowValues([[columnId, ""]]),
		);
		const replaced = await replaceLookupRows(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: table.tableRevision,
			rows,
		});
		const rowCapRace = await Promise.allSettled([
			createLookupRow(OWNER_A, {
				tableId: table.id,
				expectedTableRevision: replaced.tableRevision,
				toIndex: LOOKUP_MAX_ROWS - 1,
				values: rowValues([[columnId, "last-a"]]),
			}),
			createLookupRow(OWNER_A, {
				tableId: table.id,
				expectedTableRevision: replaced.tableRevision,
				toIndex: LOOKUP_MAX_ROWS - 1,
				values: rowValues([[columnId, "last-b"]]),
			}),
		]);
		expect(
			rowCapRace.filter((result) => result.status === "fulfilled"),
		).toHaveLength(1);
		expect(
			rowCapRace.find((result) => result.status === "rejected"),
		).toMatchObject({ reason: { code: "conflict" } });
		const rowCapSnapshot = await getLookupTable(OWNER_A, table.id);
		expect(rowCapSnapshot.rowCount).toBe(LOOKUP_MAX_ROWS);
		await expectLookupError(
			createLookupRow(OWNER_A, {
				tableId: table.id,
				expectedTableRevision: rowCapSnapshot.tableRevision,
				toIndex: LOOKUP_MAX_ROWS,
				values: rowValues([[columnId, "one too many"]]),
			}),
			"row_limit",
		);
		expect((await getLookupManifest(OWNER_A)).projectRevision).toBe(
			rowCapSnapshot.projectRevision,
		);
		const columnCapTable = await createTable(OWNER_A, {
			name: "Column boundary",
			tag: "column_boundary",
			columns: Array.from({ length: LOOKUP_MAX_COLUMNS }, (_, index) => ({
				wireName: `column_${index}`,
				label: `Column ${index}`,
				dataType: "text" as const,
			})),
		});
		await expectLookupError(
			addLookupColumn(OWNER_A, {
				tableId: columnCapTable.id,
				expectedTableRevision: columnCapTable.tableRevision,
				column: {
					wireName: "one_too_many",
					label: "One too many",
					dataType: "text",
				},
			}),
			"invalid_input",
		);
		expect((await getLookupManifest(OWNER_A)).projectRevision).toBe(
			columnCapTable.projectRevision,
		);

		const storageTable = await createTable(OWNER_A, {
			name: "Storage boundary",
			tag: "storage_boundary",
		});
		const storageColumnId = storageTable.columns[0].id;
		const maxCell = "x".repeat(65_536);
		const probe = await createLookupRow(OWNER_A, {
			tableId: storageTable.id,
			expectedTableRevision: storageTable.tableRevision,
			toIndex: 0,
			values: rowValues([[storageColumnId, maxCell]]),
		});
		const measuredRowBytes = (await getLookupTable(OWNER_A, storageTable.id))
			.rows[0].valueBytes;
		const emptied = await deleteLookupRow(OWNER_A, {
			tableId: storageTable.id,
			rowId: probe.rowId,
			expectedTableRevision: probe.tableRevision,
		});
		const fittingRowCount = Math.floor(
			LOOKUP_MAX_TABLE_BYTES / measuredRowBytes,
		);
		const nearlyFilled = await replaceLookupRows(OWNER_A, {
			tableId: storageTable.id,
			expectedTableRevision: emptied.tableRevision,
			rows: Array.from({ length: fittingRowCount - 1 }, () =>
				rowValues([[storageColumnId, maxCell]]),
			),
		});
		const byteCapRace = await Promise.allSettled([
			createLookupRow(OWNER_A, {
				tableId: storageTable.id,
				expectedTableRevision: nearlyFilled.tableRevision,
				toIndex: fittingRowCount - 1,
				values: rowValues([[storageColumnId, maxCell]]),
			}),
			createLookupRow(OWNER_A, {
				tableId: storageTable.id,
				expectedTableRevision: nearlyFilled.tableRevision,
				toIndex: fittingRowCount - 1,
				values: rowValues([[storageColumnId, maxCell]]),
			}),
		]);
		expect(
			byteCapRace.filter((result) => result.status === "fulfilled"),
		).toHaveLength(1);
		expect(
			byteCapRace.find((result) => result.status === "rejected"),
		).toMatchObject({ reason: { code: "conflict" } });
		const fullSnapshot = await getLookupTable(OWNER_A, storageTable.id);
		expect(fullSnapshot.dataBytes).toBe(measuredRowBytes * fittingRowCount);
		expect(fullSnapshot.dataBytes).toBeLessThanOrEqual(LOOKUP_MAX_TABLE_BYTES);
		await expectLookupError(
			createLookupRow(OWNER_A, {
				tableId: storageTable.id,
				expectedTableRevision: fullSnapshot.tableRevision,
				toIndex: fittingRowCount,
				values: rowValues([[storageColumnId, maxCell]]),
			}),
			"storage_limit",
		);
		expect((await getLookupManifest(OWNER_A)).projectRevision).toBe(
			fullSnapshot.projectRevision,
		);
		const shrunk = await updateLookupRow(OWNER_A, {
			tableId: storageTable.id,
			rowId: fullSnapshot.rows[0].id,
			expectedTableRevision: fullSnapshot.tableRevision,
			values: rowValues([[storageColumnId, ""]]),
		});
		await expect(
			createLookupRow(OWNER_A, {
				tableId: storageTable.id,
				expectedTableRevision: shrunk.tableRevision,
				toIndex: fittingRowCount,
				values: rowValues([[storageColumnId, maxCell]]),
			}),
		).resolves.toMatchObject({ rowId: expect.any(String) });
	});

	it("replaces atomically, rejects stale or invalid bodies without deleting, and always mints fresh nonempty-row identity", async () => {
		const table = await createTable();
		const columnId = table.columns[0].id;
		const first = await createLookupRow(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: table.tableRevision,
			toIndex: 0,
			values: rowValues([[columnId, "first"]]),
		});
		const second = await createLookupRow(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: first.tableRevision,
			toIndex: 1,
			values: rowValues([[columnId, "second"]]),
		});
		const original = await getLookupTable(OWNER_A, table.id);
		const originalIds = original.rows.map(({ id }) => id);

		await expectLookupError(
			replaceLookupRows(OWNER_A, {
				tableId: table.id,
				expectedTableRevision: first.tableRevision,
				rows: [rowValues([[columnId, "stale"]])],
			}),
			"conflict",
		);
		await expectLookupError(
			replaceLookupRows(OWNER_A, {
				tableId: table.id,
				expectedTableRevision: second.tableRevision,
				rows: [rowValues([[MISSING_COLUMN_ID, "unknown"]])],
			}),
			"invalid_input",
		);
		expect(
			(await getLookupTable(OWNER_A, table.id)).rows.map(({ id }) => id),
		).toEqual(originalIds);

		const replacement = await replaceLookupRows(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: second.tableRevision,
			rows: [
				rowValues([[columnId, "third"]]),
				rowValues([[columnId, "fourth"]]),
			],
		});
		const replaced = await getLookupTable(OWNER_A, table.id);
		expect(replaced.rows.map(({ values }) => values[columnId])).toEqual([
			"third",
			"fourth",
		]);
		expect(replaced.rows.map(({ id }) => id)).not.toEqual(originalIds);

		await replaceLookupRows(OWNER_A, {
			tableId: table.id,
			expectedTableRevision: replacement.tableRevision,
			rows: [
				rowValues([[columnId, "third"]]),
				rowValues([[columnId, "fourth"]]),
			],
		});
		const replacedAgain = await getLookupTable(OWNER_A, table.id);
		expect(replacedAgain.rows.map(({ id }) => id)).not.toEqual(
			replaced.rows.map(({ id }) => id),
		);
	});

	it("keeps revisions as canonical strings beyond JavaScript safe integer range", async () => {
		await h
			.db()
			.insertInto("lookup_project_state")
			.values({
				project_id: OWNER_A.projectId,
				revision: "9007199254740992" as LookupRevision,
			})
			.execute();
		const table = await createTable();
		expect(table.projectRevision).toBe("9007199254740993");
		expect(table.tableRevision).toBe("9007199254740993");
	});
});
