// lib/case-store/sql/database.ts
//
// The Kysely `Database` type. The DDL the types mirror lives in the
// forward-only migration modules at `lib/case-store/migrations/`
// (applied by Kysely's `Migrator` — see `lib/case-store/migrate.ts`).
// Any schema change adds a migration module and updates this file in
// lockstep; the compile-only `database.test.ts` and the harness smoke
// tests catch drift between them.
//
// ## Multi-tenancy — two orthogonal axes
//
// Tenant isolation is the column pair `(app_id, project_id)` — case
// data is shared at Project scope, so every member of a Project sees
// its rows. That is the ONLY structural filter today.
//
// `owner_id` is the SECOND axis: the CommCare case-owner, Nova's
// reserved axis for future location-/group-based access carving. It is
// a first-class column (defaulted to the creating user), NOT a tenant
// boundary and NOT disposable — nothing filters on it yet because
// locations are unimplemented, but when they land, location-based
// access control filters on it BENEATH the Project tenant filter.
//
// No row-level security, no per-tenant schema, no per-tenant database.
// The application funnels reads/writes through a `CaseStore` bound to
// the request's Project id (`withProjectContext`); schema-change
// operations are app-scoped and bind no tenant (`withSchemaContext`).
//
// ## JSONB column types do NOT narrow per case type
//
// `properties` is `JSONColumnType<JsonObject>` — the open
// `Record<string, JsonValue>` shape Postgres returns. The
// per-case-type validator lives in `case_type_schemas`'s JSON
// Schema document; narrowing the column type here would fight
// every multi-case-type query. The three-state distinction
// ("absent" / "null" / "empty string") lives at runtime and is
// preserved by the operators the compilers emit (`properties ?
// 'key'`, `properties->>'key' IS NULL`, `= ''`).

import type { ColumnType, JSONColumnType } from "kysely";

// Standard recursive JSON-value union. Read-side shape of every
// JSONB column; the dialect's serializer turns this tree into a
// string for INSERT/UPDATE.

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue =
	| JsonPrimitive
	| JsonValue[]
	| { [key: string]: JsonValue };
export type JsonObject = { [key: string]: JsonValue };

/**
 * Live-case row. The runtime read/write surface for every case
 * regardless of case type. JSONB `properties` carries the per-
 * case-type shape; the dozen reserved scalar columns are the
 * fields every case carries.
 */
export interface CasesTable {
	/**
	 * Stable case identifier. UUID v7 generated by Postgres via
	 * `DEFAULT uuidv7()`; v7's millisecond-timestamp prefix
	 * clusters INSERT order tightly on the B-tree primary-key
	 * page. Callers may supply an explicit value verbatim for
	 * cross-system traceability with CCHQ-style ids.
	 *
	 * `string | undefined` on insert tells Kysely the column is
	 * OPTIONAL — without that branch every insert site would have
	 * to construct a `case_id`, defeating the database default and
	 * the `RETURNING case_id` pattern.
	 */
	case_id: ColumnType<string, string | undefined, string>;

	/** First half of `(app_id, project_id)`. TEXT (not UUID) — an `apps.id` is text (a UUID for new apps; a compact id for pre-cutover apps). */
	app_id: string;

	/** Matches the blueprint's `CaseType.id`. */
	case_type: string;

	/**
	 * Second half of `(app_id, project_id)` — the structural tenant
	 * filter; case data is shared at Project scope. Required on insert
	 * (`withProjectContext` binds it) and non-null on read. (The DB
	 * column is nullable; the `add_cases_project_id` migration module
	 * owns the expand→backfill rollout that keeps the non-null read
	 * contract safe.)
	 */
	project_id: string;

	/**
	 * The CommCare case-owner — Nova's reserved axis for future
	 * location-/group-based access carving, NOT the tenant boundary
	 * (that is `project_id`). Defaults to the creating user; nothing
	 * filters on it today (locations unimplemented), but it is a
	 * first-class field reserved for that access-control axis, never to
	 * be repurposed or dropped. Nullable — HQ-imported cases
	 * pre-assignment carry null. Stays a queryable reserved scalar
	 * column (`RESERVED_SCALAR_COLUMN_BY_PROPERTY`).
	 */
	owner_id: string | null;

	/**
	 * Open/closed status string. Distinct from `closed_on` so
	 * domain status vocabularies (CCHQ's `open` / `closed` tokens)
	 * round-trip without lossy derivation from a timestamp.
	 */
	status: string | null;

	/** Domain timestamp ("when the case was opened"), distinct from row-versioning. The case-list "Date Opened" column reads this. */
	opened_on: ColumnType<
		Date | null,
		Date | string | null,
		Date | string | null
	>;

	/** Updated on every form-submission write. */
	modified_on: ColumnType<
		Date | null,
		Date | string | null,
		Date | string | null
	>;

	/** Null while open. Standard "list open cases" query is `WHERE closed_on IS NULL`. */
	closed_on: ColumnType<
		Date | null,
		Date | string | null,
		Date | string | null
	>;

	/**
	 * Display name. Top-level column (not a JSONB key) because
	 * `case_name` is platform-required on every case regardless of
	 * case-type. Non-empty by DB CHECK; `caseTypeToJsonSchema`
	 * excludes `case_name` from its property output so the column
	 * is the single source of truth.
	 *
	 * **`is-null` / `is-blank` against this column are structurally
	 * always false.** The column is `NOT NULL` with `length > 0`,
	 * so the predicate compiler's emitted SQL is trivially false.
	 * The type checker doesn't reject these AST shapes today
	 * (admits any `RESERVED_SCALAR_COLUMN_BY_PROPERTY` entry on the left
	 * operand without a nullability check), so the SQL compiler
	 * emits the trivially-false predicate rather than throwing.
	 */
	case_name: string;

	/**
	 * CommCare's standard `external_id` case metadata — a cross-system
	 * traceability slot beside `case_name` / `status`, never a JSONB
	 * key. Nothing writes it yet (HQ import / future features will);
	 * it exists so the standard-name reads
	 * (`RESERVED_SCALAR_COLUMN_BY_PROPERTY`'s `external_id` /
	 * `external-id` entries) resolve to an honest column instead of
	 * throwing.
	 */
	external_id: string | null;

	/** Denormalized first parent for the common single-parent case. Full ancestor walks go through `case_indices`. */
	parent_case_id: string | null;

	/** Validated against `case_type_schemas[app_id, case_type]` via AJV at every API-route write. */
	properties: JSONColumnType<JsonObject>;
}

/**
 * Per-(app, case-type) JSON Schema row generated from the
 * blueprint's case-type properties. AJV reads it on every case-
 * store write; `applySchemaChange` UPSERTs it whenever the
 * blueprint commits a case-type change.
 */
export interface CaseTypeSchemasTable {
	app_id: string;
	case_type: string;
	/**
	 * JSON Schema document generated by
	 * `lib/domain/predicate/jsonSchema.ts` from the blueprint's
	 * `CaseType.properties[]`. The shape stays open
	 * `Record<string, JsonValue>` — pinning to a specific
	 * Schema-Draft TypeScript type would couple this surface to a
	 * particular validator library.
	 */
	schema: JSONColumnType<JsonObject>;
	/**
	 * The `mutation_seq` this schema row was last synced from — the
	 * monotone guard that makes concurrent additive case-type edits
	 * converge. `applySchemaChange` UPSERTs with the incoming seq guarded
	 * by `WHERE excluded.synced_seq >= case_type_schemas.synced_seq`, so a
	 * stale lower-seq sync no-ops and a peer's concurrently-added property
	 * is never clobbered by an in-flight older write.
	 *
	 * `ColumnType<string, number | undefined, number>`: node-postgres returns
	 * `bigint`/`int8` as a STRING, so the SELECT type is `string` and a reader
	 * coerces `Number(row.synced_seq)` — the type forces the coercion rather
	 * than letting a bare `>=`/`+ 1` silently do string math. Insert is OPTIONAL
	 * (defaults to 0 via the column DEFAULT); update supplies the seq.
	 */
	synced_seq: ColumnType<string, number | undefined, number>;
}

/**
 * `child` is the standard parent-child relation; `extension` is
 * the host-extension relation where closing the host closes the
 * extension. The wire grammars (CSQL, on-device XPath) match
 * across both via `ancestor-exists` / `subcase-exists`; the
 * explicit column lets the Postgres compiler answer
 * direction-specific queries the wire grammars cannot.
 */
export type CaseIndexRelationship = "child" | "extension";

/**
 * Edge table for case-to-case relations (parent-child, host-
 * extension). One row per direct edge; `compileRelationPath`
 * chains direct edges per AST step at `depth = 1`.
 */
export interface CaseIndicesTable {
	case_id: string;
	ancestor_id: string;
	/** `parent`, `host`, or any custom identifier the blueprint defines. */
	identifier: string;
	relationship: CaseIndexRelationship;
	/**
	 * `depth=1` is direct; higher values are reserved for
	 * transitive edges. `compileRelationPath` chains direct edges
	 * per AST step and pins every lookup to `depth = 1`, so the
	 * SQL ignores any transitive rows that happen to be present —
	 * the read strategy stays materialization-agnostic.
	 */
	depth: number;
}

/**
 * Failed-migration sink. `applySchemaChange` writes here when a
 * blueprint mutation produces a value the new schema rejects; the
 * original row stays preserved verbatim for author-UI review.
 *
 * Composite PK `(case_id, quarantined_at)` admits the same case
 * being quarantined more than once across separate migrations.
 * The single-column PK `cases` uses would conflict on the second
 * quarantine.
 *
 * `case_name` is nullable here (unlike `cases`) because audit
 * rows have no CHECK — a row in quarantine is by definition one
 * whose live shape failed validation.
 */
export interface CasesQuarantineTable {
	/** NOT defaulted to `uuidv7()` — quarantine writes carry the original case_id. */
	case_id: string;
	app_id: string;
	case_type: string;
	owner_id: string | null;
	status: string | null;
	opened_on: ColumnType<
		Date | null,
		Date | string | null,
		Date | string | null
	>;
	modified_on: ColumnType<
		Date | null,
		Date | string | null,
		Date | string | null
	>;
	closed_on: ColumnType<
		Date | null,
		Date | string | null,
		Date | string | null
	>;
	case_name: string | null;
	parent_case_id: string | null;
	/** Captured verbatim at quarantine time (NOT normalized to the new schema). */
	properties: JSONColumnType<JsonObject>;
	/** E.g. `"cast text→int failed for property 'age': value 'abc' is not numeric"`. */
	quarantine_reason: string;
	/** Defaulted server-side via `now()`; application code omits on INSERT. */
	quarantined_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

/** Complete Kysely Database type. The runtime instance is constructed elsewhere. */
export interface Database {
	cases: CasesTable;
	case_type_schemas: CaseTypeSchemasTable;
	case_indices: CaseIndicesTable;
	cases_quarantine: CasesQuarantineTable;
}
