// Frozen copy generated by lezer-generator for the 20260728 migration.
// Do not regenerate from the steady-state grammar.
export const noGapIdent = 69,
	noGapSlash = 70,
	XPath = 1,
	HashtagRef = 2,
	VariableReference = 7,
	StringLiteral = 10,
	NumberLiteral = 11,
	NameTest = 16;
