// This file was generated by lezer-generator. You probably shouldn't edit it.
export const noGapIdent = 69,
	noGapSlash = 70,
	AndOp = 1,
	OrOp = 2,
	DivOp = 3,
	ModOp = 4,
	XPath = 5,
	HashtagRef = 6,
	VariableReference = 11,
	StringLiteral = 14,
	NumberLiteral = 15,
	NameTest = 20;
