// This file was generated by lezer-generator. You probably shouldn't edit it.
export const noGapIdent = 69,
	noGapSlash = 70,
	XPath = 1,
	HashtagRef = 2,
	VariableReference = 7,
	StringLiteral = 10,
	NumberLiteral = 11,
	NameTest = 16;
