// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
import { hashtagGuard } from "./hashtagGuard";

const spec_localName = {
	__proto__: null,
	div: 164,
	mod: 166,
	and: 168,
	or: 170,
};
export const parser = LRParser.deserialize({
	version: 14,
	states:
		",lOVQQOOO!WQRO'#C^O!]QQO'#CjOOQO'#D}'#D}OOQO'#Cm'#CmOOQO'#Co'#CoO#vQQO'#ClOOQO'#Cl'#ClO%^QQO'#CpOOQO'#D|'#D|O%cQQO'#CiO%hQQO'#CtOOQO'#Cv'#CvOOQO'#Cx'#CxOOQO'#Dz'#DzO&_QQO'#C|O%vQQO'#CzOOQO'#Dy'#DyQ'qQQOOOVQQO'#DUOOQO'#Dw'#DwOVQQO'#DwO(xQSO,58xO(}QQO'#CrOOQO,59[,59[O%hQQO,59TOOQO,59`,59`OOQO,59S,59SOOQO,59f,59fO%vQQO,59iO%vQQO,59jOVQQO,59lOVQQO,59nOVQQO,59rOOQO'#DY'#DYOVQQO,59sOOQO'#D['#D[OVQQO,59uOVQQO,59wOVQQO,59yOVQQO,59zOVQQO,59|OVQQO,5:OOVQQO,5:QOVQQO,5:SOVQQO,5:UOOQO'#Dm'#DmOVQQO,5:WOOQO'#Do'#DoOVQQO,5:YO)UQQO,59pO*iQQO,5:cOOQP'#C`'#C`O*pQRO1G.dOOQO,59^,59^O*uQQO,59^OOQO1G.o1G.oOOQO1G/T1G/TOOQO1G/U1G/UO+PQQO1G/WO+WQQO1G/YO,kQQO1G/^O.OQQO1G/_O/cQQO1G/aO1_QQO1G/cO2_QQO1G/eO3_QQO1G/fO4_QQO1G/hO5_QQO1G/jO6_QQO1G/lO7_QQO1G/nO8_QQO1G/pO9_QQO1G/rO:_QQO1G/tOOQO1G/}1G/}O;_QQO'#DpO;dQRO7+$OOVQQO'#DqO<zQQO1G.xOOQO1G.x1G.xOOQO7+$r7+$rO=SQRO,5:[OOQP-E7n-E7nO=XQQO,5:]OOQO-E7o-E7oOOQO7+$d7+$dO=cQSO1G/vOOQP'#Cb'#CbOOQP7+%b7+%b",
	stateData:
		"=s~O!jOS~ORPOT_OVdOWeOYdOZdObSOiZOk[Om]Oo`OycO!oQO!rRO!sTO~O!gfO~OT!qXW!qX_^Xb!qXo!qXu!qXw!qXy!qX!Q!qX!T!qX!V!qX!X!qX!Z!qX!]!qX!_!qX!f!qX!t!qX!u!qX!v!qX!w!qXX!qXg!qXs!qX~OT`XWeXb`Xo`Xu`Xw`Xy`X!Q`X!T`X!V`X!X`X!Z`X!]`X!_`X!f`X!t`X!u`X!v`X!w`XX`Xg`Xs`X~OWgO~O_iO~ObSO!oRO!rRO!sTO~ObSOiZOk[Om]O!oQO!rRO!sTO~OTpXopXupXwpXypX!QpX!TpX!VpX!XpX!ZpX!]pX!_pX!fpX!tpX!upX!vpX!wpXXpXgpXspX~P%vOTmObqOonOuoOwpOywO!QvO!TxO!VyO!XzO!Z{O!]|O!_}O!trO!utO!v!OO!w!QO~O!l!UO~OX!WO~PVOTmOonOuoOwpObxayxa!Qxa!Txa!Vxa!Xxa!Zxa!]xa!_xa!fxa!txa!uxa!vxa!wxaXxagxasxa~OX!lO~P'qO!h!mO~OX!qOg!oO~P'qOs!rO~P'qOTmOonOuoObviwviyvi!Qvi!Tvi!Vvi!Xvi!Zvi!]vi!_vi!fvi!tvi!uvi!vvi!wviXvigvisvi~OTmOonOuoOwpObziyzi!Qzi!Tzi!Vzi!Xzi!Zzi!]zi!_zi!fzi!tzi!uzi!vzi!wziXzigziszi~OTmOonOuoOwpOb{iy{i!Q{i!T{i!V{i!X{i!Z{i!]{i!_{i!f{i!t{i!u{i!v{i!w{iX{ig{is{i~OTmOonOuoOwpOb}iy}i!Q}i!T}i!V}i!X}i!Z}i!]}i!_}i!f}i!t}i!u}i!v}i!w}iX}ig}is}i~OTmObqOonOuoOwpO!trO!utO~Oy!Pi!Q!Pi!T!Pi!V!Pi!X!Pi!Z!Pi!]!Pi!_!Pi!f!Pi!v!Pi!w!PiX!Pig!Pis!Pi~P0vOy!Ri!Q!Ri!T!Ri!V!Ri!X!Ri!Z!Ri!]!Ri!_!Ri!f!Ri!v!Ri!w!RiX!Rig!Ris!Ri~P0vOywO!QvO!T!Si!V!Si!X!Si!Z!Si!]!Si!_!Si!f!Si!v!Si!w!SiX!Sig!Sis!Si~P0vOywO!QvO!T!Ui!V!Ui!X!Ui!Z!Ui!]!Ui!_!Ui!f!Ui!v!Ui!w!UiX!Uig!Uis!Ui~P0vOywO!QvO!T!Wi!V!Wi!X!Wi!Z!Wi!]!Wi!_!Wi!f!Wi!v!Wi!w!WiX!Wig!Wis!Wi~P0vOywO!QvO!T!Yi!V!Yi!X!Yi!Z!Yi!]!Yi!_!Yi!f!Yi!v!Yi!w!YiX!Yig!Yis!Yi~P0vOywO!QvO!TxO!VyO!XzO!Z{O!]![i!_![i!f![i!v![i!w![iX![ig![is![i~P0vOywO!QvO!TxO!VyO!XzO!Z{O!]!^i!_!^i!f!^i!v!^i!w!^iX!^ig!^is!^i~P0vOywO!QvO!TxO!VyO!XzO!Z{O!]|O!_}O!f!`i!v!`i!w!`iX!`ig!`is!`i~P0vOywO!QvO!TxO!VyO!XzO!Z{O!]|O!_}O!v!OO!f!bi!w!biX!big!bis!bi~P0vOT!sO~O!h!mOTQqbQqoQquQqwQqyQq!QQq!TQq!VQq!XQq!ZQq!]Qq!_Qq!fQq!tQq!uQq!vQq!wQqXQqgQqsQq~OX!wOg!oO~O!g!xO~OX!eag!ea~P'qO!l!yO~OoTmZk!s!r!oRk~",
	goto: "+i!rPP!sP#ZP#^PPPPP#a#w$cP$}%kP%k$}&X&uP#wP#wP#wP#aP!s!s!sP!sP!sP!sP!s!s&x!s'Z!sP!s!sP!sP!sP!sP!sP!sP!s'l!s't'{(RPPPPP(XP!s)gP*Z*{ydOcegopqsuvwxyz{|}!P!R!oR!VfR!z!xyaOcegopqsuvwxyz{|}!P!R!o!R^O_`cegmnopqsuvwxyz{|}!P!R!o!RYO_`cegmnopqsuvwxyz{|}!P!R!o!VXOZ_`cegimnopqsuvwxyz{|}!P!R!o!VVOZ_`cegimnopqsuvwxyz{|}!P!R!o!VWOZ_`cegimnopqsuvwxyz{|}!P!R!oRhWosb!T!X!]!b!c!d!e!f!g!h!i!j!k!uoub!T!X!]!b!c!d!e!f!g!h!i!j!k!u]!Pb!T!X!]!k!uZ!Rb!T!X!]!uQ!n!VR!t!nQ!p!XR!v!pQbOQ!ScQ!TeQ!XgQ!]oQ!^pQ!_qQ!`sQ!auQ!bvQ!cwQ!dxQ!eyQ!fzQ!g{Q!h|Q!i}Q!j!PQ!k!RR!u!oxdOcegopqsuvwxyz{|}!P!R!oQk_Ql`Q!ZmR![n!Q^O_`cegmnopqsuvwxyz{|}!P!R!oQjZR!Yi!VUOZ_`cegimnopqsuvwxyz{|}!P!R!o",
	nodeNames:
		"⚠ XPath HashtagRef # HashtagType / HashtagSegment VariableReference ( ) StringLiteral NumberLiteral Child AxisSpecified AxisName :: NameTest Wildcard * QualifiedWildcard Invoke FunctionName ArgumentList , AttrSpecified @ SelfStep . ParentStep .. Descendant // RootPath Child Descendant ] Filtered [ UnionExpr | UnaryNegativeExpr - MultiplyExpr DivideExpr Keyword ModulusExpr Keyword AddExpr + SubtractExpr GreaterThanExpr > GreaterEqualExpr >= LessThanExpr < LessEqualExpr <= NotEqualsExpr != EqualsExpr = AndExpr Keyword OrExpr Keyword",
	maxTerm: 85,
	nodeProps: [
		["closedBy", 8, ")"],
		["openedBy", 9, "("],
	],
	skippedNodes: [0],
	repeatNodeCount: 2,
	tokenData:
		"2o~RxXY#oYZ#o]^#opq#oqr$Qrs$]st$ztu%Pwx)rxy*[yz*az{*f{|*k|}*p}!O*u!O!P*z!P!Q+d!Q![+q![!]+|!^!_,X!_!`,f!`!a,k!b!c,x!c!},}!}#O2`#P#Q2e#R#S,}#T#o,}#p#q2j%W%o0{%p&a0{&b1p0{4U4d0{4e$IS0{$I`$Ib0{$Kh%#t0{&/x&Et0{&FV;'S0{?&r?Ah0{?BY?Mn0{~#tS!j~XY#oYZ#o]^#opq#o~$TP!_!`$W~$]O!]~~$`TOr$]rs$os;'S$];'S;=`$t<%lO$]~$tOY~~$wP;=`<%l$]~%POR~~%S^!c!}&O#R#S&O#T#o&O%W%o&O%p&a&O&b1p&O4U4d&O4e$IS&O$I`$Ib&O$Kh%#t&O&/x&Et&O&FV;'S&O?&r?Ah&O?BY?Mn&O~&TdV~}!O&O!Q![&O![!]'c!c!}&O#R#S&O#T#o&O$}%O&O%W%o&O%p&a&O&b1p&O1p4U&O4U4d&O4e$IS&O$I`$Ib&O$Je$Jg&O$Kh%#t&O&/x&Et&O&FV;'S&O?&r?Ah&O?BY?Mn&O~'f^!c!}(b#R#S(b#T#o(b%W%o(b%p&a(b&b1p(b4U4d(b4e$IS(b$I`$Ib(b$Kh%#t(b&/x&Et(b&FV;'S(b?&r?Ah(b?BY?Mn(b~(gcV~}!O(b!Q![(b!c!}(b#R#S(b#T#o(b$}%O(b%W%o(b%p&a(b&b1p(b1p4U(b4U4d(b4e$IS(b$I`$Ib(b$Je$Jg(b$Kh%#t(b&/x&Et(b&FV;'S(b?&r?Ah(b?BY?Mn(b~)uTOw)rwx$ox;'S)r;'S;=`*U<%lO)r~*XP;=`<%l)r~*aOW~~*fOX~~*kOb~~*pO!Q~~*uOg~~*zOy~~+PQk~!O!P+V!Q![+[~+[Om~~+aPZ~!Q![+[~+iPT~!P!Q+l~+qOo~~+vQZ~!O!P+[!Q![+q~,PP![!],S~,XO_~~,^P!X~!_!`,a~,fO!Z~~,kO!_~~,pP!T~!_!`,s~,xO!V~~,}Oi~R-Ud!lQ!oP}!O,}!Q![,}![!].d!c!},}#R#S,}#T#o,}$}%O0{%W%o0{%p&a0{&b1p0{1p4U0{4U4d0{4e$IS0{$I`$Ib0{$Je$Jg0{$Kh%#t0{&/x&Et0{&FV;'S0{?&r?Ah0{?BY?Mn0{P.g_z{/f!c!}/k#R#S/k#T#o/k%W%o/k%p&a/k&b1p/k4U4d/k4e$IS/k$I`$Ib/k$Kh%#t/k&/x&Et/k&FV;'S/k?&r?Ah/k?BY?Mn/kP/kO!sPP/pc!rP}!O/k!Q![/k!c!}/k#R#S/k#T#o/k$}%O/k%W%o/k%p&a/k&b1p/k1p4U/k4U4d/k4e$IS/k$I`$Ib/k$Je$Jg/k$Kh%#t/k&/x&Et/k&FV;'S/k?&r?Ah/k?BY?Mn/kP1Qd!oP}!O0{!Q![0{![!].d!c!}0{#R#S0{#T#o0{$}%O0{%W%o0{%p&a0{&b1p0{1p4U0{4U4d0{4e$IS0{$I`$Ib0{$Je$Jg0{$Kh%#t0{&/x&Et0{&FV;'S0{?&r?Ah0{?BY?Mn0{~2eOu~~2jOs~~2oOw~",
	tokenizers: [hashtagGuard, 0, 1],
	topRules: { XPath: [0, 1] },
	specialized: [
		{
			term: 77,
			get: (value: keyof typeof spec_localName) => spec_localName[value] || -1,
		},
	],
	tokenPrec: 1312,
});
