// lib/domain/builtinIcons.catalog.ts
//
// AUTO-GENERATED by scripts/build-builtin-icons.ts — DO NOT EDIT BY HAND.
// Regenerate: NOVA_ICONS_SRC=<path-to-nova-claude-design-icons> npx tsx scripts/build-builtin-icons.ts
//
// Source: Nova default module & form icons v1.0.0 (Tabler Icons, MIT, rasterized).
// Each PNG ships at public/nova-icons/<slug>.png, 512×512 RGBA.
// The hand-written helpers + types that wrap this data live in ./builtinIcons.ts.

/** One shipped built-in icon. `contentHash` is the SHA-256 of the crunched PNG
 *  bytes (the wire path + dedup key); `sizeBytes` feeds the export budget. */
export const BUILTIN_ICON_CATALOG = [
	{
		slug: "household",
		kind: "module",
		label: "Households",
		tabler: "home",
		contentHash:
			"5b77ca365eab09731969cc143655d407544b75ecc5ccf7eef3309b79f80add17",
		sizeBytes: 25781,
	},
	{
		slug: "community",
		kind: "module",
		label: "Community",
		tabler: "users",
		contentHash:
			"f15b59b1d3d71114a317498022d2061627bc6c02020fc03f362316c0ba31a820",
		sizeBytes: 28409,
	},
	{
		slug: "patient",
		kind: "module",
		label: "Patients",
		tabler: "user-heart",
		contentHash:
			"348ba267f459c5d5455600b7cef9e5f0d67e43d08a01088fcf91f3350e4cdab0",
		sizeBytes: 27057,
	},
	{
		slug: "chw_staff",
		kind: "module",
		label: "Health workers",
		tabler: "nurse",
		contentHash:
			"8f424c4574a61f86dacb888917d0cd28a417f8b425094064dddedd58fd123414",
		sizeBytes: 25881,
	},
	{
		slug: "maternal_health",
		kind: "module",
		label: "Maternal health",
		tabler: "heart-rate-monitor",
		contentHash:
			"d62670548fe704dda4ed7d065c006d771bdf5be6f3948263b693a31b490f5a17",
		sizeBytes: 25593,
	},
	{
		slug: "child_health",
		kind: "module",
		label: "Child health",
		tabler: "mood-kid",
		contentHash:
			"b5d3e13cc35569d2eeea72f3fafc6722ad1950543ec2749f044118700f7e184e",
		sizeBytes: 27837,
	},
	{
		slug: "newborn_care",
		kind: "module",
		label: "Newborn care",
		tabler: "baby-bottle",
		contentHash:
			"7d5ef1ae12f16f862dae69e764f5dde4099d9819d3984477a821ebe73ee5ee60",
		sizeBytes: 25848,
	},
	{
		slug: "immunization",
		kind: "module",
		label: "Immunization",
		tabler: "vaccine",
		contentHash:
			"46d190ae4a1f15f2dce27e19fcc21eb9492508ff77fcd09e90efb0a53d99a741",
		sizeBytes: 25180,
	},
	{
		slug: "nutrition",
		kind: "module",
		label: "Nutrition",
		tabler: "apple",
		contentHash:
			"950acd5fc742e7aa6938dceeced89a9cfc94c6baf79146432848caad675cb627",
		sizeBytes: 27478,
	},
	{
		slug: "growth_monitoring",
		kind: "module",
		label: "Growth monitoring",
		tabler: "chart-line",
		contentHash:
			"76085656c40aa06264a3e7061541cb238ba678a71a73909286c8e50f3d95f0ad",
		sizeBytes: 24228,
	},
	{
		slug: "family_planning",
		kind: "module",
		label: "Family planning",
		tabler: "gender-bigender",
		contentHash:
			"58bc00c93e7d87ae1817693920337960f9c42e1bdb91aaae221de046e04c7a8e",
		sizeBytes: 25676,
	},
	{
		slug: "hiv",
		kind: "module",
		label: "HIV care",
		tabler: "ribbon-health",
		contentHash:
			"2afc7f28828f34adc65dcf9e3eea957e595ee055530ebb13367a90cd9a9f4c34",
		sizeBytes: 26219,
	},
	{
		slug: "tuberculosis",
		kind: "module",
		label: "Tuberculosis",
		tabler: "lungs",
		contentHash:
			"ad207b46c2653679cda813b63b7c7b66b2bdf7daa4f623d40415f41ec80739aa",
		sizeBytes: 27951,
	},
	{
		slug: "malaria",
		kind: "module",
		label: "Malaria",
		tabler: "bug",
		contentHash:
			"94b8d28ed3b5ef7de633ec5f7d0dc4b47881ab67d5783377f32fd18fa98bace7",
		sizeBytes: 26514,
	},
	{
		slug: "disease_surveillance",
		kind: "module",
		label: "Surveillance",
		tabler: "virus-search",
		contentHash:
			"897857cda321423f03ed0711b9da553d815f91270cbbe7e47a7cd90797561b8b",
		sizeBytes: 28205,
	},
	{
		slug: "mental_health",
		kind: "module",
		label: "Mental health",
		tabler: "brain",
		contentHash:
			"61e99ae11f5ad4862debafa2e6a5fbdaf78bd69a82970fbd364e50af01866d0d",
		sizeBytes: 28445,
	},
	{
		slug: "substance_use",
		kind: "module",
		label: "Substance use",
		tabler: "bottle",
		contentHash:
			"c84a149a4c0f00b73adcbd363e8ea4c888a9cf1acbb0a6fb30a1a8cc538edbc9",
		sizeBytes: 25998,
	},
	{
		slug: "oral_health",
		kind: "module",
		label: "Oral health",
		tabler: "dental",
		contentHash:
			"d62093c32b7cbefc9a8eb65475a903018ebd51683d392effa7ea6fd61e1b0cc7",
		sizeBytes: 27715,
	},
	{
		slug: "eye_care",
		kind: "module",
		label: "Eye care",
		tabler: "eye",
		contentHash:
			"3503b564a44cd65b0fc39bb2a7a161bfbe96d626c8650d82bb703a2776557f51",
		sizeBytes: 27147,
	},
	{
		slug: "facility",
		kind: "module",
		label: "Facilities",
		tabler: "building-hospital",
		contentHash:
			"c821ef9ad423075abfdb7a00d81596fe4f64923d47f89569f5933c4c9c0a36c3",
		sizeBytes: 26321,
	},
	{
		slug: "bed_capacity",
		kind: "module",
		label: "Bed capacity",
		tabler: "bed",
		contentHash:
			"f6003885981ef1ccd42000cdb0a5acf1b3b82a3db9b4156212586933cf4a2965",
		sizeBytes: 25121,
	},
	{
		slug: "pharmacy_stock",
		kind: "module",
		label: "Pharmacy & stock",
		tabler: "building-store",
		contentHash:
			"7b8b11a9e6c1dbce7af21685cb2294f66730d09ec25aff3fa6138266798e093e",
		sizeBytes: 26040,
	},
	{
		slug: "medications",
		kind: "module",
		label: "Medications",
		tabler: "pills",
		contentHash:
			"c90d8c53b3102fcaefe80752e14e649dc4feb949dc04c15bc97e8227d5deaa19",
		sizeBytes: 26738,
	},
	{
		slug: "lab",
		kind: "module",
		label: "Laboratory",
		tabler: "microscope",
		contentHash:
			"4fe4f942cf0443fcb9d93f2b0ca63d51f838dd0e586804d1fd401e8cd48b9b1b",
		sizeBytes: 25174,
	},
	{
		slug: "diagnostics",
		kind: "module",
		label: "Diagnostics",
		tabler: "test-pipe",
		contentHash:
			"6b99d8577aa0d9fb7ed0cffc14df74e93fc581cea090e187b7c1c29236de0077",
		sizeBytes: 25472,
	},
	{
		slug: "screening",
		kind: "module",
		label: "Screening",
		tabler: "zoom-check",
		contentHash:
			"8c6bb077c0846b0b7bb476f895e1626092f7d3c155c462caabef9cdd6f5231eb",
		sizeBytes: 27115,
	},
	{
		slug: "referrals",
		kind: "module",
		label: "Referrals",
		tabler: "route",
		contentHash:
			"20683faf0604b417a42a4b1f0bbd3de4a183bf58601f68f744185a493a278bc0",
		sizeBytes: 26049,
	},
	{
		slug: "appointments",
		kind: "module",
		label: "Appointments",
		tabler: "calendar-event",
		contentHash:
			"f6ada083e3297a8898d5acf37d927a5d275d9858937e76d5d541eb27edb37bae",
		sizeBytes: 25253,
	},
	{
		slug: "vital_events",
		kind: "module",
		label: "Births & deaths",
		tabler: "certificate",
		contentHash:
			"52c36feca2c4ff6a95ddb691b5c80a1700afb7accf063b4de8c8622ea0070676",
		sizeBytes: 27557,
	},
	{
		slug: "education",
		kind: "module",
		label: "Health education",
		tabler: "school",
		contentHash:
			"1bc19fb8631e20120956c006469cf0419b278fb1554ecf2c9303648dc69b01b9",
		sizeBytes: 24992,
	},
	{
		slug: "tasks",
		kind: "module",
		label: "Tasks",
		tabler: "list-check",
		contentHash:
			"644b528bd0d6297b6b811fba2031d5d6aac1c3b8eef37e79a77e174ec02b1aab",
		sizeBytes: 24617,
	},
	{
		slug: "alerts",
		kind: "module",
		label: "Alerts & risk",
		tabler: "alert-triangle",
		contentHash:
			"4c3cb59586838c3f7e528be5abd146c71ea45830e5142f2f77f8b99c55003154",
		sizeBytes: 25326,
	},
	{
		slug: "reports",
		kind: "module",
		label: "Reports",
		tabler: "report-medical",
		contentHash:
			"688b0025b94d4506409a575c356f603ba477b1e283d32d4a45cb5307687c3f8a",
		sizeBytes: 26632,
	},
	{
		slug: "register",
		kind: "form",
		label: "Register / enroll",
		tabler: "user-plus",
		contentHash:
			"7b6eea324eec1a6c05d20f96d0add3859f23329d942cd590d644113134eaeb6d",
		sizeBytes: 25930,
	},
	{
		slug: "update",
		kind: "form",
		label: "Update details",
		tabler: "pencil",
		contentHash:
			"11a1b6073f1df1d913d99e8463ab761b09424a0316df5e9c593b560cc9324e03",
		sizeBytes: 24662,
	},
	{
		slug: "follow_up",
		kind: "form",
		label: "Follow-up visit",
		tabler: "calendar-repeat",
		contentHash:
			"deda38803a92523aad7d9e7a987c68e1f318bce0046424ceefd2f38cd9c7cbd5",
		sizeBytes: 25988,
	},
	{
		slug: "record_vitals",
		kind: "form",
		label: "Record vitals",
		tabler: "activity",
		contentHash:
			"8f54e1ce03a6a4aafbea6cf29325e8350c1890eac3d09e33183bc24da7e95742",
		sizeBytes: 24582,
	},
	{
		slug: "screen_assess",
		kind: "form",
		label: "Screen / assess",
		tabler: "clipboard-check",
		contentHash:
			"4dc8ed53cece94a1e105f44fe9d799891bf45880b540f3df53eea66aee9f90d4",
		sizeBytes: 25734,
	},
	{
		slug: "administer",
		kind: "form",
		label: "Administer",
		tabler: "vaccine-bottle",
		contentHash:
			"2d84bb32b9669150bbaf8f88510be2042e9a938fb6518d7e0e1f31392396c5e1",
		sizeBytes: 25611,
	},
	{
		slug: "collect_sample",
		kind: "form",
		label: "Collect sample",
		tabler: "droplet",
		contentHash:
			"95eca735f068cfd2b4ff1a9630eafc2bfb1eef77b3866c5b9ff1651d7a07dbf5",
		sizeBytes: 25949,
	},
	{
		slug: "counsel",
		kind: "form",
		label: "Counsel / educate",
		tabler: "message-heart",
		contentHash:
			"e22bd50572feb166df8a8ffa5f8f513721d38188eef081df9477c9b07f9d8620",
		sizeBytes: 26911,
	},
	{
		slug: "schedule",
		kind: "form",
		label: "Schedule",
		tabler: "calendar-plus",
		contentHash:
			"4eaf836d4cd06454696a2c778d8a0b3d527c9fbaed15018ad9251b7f6397ac00",
		sizeBytes: 25703,
	},
	{
		slug: "refer",
		kind: "form",
		label: "Make referral",
		tabler: "arrow-forward",
		contentHash:
			"a830cda8030e7e2ccd576b7efed15fe982643a30b8b5e5e5fee1a2332ae92417",
		sizeBytes: 24215,
	},
	{
		slug: "consent",
		kind: "form",
		label: "Record consent",
		tabler: "file-check",
		contentHash:
			"82bf8629da05a51026cdeb7c4be527384d405ca9537ada5f6288014f06ac5160",
		sizeBytes: 25281,
	},
	{
		slug: "checklist",
		kind: "form",
		label: "Checklist / survey",
		tabler: "checklist",
		contentHash:
			"7bdd1e99cce9acb1a0dd282c9b157083aca69224250263bbdc86690d99d62262",
		sizeBytes: 25143,
	},
	{
		slug: "close_case",
		kind: "form",
		label: "Close / discharge",
		tabler: "circle-check",
		contentHash:
			"02b657e683155b593ab2ba249ec25d8c021f253f67351e063628e93b9fcb793b",
		sizeBytes: 27837,
	},
	{
		slug: "default",
		kind: "fallback",
		label: "Default",
		tabler: "apps",
		contentHash:
			"fc81fd4fb097d0468ecdf305e434d1411e30ce8fbf4d63121947d3f37a6e048d",
		sizeBytes: 26101,
	},
] as const;

/** Slugs offered on module create/update tools — the 33 topic icons + `default`. */
export const MODULE_ICON_SLUGS = [
	"household",
	"community",
	"patient",
	"chw_staff",
	"maternal_health",
	"child_health",
	"newborn_care",
	"immunization",
	"nutrition",
	"growth_monitoring",
	"family_planning",
	"hiv",
	"tuberculosis",
	"malaria",
	"disease_surveillance",
	"mental_health",
	"substance_use",
	"oral_health",
	"eye_care",
	"facility",
	"bed_capacity",
	"pharmacy_stock",
	"medications",
	"lab",
	"diagnostics",
	"screening",
	"referrals",
	"appointments",
	"vital_events",
	"education",
	"tasks",
	"alerts",
	"reports",
	"default",
] as const;

/** Slugs offered on form create/update tools — the 13 action icons + `default`. */
export const FORM_ICON_SLUGS = [
	"register",
	"update",
	"follow_up",
	"record_vitals",
	"screen_assess",
	"administer",
	"collect_sample",
	"counsel",
	"schedule",
	"refer",
	"consent",
	"checklist",
	"close_case",
	"default",
] as const;

/** Every built-in icon slug, in catalog order. */
export const ALL_ICON_SLUGS = [
	"household",
	"community",
	"patient",
	"chw_staff",
	"maternal_health",
	"child_health",
	"newborn_care",
	"immunization",
	"nutrition",
	"growth_monitoring",
	"family_planning",
	"hiv",
	"tuberculosis",
	"malaria",
	"disease_surveillance",
	"mental_health",
	"substance_use",
	"oral_health",
	"eye_care",
	"facility",
	"bed_capacity",
	"pharmacy_stock",
	"medications",
	"lab",
	"diagnostics",
	"screening",
	"referrals",
	"appointments",
	"vital_events",
	"education",
	"tasks",
	"alerts",
	"reports",
	"register",
	"update",
	"follow_up",
	"record_vitals",
	"screen_assess",
	"administer",
	"collect_sample",
	"counsel",
	"schedule",
	"refer",
	"consent",
	"checklist",
	"close_case",
	"default",
] as const;
