// lib/domain/builtinIcons.ts
//
// The built-in icon library: a curated set of gradient-tile + Tabler-glyph PNGs
// the SA agent and the builder can attach to a module/form menu tile by NAME.
//
// The win: setting a module/form icon is just an enum slug (`household`,
// `register`, …) — no upload, no per-user asset. The blueprint stores a
// reserved-form `AssetId` (`nova-icon:<slug>`); every app points at ONE shared,
// deployment-bundled copy of the bytes (shipped at `public/nova-icons/<slug>.png`,
// read server-side at emit time). The kind/readiness discriminator is already a
// runtime, fail-closed concern (a built-in is always a ready image), so the
// reserved string slots into every existing media slot + mutation unchanged —
// no schema union. See `lib/media/CLAUDE.md`.
//
// The machine-owned data (catalog with content hashes + the slug tuples for the
// tool enums) lives in `./builtinIcons.catalog.ts`, regenerated by
// `scripts/build-builtin-icons.ts`. This module is the hand-written wrapper:
// types + the ref/path helpers every surface shares. It is a `lib/domain` leaf —
// imported by both the client (`useAttachBudget`) and the server (`lib/media`),
// so it pulls in no `lib/commcare`, Firestore, or `server-only`.

import {
	ALL_ICON_SLUGS,
	BUILTIN_ICON_CATALOG,
	FORM_ICON_SLUGS,
	MODULE_ICON_SLUGS,
} from "./builtinIcons.catalog";
import { type AssetId, asAssetId, NOVA_ICON_REF_PREFIX } from "./multimedia";

export { ALL_ICON_SLUGS, FORM_ICON_SLUGS, MODULE_ICON_SLUGS };

/** The full catalog of shipped built-in icons. */
export const ICON_CATALOG = BUILTIN_ICON_CATALOG;

/** One built-in icon's metadata + emit constants (content hash, byte size). */
export type IconCatalogEntry = (typeof BUILTIN_ICON_CATALOG)[number];

/** Every built-in icon slug. */
export type IconSlug = (typeof ALL_ICON_SLUGS)[number];
/** Slugs offered on module create/update tools (topic icons + `default`). */
export type ModuleIconSlug = (typeof MODULE_ICON_SLUGS)[number];
/** Slugs offered on form create/update tools (action icons + `default`). */
export type FormIconSlug = (typeof FORM_ICON_SLUGS)[number];

/** The two icon-slot families: module tiles (incl. case-list) take topic icons,
 *  form tiles take action icons. `default` is available to both. */
export type IconSlotKind = "module" | "form";

const CATALOG_BY_SLUG: ReadonlyMap<string, IconCatalogEntry> = new Map(
	BUILTIN_ICON_CATALOG.map((entry) => [entry.slug, entry]),
);

/** The catalog entry for a slug, or `undefined` for an unknown one. */
export function iconCatalogEntry(slug: string): IconCatalogEntry | undefined {
	return CATALOG_BY_SLUG.get(slug);
}

/** The reserved `AssetId` for a built-in icon — what a media slot stores. */
export function builtinIconRef(slug: IconSlug): AssetId {
	return asAssetId(`${NOVA_ICON_REF_PREFIX}${slug}`);
}

/** Whether an asset id refers to a built-in icon (a cheap prefix check — routes
 *  the ref AWAY from Firestore/GCS before any lookup; stale slugs included, they
 *  fail closed downstream). */
export function isBuiltinIconRef(id: string): boolean {
	return id.startsWith(NOVA_ICON_REF_PREFIX);
}

/** The catalog slug a built-in ref names, or `null` if it isn't one / is stale.
 *  A stale slug (in the doc but gone from the catalog) returns `null` so it
 *  fails closed exactly like a deleted upload. */
export function parseBuiltinIconSlug(id: string): IconSlug | null {
	if (!isBuiltinIconRef(id)) return null;
	const slug = id.slice(NOVA_ICON_REF_PREFIX.length);
	return CATALOG_BY_SLUG.has(slug) ? (slug as IconSlug) : null;
}

/** The browser URL for a built-in icon's bytes (static, CDN-cacheable). */
export function builtinIconPublicPath(slug: string): string {
	return `/nova-icons/${slug}.png`;
}

/** The icons to offer for an icon slot — the slot's family plus the `default`
 *  fallback, in catalog order. Module + case-list slots pass `"module"`; form
 *  slots pass `"form"`. */
export function builtinIconsForSlot(
	slot: IconSlotKind,
): readonly IconCatalogEntry[] {
	return BUILTIN_ICON_CATALOG.filter(
		(entry) => entry.kind === slot || entry.kind === "fallback",
	);
}
