// lib/domain/builtinIcons.ts
//
// The built-in icon library: a curated set of gradient-tile + Tabler-glyph PNGs
// the SA agent and the builder can attach to a module/form menu tile by NAME.
//
// The win: setting a module/form icon is just an enum slug (`household`,
// `register`, …) — no upload, no per-user asset. The blueprint stores one exact,
// closed `BuiltinIconRef` (`nova-icon:<slug>`); every app points at ONE shared,
// deployment-bundled copy of the bytes (shipped at
// `public/nova-icons/<slug>.png`, read server-side at emit time). Uploaded
// `MediaAssetId`s remain strict UUIDs. Menu icon slots explicitly union the two
// identity families and further restrict built-ins to the matching module/form
// catalog. See `lib/media/CLAUDE.md`.
//
// The machine-owned data (catalog with content hashes + the slug tuples for the
// tool enums) lives in `./builtinIcons.catalog.ts`, regenerated by
// `scripts/build-builtin-icons.ts`. This module is the hand-written wrapper:
// types + the ref/path helpers every surface shares. It is a `lib/domain` leaf —
// imported by both the client (`useAttachBudget`) and the server (`lib/media`),
// so it pulls in no `lib/commcare`, `lib/db`, or `server-only`.

import { z } from "zod";
import {
	ALL_ICON_SLUGS,
	BUILTIN_ICON_CATALOG,
	FORM_ICON_SLUGS,
	MODULE_ICON_SLUGS,
} from "./builtinIcons.catalog";
import { type MediaAssetId, mediaAssetIdSchema } from "./multimedia";

export { ALL_ICON_SLUGS, FORM_ICON_SLUGS, MODULE_ICON_SLUGS };

/** The full catalog of shipped built-in icons. */
export const ICON_CATALOG = BUILTIN_ICON_CATALOG;

/** One built-in icon's metadata + emit constants (content hash, byte size). */
export type IconCatalogEntry = (typeof BUILTIN_ICON_CATALOG)[number];

/** Every built-in icon slug. */
export type IconSlug = (typeof ALL_ICON_SLUGS)[number];
/** Slugs offered on `set_menu_media`'s module arm (topic icons + `default`). */
export type ModuleIconSlug = (typeof MODULE_ICON_SLUGS)[number];
/** Slugs offered on `set_menu_media`'s form arm (action icons + `default`). */
export type FormIconSlug = (typeof FORM_ICON_SLUGS)[number];

/** The two icon-slot families: module tiles (incl. case-list) take topic icons,
 *  form tiles take action icons. `default` is available to both. */
export type IconSlotKind = "module" | "form";

/** Reserved prefix for deployment-bundled icon identities. */
export const NOVA_ICON_REF_PREFIX = "nova-icon:";

export type BuiltinIconRef = `${typeof NOVA_ICON_REF_PREFIX}${IconSlug}`;
export type BuiltinIconRefFor<Slug extends IconSlug> =
	`${typeof NOVA_ICON_REF_PREFIX}${Slug}`;
export type ModuleBuiltinIconRef =
	`${typeof NOVA_ICON_REF_PREFIX}${ModuleIconSlug}`;
export type FormBuiltinIconRef =
	`${typeof NOVA_ICON_REF_PREFIX}${FormIconSlug}`;

function refsFor<const Slugs extends readonly string[]>(
	slugs: Slugs,
): [`${typeof NOVA_ICON_REF_PREFIX}${Slugs[number]}`, ...string[]] {
	return slugs.map((slug) => `${NOVA_ICON_REF_PREFIX}${slug}`) as [
		`${typeof NOVA_ICON_REF_PREFIX}${Slugs[number]}`,
		...string[],
	];
}

export const BUILTIN_ICON_REFS = refsFor(ALL_ICON_SLUGS);
export const MODULE_BUILTIN_ICON_REFS = refsFor(MODULE_ICON_SLUGS);
export const FORM_BUILTIN_ICON_REFS = refsFor(FORM_ICON_SLUGS);

/** Closed schemas: prefix recognition alone is never validation. */
export const builtinIconRefSchema = z.enum(
	BUILTIN_ICON_REFS,
) as z.ZodType<BuiltinIconRef>;
export const moduleBuiltinIconRefSchema = z.enum(
	MODULE_BUILTIN_ICON_REFS,
) as z.ZodType<ModuleBuiltinIconRef>;
export const formBuiltinIconRefSchema = z.enum(
	FORM_BUILTIN_ICON_REFS,
) as z.ZodType<FormBuiltinIconRef>;

/** Uploaded-or-built-in union used only by the matching menu icon slot. */
export type IconRef = MediaAssetId | BuiltinIconRef;
export type ModuleIconRef = MediaAssetId | ModuleBuiltinIconRef;
export type FormIconRef = MediaAssetId | FormBuiltinIconRef;
/* There is deliberately no schema over the loose `IconRef` union: a slot must
 * parse through the module or form catalog so a built-in valid in one family
 * cannot be accepted in the other. The loose TYPE survives for the emission
 * layer, which resolves either family through one asset manifest. */
export const moduleIconRefSchema = z.union([
	mediaAssetIdSchema,
	moduleBuiltinIconRefSchema,
]) as z.ZodType<ModuleIconRef>;
export const formIconRefSchema = z.union([
	mediaAssetIdSchema,
	formBuiltinIconRefSchema,
]) as z.ZodType<FormIconRef>;

const CATALOG_BY_SLUG: ReadonlyMap<string, IconCatalogEntry> = new Map(
	BUILTIN_ICON_CATALOG.map((entry) => [entry.slug, entry]),
);

/** The catalog entry for a slug, or `undefined` for an unknown one. */
export function iconCatalogEntry(slug: string): IconCatalogEntry | undefined {
	return CATALOG_BY_SLUG.get(slug);
}

/** The reserved identity for a built-in icon — what a menu icon slot stores. */
export function builtinIconRef<Slug extends IconSlug>(
	slug: Slug,
): BuiltinIconRefFor<Slug> {
	return `${NOVA_ICON_REF_PREFIX}${slug}` as BuiltinIconRefFor<Slug>;
}

/** Whether a value is one of the exact shipped built-in identities. */
export function isBuiltinIconRef(id: string): id is BuiltinIconRef {
	return builtinIconRefSchema.safeParse(id).success;
}

/** The catalog slug a validated built-in ref names, or `null` otherwise. */
export function parseBuiltinIconSlug(id: string): IconSlug | null {
	if (!isBuiltinIconRef(id)) return null;
	const slug = id.slice(NOVA_ICON_REF_PREFIX.length);
	return slug as IconSlug;
}

/** The browser URL for a built-in icon's bytes (static, CDN-cacheable). */
export function builtinIconPublicPath(slug: string): string {
	return `/nova-icons/${slug}.png`;
}

/** The icons to offer for an icon slot — the slot's family plus the `default`
 *  fallback, in catalog order. Module + case-list slots pass `"module"`; form
 *  slots pass `"form"`. */
export function builtinIconsForSlot(
	slot: IconSlotKind,
): readonly IconCatalogEntry[] {
	return BUILTIN_ICON_CATALOG.filter(
		(entry) => entry.kind === slot || entry.kind === "fallback",
	);
}
