// Worker-facing validation copy generated by the case-search compiler. These
// strings are not authored on one Blueprint slot, but they still belong to the
// app's translation inventory: CommCare renders them inside the running app.

export const searchRuntimeValidationKinds = [
	"geopoint",
	"whole-number",
	"nonnegative-whole-number",
	"quote",
] as const;
export type SearchRuntimeValidationKind =
	(typeof searchRuntimeValidationKinds)[number];

export interface SearchRuntimeValidationMessage {
	readonly key: string;
	readonly message: string;
	readonly description: string;
}

export const DATE_RANGE_PAIR_REQUIRED_MESSAGE =
	"Choose both a start date and an end date";
export const DATE_RANGE_ORDER_MESSAGE =
	"Choose an end date on or after the start date";
export const DATE_RANGE_INVALID_MESSAGE = "Choose valid start and end dates";
export const DATE_RANGE_CONFIGURATION_MESSAGE =
	"This search field's date settings don't match. Return to edit and choose Date range with Between dates";

const DATE_RANGE_MESSAGES: readonly SearchRuntimeValidationMessage[] = [
	{
		key: "date-range:pair-required",
		message: DATE_RANGE_PAIR_REQUIRED_MESSAGE,
		description: "Search date-range completeness",
	},
	{
		key: "date-range:order",
		message: DATE_RANGE_ORDER_MESSAGE,
		description: "Search date-range ordering",
	},
	{
		key: "date-range:invalid",
		message: DATE_RANGE_INVALID_MESSAGE,
		description: "Search date-range validity",
	},
	{
		key: "date-range:configuration",
		message: DATE_RANGE_CONFIGURATION_MESSAGE,
		description: "Search date-range configuration recovery",
	},
];

const SINGLE_MESSAGES: Readonly<
	Record<
		SearchRuntimeValidationKind,
		Omit<SearchRuntimeValidationMessage, "key">
	>
> = {
	geopoint: {
		message: "Enter a location as latitude and longitude",
		description: "Search location format",
	},
	"whole-number": {
		message: "Enter a whole number",
		description: "Search whole-number format",
	},
	"nonnegative-whole-number": {
		message: "Enter a whole number that is zero or greater",
		description: "Search nonnegative whole-number format",
	},
	quote: {
		message:
			"This search can't use both single and double quotation marks. Remove one kind and try again",
		description: "Search quotation-mark compatibility",
	},
};

const GLOBAL_MESSAGES: Readonly<
	Record<
		SearchRuntimeValidationKind,
		Omit<SearchRuntimeValidationMessage, "key">
	>
> = {
	geopoint: {
		message:
			"This search's current location value needs a valid latitude and longitude",
		description: "Computed search location format",
	},
	"whole-number": {
		message: "This search's current value needs to be a whole number",
		description: "Computed search whole-number format",
	},
	"nonnegative-whole-number": {
		message:
			"This search's current value needs to be a whole number that is zero or greater",
		description: "Computed search nonnegative whole-number format",
	},
	quote: {
		message:
			"This search can't use the current value because it contains both single and double quotation marks",
		description: "Computed search quotation-mark compatibility",
	},
};

/** Worker-facing error for a rejected session- or computed-value binding. */
export function searchRuntimeGlobalValidationMessage(
	kind: SearchRuntimeValidationKind,
): SearchRuntimeValidationMessage {
	return { key: `global:${kind}`, ...GLOBAL_MESSAGES[kind] };
}

function normalizedKinds(
	kinds: ReadonlySet<SearchRuntimeValidationKind>,
): readonly SearchRuntimeValidationKind[] {
	const numberKind = kinds.has("nonnegative-whole-number")
		? "nonnegative-whole-number"
		: kinds.has("whole-number")
			? "whole-number"
			: undefined;
	const normalized: SearchRuntimeValidationKind[] = [];
	if (kinds.has("geopoint")) normalized.push("geopoint");
	if (numberKind !== undefined) normalized.push(numberKind);
	if (kinds.has("quote")) normalized.push("quote");
	return normalized;
}

export function searchRuntimeValidationMessage(
	kinds: ReadonlySet<SearchRuntimeValidationKind>,
): SearchRuntimeValidationMessage | undefined {
	const normalized = normalizedKinds(kinds);
	if (normalized.length === 0) return undefined;
	if (normalized.length === 1) {
		const kind = normalized[0];
		return { key: kind, ...SINGLE_MESSAGES[kind] };
	}
	const instructions: string[] = [];
	if (normalized.includes("geopoint")) {
		instructions.push("Enter a location as latitude and longitude");
	}
	if (normalized.includes("nonnegative-whole-number")) {
		instructions.push("enter a whole number that is zero or greater");
	} else if (normalized.includes("whole-number")) {
		instructions.push("enter a whole number");
	}
	if (normalized.includes("quote")) {
		instructions.push("don't use both kinds of quotation mark");
	}
	return {
		key: `combined:${normalized.join("+")}`,
		message: instructions.join(", and "),
		description: `Combined search validation: ${normalized.join(", ")}`,
	};
}

/** The finite compiler-owned message catalog exposed to people and agents. */
export const SEARCH_RUNTIME_VALIDATION_MESSAGES: readonly SearchRuntimeValidationMessage[] =
	(() => {
		const out = new Map<string, SearchRuntimeValidationMessage>();
		for (const geopoint of [false, true]) {
			for (const number of [
				undefined,
				"whole-number",
				"nonnegative-whole-number",
			] as const) {
				for (const quote of [false, true]) {
					const kinds = new Set<SearchRuntimeValidationKind>();
					if (geopoint) kinds.add("geopoint");
					if (number !== undefined) kinds.add(number);
					if (quote) kinds.add("quote");
					const entry = searchRuntimeValidationMessage(kinds);
					if (entry !== undefined) out.set(entry.key, entry);
				}
			}
		}
		for (const message of DATE_RANGE_MESSAGES) out.set(message.key, message);
		for (const kind of searchRuntimeValidationKinds) {
			const message = searchRuntimeGlobalValidationMessage(kind);
			out.set(message.key, message);
		}
		return [...out.values()];
	})();

export function searchRuntimeValidationMessageByKey(
	key: string,
): SearchRuntimeValidationMessage | undefined {
	return SEARCH_RUNTIME_VALIDATION_MESSAGES.find((entry) => entry.key === key);
}
