// lib/domain/languageRegistry/macrolanguages.catalog.ts
//
// AUTO-GENERATED by scripts/generate-language-registry.ts — DO NOT EDIT BY HAND.
// Regenerate: npx tsx scripts/generate-language-registry.ts
//
// Sources:
//   https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab
//   https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3-macrolanguages.tab
//   cldr-core + cldr-localenames-full 48.2.0 (npm), scriptMetadata.txt at release-48-2

/** Every ISO 639:2023 macrolanguage with its individual living members,
 *  CLDR's predominant member first. */
export const MACROLANGUAGE_CATALOG: readonly {
	readonly code: string;
	readonly name: string;
	readonly members: readonly { readonly code: string; readonly name: string }[];
}[] = [
	{
		code: "aka",
		name: "Akan",
		members: [
			{
				code: "fat",
				name: "Fanti",
			},
			{
				code: "twi",
				name: "Akan",
			},
		],
	},
	{
		code: "ara",
		name: "Arabic",
		members: [
			{
				code: "arb",
				name: "Standard Arabic",
			},
			{
				code: "aao",
				name: "Algerian Saharan Arabic",
			},
			{
				code: "abh",
				name: "Tajiki Arabic",
			},
			{
				code: "abv",
				name: "Baharna Arabic",
			},
			{
				code: "acm",
				name: "Mesopotamian Arabic",
			},
			{
				code: "acq",
				name: "Ta'izzi-Adeni Arabic",
			},
			{
				code: "acw",
				name: "Hijazi Arabic",
			},
			{
				code: "acx",
				name: "Omani Arabic",
			},
			{
				code: "acy",
				name: "Cypriot Arabic",
			},
			{
				code: "adf",
				name: "Dhofari Arabic",
			},
			{
				code: "aeb",
				name: "Tunisian Arabic",
			},
			{
				code: "aec",
				name: "Saidi Arabic",
			},
			{
				code: "afb",
				name: "Gulf Arabic",
			},
			{
				code: "apc",
				name: "Levantine Arabic",
			},
			{
				code: "apd",
				name: "Sudanese Arabic",
			},
			{
				code: "arq",
				name: "Algerian Arabic",
			},
			{
				code: "ars",
				name: "Najdi Arabic",
			},
			{
				code: "ary",
				name: "Moroccan Arabic",
			},
			{
				code: "arz",
				name: "Egyptian Arabic",
			},
			{
				code: "auz",
				name: "Uzbeki Arabic",
			},
			{
				code: "avl",
				name: "Eastern Egyptian Bedawi Arabic",
			},
			{
				code: "ayh",
				name: "Hadrami Arabic",
			},
			{
				code: "ayl",
				name: "Libyan Arabic",
			},
			{
				code: "ayn",
				name: "Sanaani Arabic",
			},
			{
				code: "ayp",
				name: "North Mesopotamian Arabic",
			},
			{
				code: "pga",
				name: "Sudanese Creole Arabic",
			},
			{
				code: "shu",
				name: "Chadian Arabic",
			},
			{
				code: "ssh",
				name: "Shihhi Arabic",
			},
		],
	},
	{
		code: "aym",
		name: "Aymara",
		members: [
			{
				code: "ayr",
				name: "Central Aymara",
			},
			{
				code: "ayc",
				name: "Southern Aymara",
			},
		],
	},
	{
		code: "aze",
		name: "Azerbaijani",
		members: [
			{
				code: "azj",
				name: "North Azerbaijani",
			},
			{
				code: "azb",
				name: "South Azerbaijani",
			},
		],
	},
	{
		code: "bal",
		name: "Baluchi",
		members: [
			{
				code: "bcc",
				name: "Southern Balochi",
			},
			{
				code: "bgn",
				name: "Western Balochi",
			},
			{
				code: "bgp",
				name: "Eastern Balochi",
			},
		],
	},
	{
		code: "bik",
		name: "Bikol",
		members: [
			{
				code: "bcl",
				name: "Central Bikol",
			},
			{
				code: "bln",
				name: "Southern Catanduanes Bikol",
			},
			{
				code: "bto",
				name: "Rinconada Bikol",
			},
			{
				code: "cts",
				name: "Northern Catanduanes Bikol",
			},
			{
				code: "fbl",
				name: "West Albay Bikol",
			},
			{
				code: "lbl",
				name: "Libon Bikol",
			},
			{
				code: "rbl",
				name: "Miraya Bikol",
			},
			{
				code: "ubl",
				name: "Buhi'non Bikol",
			},
		],
	},
	{
		code: "bnc",
		name: "Bontok",
		members: [
			{
				code: "lbk",
				name: "Central Bontok",
			},
			{
				code: "ebk",
				name: "Eastern Bontok",
			},
			{
				code: "obk",
				name: "Southern Bontok",
			},
			{
				code: "rbk",
				name: "Northern Bontok",
			},
			{
				code: "vbk",
				name: "Southwestern Bontok",
			},
		],
	},
	{
		code: "bua",
		name: "Buriat",
		members: [
			{
				code: "bxr",
				name: "Russia Buriat",
			},
			{
				code: "bxm",
				name: "Mongolia Buriat",
			},
			{
				code: "bxu",
				name: "China Buriat",
			},
		],
	},
	{
		code: "chm",
		name: "Mari (Russia)",
		members: [
			{
				code: "mhr",
				name: "Eastern Mari",
			},
			{
				code: "mrj",
				name: "Western Mari",
			},
		],
	},
	{
		code: "cre",
		name: "Cree",
		members: [
			{
				code: "cwd",
				name: "Woods Cree",
			},
			{
				code: "crj",
				name: "Southern East Cree",
			},
			{
				code: "crk",
				name: "Plains Cree",
			},
			{
				code: "crl",
				name: "Northern East Cree",
			},
			{
				code: "crm",
				name: "Moose Cree",
			},
			{
				code: "csw",
				name: "Swampy Cree",
			},
		],
	},
	{
		code: "del",
		name: "Delaware",
		members: [
			{
				code: "umu",
				name: "Munsee",
			},
		],
	},
	{
		code: "den",
		name: "Slavey",
		members: [
			{
				code: "xsl",
				name: "South Slavey",
			},
			{
				code: "scs",
				name: "North Slavey",
			},
		],
	},
	{
		code: "din",
		name: "Dinka",
		members: [
			{
				code: "dik",
				name: "Southwestern Dinka",
			},
			{
				code: "dib",
				name: "South Central Dinka",
			},
			{
				code: "dip",
				name: "Northeastern Dinka",
			},
			{
				code: "diw",
				name: "Northwestern Dinka",
			},
			{
				code: "dks",
				name: "Southeastern Dinka",
			},
		],
	},
	{
		code: "doi",
		name: "Dogri (macrolanguage)",
		members: [
			{
				code: "dgo",
				name: "Dogri (individual language)",
			},
			{
				code: "xnr",
				name: "Kangri",
			},
		],
	},
	{
		code: "est",
		name: "Estonian",
		members: [
			{
				code: "ekk",
				name: "Standard Estonian",
			},
			{
				code: "vro",
				name: "Võro",
			},
		],
	},
	{
		code: "fas",
		name: "Persian",
		members: [
			{
				code: "pes",
				name: "Iranian Persian",
			},
			{
				code: "prs",
				name: "Dari",
			},
		],
	},
	{
		code: "ful",
		name: "Fulah",
		members: [
			{
				code: "fuc",
				name: "Pulaar",
			},
			{
				code: "ffm",
				name: "Maasina Fulfulde",
			},
			{
				code: "fub",
				name: "Adamawa Fulfulde",
			},
			{
				code: "fue",
				name: "Borgu Fulfulde",
			},
			{
				code: "fuf",
				name: "Pular",
			},
			{
				code: "fuh",
				name: "Western Niger Fulfulde",
			},
			{
				code: "fui",
				name: "Bagirmi Fulfulde",
			},
			{
				code: "fuq",
				name: "Central-Eastern Niger Fulfulde",
			},
			{
				code: "fuv",
				name: "Nigerian Fulfulde",
			},
		],
	},
	{
		code: "gba",
		name: "Gbaya (Central African Republic)",
		members: [
			{
				code: "gya",
				name: "Northwest Gbaya",
			},
			{
				code: "bdt",
				name: "Bokoto",
			},
			{
				code: "gbp",
				name: "Gbaya-Bossangoa",
			},
			{
				code: "gbq",
				name: "Gbaya-Bozoum",
			},
			{
				code: "gmm",
				name: "Gbaya-Mbodomo",
			},
			{
				code: "gso",
				name: "Southwest Gbaya",
			},
		],
	},
	{
		code: "gon",
		name: "Gondi",
		members: [
			{
				code: "gno",
				name: "Northern Gondi",
			},
			{
				code: "esg",
				name: "Aheri Gondi",
			},
			{
				code: "wsg",
				name: "Adilabad Gondi",
			},
		],
	},
	{
		code: "grb",
		name: "Grebo",
		members: [
			{
				code: "gbo",
				name: "Northern Grebo",
			},
			{
				code: "gec",
				name: "Gboloo Grebo",
			},
			{
				code: "grj",
				name: "Southern Grebo",
			},
			{
				code: "grv",
				name: "Central Grebo",
			},
			{
				code: "gry",
				name: "Barclayville Grebo",
			},
		],
	},
	{
		code: "grn",
		name: "Guarani",
		members: [
			{
				code: "gug",
				name: "Paraguayan Guaraní",
			},
			{
				code: "gnw",
				name: "Western Bolivian Guaraní",
			},
			{
				code: "gui",
				name: "Eastern Bolivian Guaraní",
			},
			{
				code: "gun",
				name: "Mbyá Guaraní",
			},
			{
				code: "nhd",
				name: "Chiripá",
			},
		],
	},
	{
		code: "hai",
		name: "Haida",
		members: [
			{
				code: "hdn",
				name: "Northern Haida",
			},
			{
				code: "hax",
				name: "Southern Haida",
			},
		],
	},
	{
		code: "hbs",
		name: "Serbo-Croatian",
		members: [
			{
				code: "cnr",
				name: "Montenegrin",
			},
			{
				code: "srp",
				name: "Serbian",
			},
			{
				code: "bos",
				name: "Bosnian",
			},
			{
				code: "hrv",
				name: "Croatian",
			},
		],
	},
	{
		code: "hmn",
		name: "Hmong",
		members: [
			{
				code: "hea",
				name: "Northern Qiandong Miao",
			},
			{
				code: "cqd",
				name: "Chuanqiandian Cluster Miao",
			},
			{
				code: "hma",
				name: "Southern Mashan Hmong",
			},
			{
				code: "hmc",
				name: "Central Huishui Hmong",
			},
			{
				code: "hmd",
				name: "Large Flowery Miao",
			},
			{
				code: "hme",
				name: "Eastern Huishui Hmong",
			},
			{
				code: "hmg",
				name: "Southwestern Guiyang Hmong",
			},
			{
				code: "hmh",
				name: "Southwestern Huishui Hmong",
			},
			{
				code: "hmi",
				name: "Northern Huishui Hmong",
			},
			{
				code: "hmj",
				name: "Ge",
			},
			{
				code: "hml",
				name: "Luopohe Hmong",
			},
			{
				code: "hmm",
				name: "Central Mashan Hmong",
			},
			{
				code: "hmp",
				name: "Northern Mashan Hmong",
			},
			{
				code: "hmq",
				name: "Eastern Qiandong Miao",
			},
			{
				code: "hms",
				name: "Southern Qiandong Miao",
			},
			{
				code: "hmw",
				name: "Western Mashan Hmong",
			},
			{
				code: "hmy",
				name: "Southern Guiyang Hmong",
			},
			{
				code: "hmz",
				name: "Hmong Shua",
			},
			{
				code: "hnj",
				name: "Hmong Njua",
			},
			{
				code: "hrm",
				name: "Horned Miao",
			},
			{
				code: "huj",
				name: "Northern Guiyang Hmong",
			},
			{
				code: "mmr",
				name: "Western Xiangxi Miao",
			},
			{
				code: "muq",
				name: "Eastern Xiangxi Miao",
			},
			{
				code: "mww",
				name: "Hmong Daw",
			},
			{
				code: "sfm",
				name: "Small Flowery Miao",
			},
		],
	},
	{
		code: "iku",
		name: "Inuktitut",
		members: [
			{
				code: "ike",
				name: "Eastern Canadian Inuktitut",
			},
			{
				code: "ikt",
				name: "Western Canadian Inuktitut",
			},
		],
	},
	{
		code: "ipk",
		name: "Inupiaq",
		members: [
			{
				code: "esk",
				name: "Northwest Alaska Inupiatun",
			},
			{
				code: "esi",
				name: "North Alaskan Inupiatun",
			},
		],
	},
	{
		code: "jrb",
		name: "Judeo-Arabic",
		members: [
			{
				code: "aju",
				name: "Judeo-Moroccan Arabic",
			},
			{
				code: "jye",
				name: "Judeo-Yemeni Arabic",
			},
			{
				code: "yhd",
				name: "Judeo-Iraqi Arabic",
			},
			{
				code: "yud",
				name: "Judeo-Tripolitanian Arabic",
			},
		],
	},
	{
		code: "kau",
		name: "Kanuri",
		members: [
			{
				code: "knc",
				name: "Central Kanuri",
			},
			{
				code: "kby",
				name: "Manga Kanuri",
			},
			{
				code: "krt",
				name: "Tumari Kanuri",
			},
		],
	},
	{
		code: "kln",
		name: "Kalenjin",
		members: [
			{
				code: "spy",
				name: "Sabaot",
			},
			{
				code: "enb",
				name: "Markweeta",
			},
			{
				code: "eyo",
				name: "Keiyo",
			},
			{
				code: "niq",
				name: "Nandi",
			},
			{
				code: "oki",
				name: "Okiek",
			},
			{
				code: "pko",
				name: "Pökoot",
			},
			{
				code: "sgc",
				name: "Kipsigis",
			},
			{
				code: "tec",
				name: "Terik",
			},
			{
				code: "tuy",
				name: "Tugen",
			},
		],
	},
	{
		code: "kok",
		name: "Konkani (macrolanguage)",
		members: [
			{
				code: "gom",
				name: "Goan Konkani",
			},
			{
				code: "knn",
				name: "Konkani (individual language)",
			},
		],
	},
	{
		code: "kom",
		name: "Komi",
		members: [
			{
				code: "kpv",
				name: "Komi-Zyrian",
			},
			{
				code: "koi",
				name: "Komi-Permyak",
			},
		],
	},
	{
		code: "kon",
		name: "Kongo",
		members: [
			{
				code: "kng",
				name: "Koongo",
			},
			{
				code: "kwy",
				name: "San Salvador Kongo",
			},
			{
				code: "ldi",
				name: "Laari",
			},
		],
	},
	{
		code: "kpe",
		name: "Kpelle",
		members: [
			{
				code: "xpe",
				name: "Liberia Kpelle",
			},
			{
				code: "gkp",
				name: "Guinea Kpelle",
			},
		],
	},
	{
		code: "kur",
		name: "Kurdish",
		members: [
			{
				code: "kmr",
				name: "Northern Kurdish",
			},
			{
				code: "ckb",
				name: "Central Kurdish",
			},
			{
				code: "sdh",
				name: "Southern Kurdish",
			},
		],
	},
	{
		code: "lah",
		name: "Lahnda",
		members: [
			{
				code: "pnb",
				name: "Western Panjabi",
			},
			{
				code: "hnd",
				name: "Southern Hindko",
			},
			{
				code: "hno",
				name: "Northern Hindko",
			},
			{
				code: "jat",
				name: "Jakati",
			},
			{
				code: "phr",
				name: "Pahari-Potwari",
			},
			{
				code: "skr",
				name: "Saraiki",
			},
			{
				code: "xhe",
				name: "Khetrani",
			},
		],
	},
	{
		code: "lav",
		name: "Latvian",
		members: [
			{
				code: "lvs",
				name: "Standard Latvian",
			},
			{
				code: "ltg",
				name: "Latgalian",
			},
		],
	},
	{
		code: "luy",
		name: "Luyia",
		members: [
			{
				code: "bxk",
				name: "Bukusu",
			},
			{
				code: "ida",
				name: "Idakho-Isukha-Tiriki",
			},
			{
				code: "lkb",
				name: "Kabras",
			},
			{
				code: "lko",
				name: "Khayo",
			},
			{
				code: "lks",
				name: "Kisa",
			},
			{
				code: "lri",
				name: "Marachi",
			},
			{
				code: "lrm",
				name: "Marama",
			},
			{
				code: "lsm",
				name: "Saamia",
			},
			{
				code: "lto",
				name: "Tsotso",
			},
			{
				code: "lts",
				name: "Tachoni",
			},
			{
				code: "lwg",
				name: "Wanga",
			},
			{
				code: "nle",
				name: "East Nyala",
			},
			{
				code: "nyd",
				name: "Nyore",
			},
			{
				code: "rag",
				name: "Logooli",
			},
		],
	},
	{
		code: "man",
		name: "Mandingo",
		members: [
			{
				code: "emk",
				name: "Eastern Maninkakan",
			},
			{
				code: "mku",
				name: "Konyanka Maninka",
			},
			{
				code: "mlq",
				name: "Western Maninkakan",
			},
			{
				code: "mnk",
				name: "Mandinka",
			},
			{
				code: "msc",
				name: "Sankaran Maninka",
			},
			{
				code: "mwk",
				name: "Kita Maninkakan",
			},
		],
	},
	{
		code: "mlg",
		name: "Malagasy",
		members: [
			{
				code: "plt",
				name: "Plateau Malagasy",
			},
			{
				code: "bhr",
				name: "Bara Malagasy",
			},
			{
				code: "bmm",
				name: "Northern Betsimisaraka Malagasy",
			},
			{
				code: "bzc",
				name: "Southern Betsimisaraka Malagasy",
			},
			{
				code: "msh",
				name: "Masikoro Malagasy",
			},
			{
				code: "skg",
				name: "Sakalava Malagasy",
			},
			{
				code: "tdx",
				name: "Tandroy-Mahafaly Malagasy",
			},
			{
				code: "tkg",
				name: "Tesaka Malagasy",
			},
			{
				code: "txy",
				name: "Tanosy Malagasy",
			},
			{
				code: "xmv",
				name: "Antankarana Malagasy",
			},
			{
				code: "xmw",
				name: "Tsimihety Malagasy",
			},
		],
	},
	{
		code: "mon",
		name: "Mongolian",
		members: [
			{
				code: "khk",
				name: "Halh Mongolian",
			},
			{
				code: "mvf",
				name: "Peripheral Mongolian",
			},
		],
	},
	{
		code: "msa",
		name: "Malay (macrolanguage)",
		members: [
			{
				code: "zsm",
				name: "Standard Malay",
			},
			{
				code: "bjn",
				name: "Banjar",
			},
			{
				code: "btj",
				name: "Bacanese Malay",
			},
			{
				code: "bve",
				name: "Berau Malay",
			},
			{
				code: "bvu",
				name: "Bukit Malay",
			},
			{
				code: "coa",
				name: "Cocos Islands Malay",
			},
			{
				code: "dup",
				name: "Duano",
			},
			{
				code: "hji",
				name: "Haji",
			},
			{
				code: "ind",
				name: "Indonesian",
			},
			{
				code: "jak",
				name: "Jakun",
			},
			{
				code: "jax",
				name: "Jambi Malay",
			},
			{
				code: "kvb",
				name: "Kubu",
			},
			{
				code: "kvr",
				name: "Kerinci",
			},
			{
				code: "kxd",
				name: "Brunei",
			},
			{
				code: "lce",
				name: "Loncong",
			},
			{
				code: "lcf",
				name: "Lubu",
			},
			{
				code: "liw",
				name: "Col",
			},
			{
				code: "max",
				name: "North Moluccan Malay",
			},
			{
				code: "meo",
				name: "Kedah Malay",
			},
			{
				code: "mfa",
				name: "Pattani Malay",
			},
			{
				code: "mfb",
				name: "Bangka",
			},
			{
				code: "min",
				name: "Minangkabau",
			},
			{
				code: "mqg",
				name: "Kota Bangun Kutai Malay",
			},
			{
				code: "msi",
				name: "Sabah Malay",
			},
			{
				code: "mui",
				name: "Musi",
			},
			{
				code: "orn",
				name: "Orang Kanaq",
			},
			{
				code: "ors",
				name: "Orang Seletar",
			},
			{
				code: "pel",
				name: "Pekal",
			},
			{
				code: "pse",
				name: "Central Malay",
			},
			{
				code: "tmw",
				name: "Temuan",
			},
			{
				code: "urk",
				name: "Urak Lawoi'",
			},
			{
				code: "vkk",
				name: "Kaur",
			},
			{
				code: "vkt",
				name: "Tenggarong Kutai Malay",
			},
			{
				code: "xmm",
				name: "Manado Malay",
			},
			{
				code: "zlm",
				name: "Malay (individual language)",
			},
			{
				code: "zmi",
				name: "Negeri Sembilan Malay",
			},
		],
	},
	{
		code: "mwr",
		name: "Marwari",
		members: [
			{
				code: "dhd",
				name: "Dhundari",
			},
			{
				code: "mtr",
				name: "Mewari",
			},
			{
				code: "mve",
				name: "Marwari (Pakistan)",
			},
			{
				code: "rwr",
				name: "Marwari (India)",
			},
			{
				code: "swv",
				name: "Shekhawati",
			},
			{
				code: "wry",
				name: "Merwari",
			},
		],
	},
	{
		code: "nep",
		name: "Nepali (macrolanguage)",
		members: [
			{
				code: "npi",
				name: "Nepali (individual language)",
			},
			{
				code: "dty",
				name: "Dotyali",
			},
		],
	},
	{
		code: "nor",
		name: "Norwegian",
		members: [
			{
				code: "nno",
				name: "Norwegian Nynorsk",
			},
			{
				code: "nob",
				name: "Norwegian Bokmål",
			},
		],
	},
	{
		code: "oji",
		name: "Ojibwa",
		members: [
			{
				code: "ojg",
				name: "Eastern Ojibwa",
			},
			{
				code: "ciw",
				name: "Chippewa",
			},
			{
				code: "ojb",
				name: "Northwestern Ojibwa",
			},
			{
				code: "ojc",
				name: "Central Ojibwa",
			},
			{
				code: "ojs",
				name: "Oji-Cree",
			},
			{
				code: "ojw",
				name: "Western Ojibwa",
			},
			{
				code: "otw",
				name: "Ottawa",
			},
		],
	},
	{
		code: "ori",
		name: "Oriya (macrolanguage)",
		members: [
			{
				code: "ory",
				name: "Odia",
			},
			{
				code: "spv",
				name: "Sambalpuri",
			},
		],
	},
	{
		code: "orm",
		name: "Oromo",
		members: [
			{
				code: "gaz",
				name: "West Central Oromo",
			},
			{
				code: "gax",
				name: "Borana-Arsi-Guji Oromo",
			},
			{
				code: "hae",
				name: "Eastern Oromo",
			},
			{
				code: "orc",
				name: "Orma",
			},
		],
	},
	{
		code: "pus",
		name: "Pushto",
		members: [
			{
				code: "pbu",
				name: "Northern Pashto",
			},
			{
				code: "pbt",
				name: "Southern Pashto",
			},
			{
				code: "pst",
				name: "Central Pashto",
			},
		],
	},
	{
		code: "que",
		name: "Quechua",
		members: [
			{
				code: "quz",
				name: "Cusco Quechua",
			},
			{
				code: "qub",
				name: "Huallaga Huánuco Quechua",
			},
			{
				code: "qud",
				name: "Calderón Highland Quichua",
			},
			{
				code: "quf",
				name: "Lambayeque Quechua",
			},
			{
				code: "qug",
				name: "Chimborazo Highland Quichua",
			},
			{
				code: "quh",
				name: "South Bolivian Quechua",
			},
			{
				code: "quk",
				name: "Chachapoyas Quechua",
			},
			{
				code: "qul",
				name: "North Bolivian Quechua",
			},
			{
				code: "qup",
				name: "Southern Pastaza Quechua",
			},
			{
				code: "qur",
				name: "Yanahuanca Pasco Quechua",
			},
			{
				code: "qus",
				name: "Santiago del Estero Quichua",
			},
			{
				code: "quw",
				name: "Tena Lowland Quichua",
			},
			{
				code: "qux",
				name: "Yauyos Quechua",
			},
			{
				code: "quy",
				name: "Ayacucho Quechua",
			},
			{
				code: "qva",
				name: "Ambo-Pasco Quechua",
			},
			{
				code: "qvc",
				name: "Cajamarca Quechua",
			},
			{
				code: "qve",
				name: "Eastern Apurímac Quechua",
			},
			{
				code: "qvh",
				name: "Huamalíes-Dos de Mayo Huánuco Quechua",
			},
			{
				code: "qvi",
				name: "Imbabura Highland Quichua",
			},
			{
				code: "qvj",
				name: "Loja Highland Quichua",
			},
			{
				code: "qvl",
				name: "Cajatambo North Lima Quechua",
			},
			{
				code: "qvm",
				name: "Margos-Yarowilca-Lauricocha Quechua",
			},
			{
				code: "qvn",
				name: "North Junín Quechua",
			},
			{
				code: "qvo",
				name: "Napo Lowland Quechua",
			},
			{
				code: "qvp",
				name: "Pacaraos Quechua",
			},
			{
				code: "qvs",
				name: "San Martín Quechua",
			},
			{
				code: "qvw",
				name: "Huaylla Wanca Quechua",
			},
			{
				code: "qvz",
				name: "Northern Pastaza Quichua",
			},
			{
				code: "qwa",
				name: "Corongo Ancash Quechua",
			},
			{
				code: "qwh",
				name: "Huaylas Ancash Quechua",
			},
			{
				code: "qws",
				name: "Sihuas Ancash Quechua",
			},
			{
				code: "qxa",
				name: "Chiquián Ancash Quechua",
			},
			{
				code: "qxc",
				name: "Chincha Quechua",
			},
			{
				code: "qxh",
				name: "Panao Huánuco Quechua",
			},
			{
				code: "qxl",
				name: "Salasaca Highland Quichua",
			},
			{
				code: "qxn",
				name: "Northern Conchucos Ancash Quechua",
			},
			{
				code: "qxo",
				name: "Southern Conchucos Ancash Quechua",
			},
			{
				code: "qxp",
				name: "Puno Quechua",
			},
			{
				code: "qxr",
				name: "Cañar Highland Quichua",
			},
			{
				code: "qxt",
				name: "Santa Ana de Tusi Pasco Quechua",
			},
			{
				code: "qxu",
				name: "Arequipa-La Unión Quechua",
			},
			{
				code: "qxw",
				name: "Jauja Wanca Quechua",
			},
		],
	},
	{
		code: "raj",
		name: "Rajasthani",
		members: [
			{
				code: "mup",
				name: "Malvi",
			},
			{
				code: "bgq",
				name: "Bagri",
			},
			{
				code: "gda",
				name: "Gade Lohar",
			},
			{
				code: "gju",
				name: "Gujari",
			},
			{
				code: "hoj",
				name: "Hadothi",
			},
			{
				code: "wbr",
				name: "Wagdi",
			},
		],
	},
	{
		code: "rom",
		name: "Romany",
		members: [
			{
				code: "rmy",
				name: "Vlax Romani",
			},
			{
				code: "rmc",
				name: "Carpathian Romani",
			},
			{
				code: "rmf",
				name: "Kalo Finnish Romani",
			},
			{
				code: "rml",
				name: "Baltic Romani",
			},
			{
				code: "rmn",
				name: "Balkan Romani",
			},
			{
				code: "rmo",
				name: "Sinte Romani",
			},
			{
				code: "rmw",
				name: "Welsh Romani",
			},
		],
	},
	{
		code: "san",
		name: "Sanskrit",
		members: [],
	},
	{
		code: "sqi",
		name: "Albanian",
		members: [
			{
				code: "als",
				name: "Tosk Albanian",
			},
			{
				code: "aae",
				name: "Arbëreshë Albanian",
			},
			{
				code: "aat",
				name: "Arvanitika Albanian",
			},
			{
				code: "aln",
				name: "Gheg Albanian",
			},
		],
	},
	{
		code: "srd",
		name: "Sardinian",
		members: [
			{
				code: "src",
				name: "Logudorese Sardinian",
			},
			{
				code: "sdc",
				name: "Sassarese Sardinian",
			},
			{
				code: "sdn",
				name: "Gallurese Sardinian",
			},
			{
				code: "sro",
				name: "Campidanese Sardinian",
			},
		],
	},
	{
		code: "swa",
		name: "Swahili (macrolanguage)",
		members: [
			{
				code: "swc",
				name: "Congo Swahili",
			},
			{
				code: "swh",
				name: "Swahili (individual language)",
			},
		],
	},
	{
		code: "syr",
		name: "Syriac",
		members: [
			{
				code: "cld",
				name: "Chaldean Neo-Aramaic",
			},
			{
				code: "aii",
				name: "Assyrian Neo-Aramaic",
			},
		],
	},
	{
		code: "tmh",
		name: "Tamashek",
		members: [
			{
				code: "ttq",
				name: "Tawallammat Tamajaq",
			},
			{
				code: "taq",
				name: "Tamasheq",
			},
			{
				code: "thv",
				name: "Tahaggart Tamahaq",
			},
			{
				code: "thz",
				name: "Tayart Tamajeq",
			},
		],
	},
	{
		code: "uzb",
		name: "Uzbek",
		members: [
			{
				code: "uzn",
				name: "Northern Uzbek",
			},
			{
				code: "uzs",
				name: "Southern Uzbek",
			},
		],
	},
	{
		code: "yid",
		name: "Yiddish",
		members: [
			{
				code: "ydd",
				name: "Eastern Yiddish",
			},
		],
	},
	{
		code: "zap",
		name: "Zapotec",
		members: [
			{
				code: "zai",
				name: "Isthmus Zapotec",
			},
			{
				code: "zaa",
				name: "Sierra de Juárez Zapotec",
			},
			{
				code: "zab",
				name: "Western Tlacolula Valley Zapotec",
			},
			{
				code: "zac",
				name: "Ocotlán Zapotec",
			},
			{
				code: "zad",
				name: "Cajonos Zapotec",
			},
			{
				code: "zae",
				name: "Yareni Zapotec",
			},
			{
				code: "zaf",
				name: "Ayoquesco Zapotec",
			},
			{
				code: "zam",
				name: "Miahuatlán Zapotec",
			},
			{
				code: "zao",
				name: "Ozolotepec Zapotec",
			},
			{
				code: "zaq",
				name: "Aloápam Zapotec",
			},
			{
				code: "zar",
				name: "Rincón Zapotec",
			},
			{
				code: "zas",
				name: "Santo Domingo Albarradas Zapotec",
			},
			{
				code: "zat",
				name: "Tabaa Zapotec",
			},
			{
				code: "zav",
				name: "Yatzachi Zapotec",
			},
			{
				code: "zaw",
				name: "Mitla Zapotec",
			},
			{
				code: "zax",
				name: "Xadani Zapotec",
			},
			{
				code: "zca",
				name: "Coatecas Altas Zapotec",
			},
			{
				code: "zcd",
				name: "Las Delicias Zapotec",
			},
			{
				code: "zoo",
				name: "Asunción Mixtepec Zapotec",
			},
			{
				code: "zpa",
				name: "Lachiguiri Zapotec",
			},
			{
				code: "zpb",
				name: "Yautepec Zapotec",
			},
			{
				code: "zpc",
				name: "Choapan Zapotec",
			},
			{
				code: "zpd",
				name: "Southeastern Ixtlán Zapotec",
			},
			{
				code: "zpe",
				name: "Petapa Zapotec",
			},
			{
				code: "zpf",
				name: "San Pedro Quiatoni Zapotec",
			},
			{
				code: "zpg",
				name: "Guevea De Humboldt Zapotec",
			},
			{
				code: "zph",
				name: "Totomachapan Zapotec",
			},
			{
				code: "zpi",
				name: "Santa María Quiegolani Zapotec",
			},
			{
				code: "zpj",
				name: "Quiavicuzas Zapotec",
			},
			{
				code: "zpk",
				name: "Tlacolulita Zapotec",
			},
			{
				code: "zpl",
				name: "Lachixío Zapotec",
			},
			{
				code: "zpm",
				name: "Mixtepec Zapotec",
			},
			{
				code: "zpn",
				name: "Santa Inés Yatzechi Zapotec",
			},
			{
				code: "zpo",
				name: "Amatlán Zapotec",
			},
			{
				code: "zpp",
				name: "El Alto Zapotec",
			},
			{
				code: "zpq",
				name: "Zoogocho Zapotec",
			},
			{
				code: "zpr",
				name: "Santiago Xanica Zapotec",
			},
			{
				code: "zps",
				name: "Coatlán Zapotec",
			},
			{
				code: "zpt",
				name: "San Vicente Coatlán Zapotec",
			},
			{
				code: "zpu",
				name: "Yalálag Zapotec",
			},
			{
				code: "zpv",
				name: "Chichicapan Zapotec",
			},
			{
				code: "zpw",
				name: "Zaniza Zapotec",
			},
			{
				code: "zpx",
				name: "San Baltazar Loxicha Zapotec",
			},
			{
				code: "zpy",
				name: "Mazaltepec Zapotec",
			},
			{
				code: "zpz",
				name: "Texmelucan Zapotec",
			},
			{
				code: "zsr",
				name: "Southern Rincon Zapotec",
			},
			{
				code: "zte",
				name: "Elotepec Zapotec",
			},
			{
				code: "ztg",
				name: "Xanaguía Zapotec",
			},
			{
				code: "ztl",
				name: "Lapaguía-Guivini Zapotec",
			},
			{
				code: "ztm",
				name: "San Agustín Mixtepec Zapotec",
			},
			{
				code: "ztn",
				name: "Santa Catarina Albarradas Zapotec",
			},
			{
				code: "ztp",
				name: "Loxicha Zapotec",
			},
			{
				code: "ztq",
				name: "Quioquitani-Quierí Zapotec",
			},
			{
				code: "zts",
				name: "Tilquiapan Zapotec",
			},
			{
				code: "ztt",
				name: "Tejalapan Zapotec",
			},
			{
				code: "ztu",
				name: "Güilá Zapotec",
			},
			{
				code: "ztx",
				name: "Zaachila Zapotec",
			},
			{
				code: "zty",
				name: "Yatee Zapotec",
			},
		],
	},
	{
		code: "zha",
		name: "Zhuang",
		members: [
			{
				code: "zyb",
				name: "Yongbei Zhuang",
			},
			{
				code: "zch",
				name: "Central Hongshuihe Zhuang",
			},
			{
				code: "zeh",
				name: "Eastern Hongshuihe Zhuang",
			},
			{
				code: "zgb",
				name: "Guibei Zhuang",
			},
			{
				code: "zgm",
				name: "Minz Zhuang",
			},
			{
				code: "zgn",
				name: "Guibian Zhuang",
			},
			{
				code: "zhd",
				name: "Dai Zhuang",
			},
			{
				code: "zhn",
				name: "Nong Zhuang",
			},
			{
				code: "zlj",
				name: "Liujiang Zhuang",
			},
			{
				code: "zln",
				name: "Lianshan Zhuang",
			},
			{
				code: "zlq",
				name: "Liuqian Zhuang",
			},
			{
				code: "zqe",
				name: "Qiubei Zhuang",
			},
			{
				code: "zyg",
				name: "Yang Zhuang",
			},
			{
				code: "zyj",
				name: "Youjiang Zhuang",
			},
			{
				code: "zyn",
				name: "Yongnan Zhuang",
			},
			{
				code: "zzj",
				name: "Zuojiang Zhuang",
			},
		],
	},
	{
		code: "zho",
		name: "Chinese",
		members: [
			{
				code: "cmn",
				name: "Mandarin Chinese",
			},
			{
				code: "cdo",
				name: "Min Dong Chinese",
			},
			{
				code: "cjy",
				name: "Jinyu Chinese",
			},
			{
				code: "cnp",
				name: "Northern Ping Chinese",
			},
			{
				code: "cpx",
				name: "Pu-Xian Chinese",
			},
			{
				code: "csp",
				name: "Southern Ping Chinese",
			},
			{
				code: "czh",
				name: "Huizhou Chinese",
			},
			{
				code: "czo",
				name: "Min Zhong Chinese",
			},
			{
				code: "gan",
				name: "Gan Chinese",
			},
			{
				code: "hak",
				name: "Hakka Chinese",
			},
			{
				code: "hnm",
				name: "Hainanese",
			},
			{
				code: "hsn",
				name: "Xiang Chinese",
			},
			{
				code: "luh",
				name: "Leizhou Chinese",
			},
			{
				code: "mnp",
				name: "Min Bei Chinese",
			},
			{
				code: "nan",
				name: "Min Nan Chinese",
			},
			{
				code: "sjc",
				name: "Shaojiang Chinese",
			},
			{
				code: "wuu",
				name: "Wu Chinese",
			},
			{
				code: "yue",
				name: "Cantonese",
			},
		],
	},
	{
		code: "zza",
		name: "Zaza",
		members: [
			{
				code: "diq",
				name: "Dimli (individual language)",
			},
			{
				code: "kiu",
				name: "Kirmanjki",
			},
		],
	},
];

/** Individual member code → its macrolanguage code. */
export const MACROLANGUAGE_OF_MEMBER: Readonly<Record<string, string>> = {
	fat: "aka",
	twi: "aka",
	aao: "ara",
	abh: "ara",
	abv: "ara",
	acm: "ara",
	acq: "ara",
	acw: "ara",
	acx: "ara",
	acy: "ara",
	adf: "ara",
	aeb: "ara",
	aec: "ara",
	afb: "ara",
	apc: "ara",
	apd: "ara",
	arb: "ara",
	arq: "ara",
	ars: "ara",
	ary: "ara",
	arz: "ara",
	auz: "ara",
	avl: "ara",
	ayh: "ara",
	ayl: "ara",
	ayn: "ara",
	ayp: "ara",
	pga: "ara",
	shu: "ara",
	ssh: "ara",
	ayc: "aym",
	ayr: "aym",
	azb: "aze",
	azj: "aze",
	bcc: "bal",
	bgn: "bal",
	bgp: "bal",
	bcl: "bik",
	bln: "bik",
	bto: "bik",
	cts: "bik",
	fbl: "bik",
	lbl: "bik",
	rbl: "bik",
	ubl: "bik",
	ebk: "bnc",
	lbk: "bnc",
	obk: "bnc",
	rbk: "bnc",
	vbk: "bnc",
	bxm: "bua",
	bxr: "bua",
	bxu: "bua",
	mhr: "chm",
	mrj: "chm",
	crj: "cre",
	crk: "cre",
	crl: "cre",
	crm: "cre",
	csw: "cre",
	cwd: "cre",
	umu: "del",
	scs: "den",
	xsl: "den",
	dib: "din",
	dik: "din",
	dip: "din",
	diw: "din",
	dks: "din",
	dgo: "doi",
	xnr: "doi",
	ekk: "est",
	vro: "est",
	pes: "fas",
	prs: "fas",
	ffm: "ful",
	fub: "ful",
	fuc: "ful",
	fue: "ful",
	fuf: "ful",
	fuh: "ful",
	fui: "ful",
	fuq: "ful",
	fuv: "ful",
	bdt: "gba",
	gbp: "gba",
	gbq: "gba",
	gmm: "gba",
	gso: "gba",
	gya: "gba",
	esg: "gon",
	gno: "gon",
	wsg: "gon",
	gbo: "grb",
	gec: "grb",
	grj: "grb",
	grv: "grb",
	gry: "grb",
	gnw: "grn",
	gug: "grn",
	gui: "grn",
	gun: "grn",
	nhd: "grn",
	hax: "hai",
	hdn: "hai",
	bos: "hbs",
	cnr: "hbs",
	hrv: "hbs",
	srp: "hbs",
	cqd: "hmn",
	hea: "hmn",
	hma: "hmn",
	hmc: "hmn",
	hmd: "hmn",
	hme: "hmn",
	hmg: "hmn",
	hmh: "hmn",
	hmi: "hmn",
	hmj: "hmn",
	hml: "hmn",
	hmm: "hmn",
	hmp: "hmn",
	hmq: "hmn",
	hms: "hmn",
	hmw: "hmn",
	hmy: "hmn",
	hmz: "hmn",
	hnj: "hmn",
	hrm: "hmn",
	huj: "hmn",
	mmr: "hmn",
	muq: "hmn",
	mww: "hmn",
	sfm: "hmn",
	ike: "iku",
	ikt: "iku",
	esi: "ipk",
	esk: "ipk",
	aju: "jrb",
	jye: "jrb",
	yhd: "jrb",
	yud: "jrb",
	kby: "kau",
	knc: "kau",
	krt: "kau",
	enb: "kln",
	eyo: "kln",
	niq: "kln",
	oki: "kln",
	pko: "kln",
	sgc: "kln",
	spy: "kln",
	tec: "kln",
	tuy: "kln",
	gom: "kok",
	knn: "kok",
	koi: "kom",
	kpv: "kom",
	kng: "kon",
	kwy: "kon",
	ldi: "kon",
	gkp: "kpe",
	xpe: "kpe",
	ckb: "kur",
	kmr: "kur",
	sdh: "kur",
	hnd: "lah",
	hno: "lah",
	jat: "lah",
	phr: "lah",
	pnb: "lah",
	skr: "lah",
	xhe: "lah",
	ltg: "lav",
	lvs: "lav",
	bxk: "luy",
	ida: "luy",
	lkb: "luy",
	lko: "luy",
	lks: "luy",
	lri: "luy",
	lrm: "luy",
	lsm: "luy",
	lto: "luy",
	lts: "luy",
	lwg: "luy",
	nle: "luy",
	nyd: "luy",
	rag: "luy",
	emk: "man",
	mku: "man",
	mlq: "man",
	mnk: "man",
	msc: "man",
	mwk: "man",
	bhr: "mlg",
	bmm: "mlg",
	bzc: "mlg",
	msh: "mlg",
	plt: "mlg",
	skg: "mlg",
	tdx: "mlg",
	tkg: "mlg",
	txy: "mlg",
	xmv: "mlg",
	xmw: "mlg",
	khk: "mon",
	mvf: "mon",
	bjn: "msa",
	btj: "msa",
	bve: "msa",
	bvu: "msa",
	coa: "msa",
	dup: "msa",
	hji: "msa",
	ind: "msa",
	jak: "msa",
	jax: "msa",
	kvb: "msa",
	kvr: "msa",
	kxd: "msa",
	lce: "msa",
	lcf: "msa",
	liw: "msa",
	max: "msa",
	meo: "msa",
	mfa: "msa",
	mfb: "msa",
	min: "msa",
	mqg: "msa",
	msi: "msa",
	mui: "msa",
	orn: "msa",
	ors: "msa",
	pel: "msa",
	pse: "msa",
	tmw: "msa",
	urk: "msa",
	vkk: "msa",
	vkt: "msa",
	xmm: "msa",
	zlm: "msa",
	zmi: "msa",
	zsm: "msa",
	dhd: "mwr",
	mtr: "mwr",
	mve: "mwr",
	rwr: "mwr",
	swv: "mwr",
	wry: "mwr",
	dty: "nep",
	npi: "nep",
	nno: "nor",
	nob: "nor",
	ciw: "oji",
	ojb: "oji",
	ojc: "oji",
	ojg: "oji",
	ojs: "oji",
	ojw: "oji",
	otw: "oji",
	ory: "ori",
	spv: "ori",
	gax: "orm",
	gaz: "orm",
	hae: "orm",
	orc: "orm",
	pbt: "pus",
	pbu: "pus",
	pst: "pus",
	qub: "que",
	qud: "que",
	quf: "que",
	qug: "que",
	quh: "que",
	quk: "que",
	qul: "que",
	qup: "que",
	qur: "que",
	qus: "que",
	quw: "que",
	qux: "que",
	quy: "que",
	quz: "que",
	qva: "que",
	qvc: "que",
	qve: "que",
	qvh: "que",
	qvi: "que",
	qvj: "que",
	qvl: "que",
	qvm: "que",
	qvn: "que",
	qvo: "que",
	qvp: "que",
	qvs: "que",
	qvw: "que",
	qvz: "que",
	qwa: "que",
	qwh: "que",
	qws: "que",
	qxa: "que",
	qxc: "que",
	qxh: "que",
	qxl: "que",
	qxn: "que",
	qxo: "que",
	qxp: "que",
	qxr: "que",
	qxt: "que",
	qxu: "que",
	qxw: "que",
	bgq: "raj",
	gda: "raj",
	gju: "raj",
	hoj: "raj",
	mup: "raj",
	wbr: "raj",
	rmc: "rom",
	rmf: "rom",
	rml: "rom",
	rmn: "rom",
	rmo: "rom",
	rmw: "rom",
	rmy: "rom",
	aae: "sqi",
	aat: "sqi",
	aln: "sqi",
	als: "sqi",
	sdc: "srd",
	sdn: "srd",
	src: "srd",
	sro: "srd",
	swc: "swa",
	swh: "swa",
	aii: "syr",
	cld: "syr",
	taq: "tmh",
	thv: "tmh",
	thz: "tmh",
	ttq: "tmh",
	uzn: "uzb",
	uzs: "uzb",
	ydd: "yid",
	zaa: "zap",
	zab: "zap",
	zac: "zap",
	zad: "zap",
	zae: "zap",
	zaf: "zap",
	zai: "zap",
	zam: "zap",
	zao: "zap",
	zaq: "zap",
	zar: "zap",
	zas: "zap",
	zat: "zap",
	zav: "zap",
	zaw: "zap",
	zax: "zap",
	zca: "zap",
	zcd: "zap",
	zoo: "zap",
	zpa: "zap",
	zpb: "zap",
	zpc: "zap",
	zpd: "zap",
	zpe: "zap",
	zpf: "zap",
	zpg: "zap",
	zph: "zap",
	zpi: "zap",
	zpj: "zap",
	zpk: "zap",
	zpl: "zap",
	zpm: "zap",
	zpn: "zap",
	zpo: "zap",
	zpp: "zap",
	zpq: "zap",
	zpr: "zap",
	zps: "zap",
	zpt: "zap",
	zpu: "zap",
	zpv: "zap",
	zpw: "zap",
	zpx: "zap",
	zpy: "zap",
	zpz: "zap",
	zsr: "zap",
	zte: "zap",
	ztg: "zap",
	ztl: "zap",
	ztm: "zap",
	ztn: "zap",
	ztp: "zap",
	ztq: "zap",
	zts: "zap",
	ztt: "zap",
	ztu: "zap",
	ztx: "zap",
	zty: "zap",
	zch: "zha",
	zeh: "zha",
	zgb: "zha",
	zgm: "zha",
	zgn: "zha",
	zhd: "zha",
	zhn: "zha",
	zlj: "zha",
	zln: "zha",
	zlq: "zha",
	zqe: "zha",
	zyb: "zha",
	zyg: "zha",
	zyj: "zha",
	zyn: "zha",
	zzj: "zha",
	cdo: "zho",
	cjy: "zho",
	cmn: "zho",
	cnp: "zho",
	cpx: "zho",
	csp: "zho",
	czh: "zho",
	czo: "zho",
	gan: "zho",
	hak: "zho",
	hnm: "zho",
	hsn: "zho",
	luh: "zho",
	mnp: "zho",
	nan: "zho",
	sjc: "zho",
	wuu: "zho",
	yue: "zho",
	diq: "zza",
	kiu: "zza",
};
