// lib/domain/languageRegistry/regions.catalog.ts
//
// AUTO-GENERATED by scripts/generate-language-registry.ts — DO NOT EDIT BY HAND.
// Regenerate: npx tsx scripts/generate-language-registry.ts
//
// Sources:
//   https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab
//   https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3-macrolanguages.tab
//   cldr-core + cldr-localenames-full 48.2.0 (npm), scriptMetadata.txt at release-48-2

/** Regional-convention choices per language (per script where the
 *  language branches): territories where the language holds official or
 *  de-facto-official status, listed only when at least two exist. The
 *  likely territory leads; region always stays skippable. */
export const LANGUAGE_REGION_CATALOG: readonly {
	readonly language: string;
	readonly script?: string;
	readonly regions: readonly {
		readonly region: string;
		readonly label: string;
	}[];
}[] = [
	{
		language: "als",
		regions: [
			{
				region: "AL",
				label: "Albania",
			},
			{
				region: "XK",
				label: "Kosovo",
			},
		],
	},
	{
		language: "arb",
		regions: [
			{
				region: "EG",
				label: "Egypt",
			},
			{
				region: "DZ",
				label: "Algeria",
			},
			{
				region: "BH",
				label: "Bahrain",
			},
			{
				region: "TD",
				label: "Chad",
			},
			{
				region: "KM",
				label: "Comoros",
			},
			{
				region: "DJ",
				label: "Djibouti",
			},
			{
				region: "ER",
				label: "Eritrea",
			},
			{
				region: "IQ",
				label: "Iraq",
			},
			{
				region: "IL",
				label: "Israel",
			},
			{
				region: "JO",
				label: "Jordan",
			},
			{
				region: "KW",
				label: "Kuwait",
			},
			{
				region: "LB",
				label: "Lebanon",
			},
			{
				region: "LY",
				label: "Libya",
			},
			{
				region: "MR",
				label: "Mauritania",
			},
			{
				region: "MA",
				label: "Morocco",
			},
			{
				region: "OM",
				label: "Oman",
			},
			{
				region: "PS",
				label: "Palestinian Territories",
			},
			{
				region: "QA",
				label: "Qatar",
			},
			{
				region: "SA",
				label: "Saudi Arabia",
			},
			{
				region: "SO",
				label: "Somalia",
			},
			{
				region: "SD",
				label: "Sudan",
			},
			{
				region: "SY",
				label: "Syria",
			},
			{
				region: "TN",
				label: "Tunisia",
			},
			{
				region: "AE",
				label: "United Arab Emirates",
			},
			{
				region: "EH",
				label: "Western Sahara",
			},
			{
				region: "YE",
				label: "Yemen",
			},
		],
	},
	{
		language: "cmn",
		script: "Hans",
		regions: [
			{
				region: "CN",
				label: "China",
			},
			{
				region: "SG",
				label: "Singapore",
			},
		],
	},
	{
		language: "cmn",
		script: "Hant",
		regions: [
			{
				region: "TW",
				label: "Taiwan",
			},
			{
				region: "HK",
				label: "Hong Kong SAR China",
			},
			{
				region: "MO",
				label: "Macao SAR China",
			},
		],
	},
	{
		language: "deu",
		regions: [
			{
				region: "DE",
				label: "Germany",
			},
			{
				region: "AT",
				label: "Austria",
			},
			{
				region: "BE",
				label: "Belgium",
			},
			{
				region: "LI",
				label: "Liechtenstein",
			},
			{
				region: "LU",
				label: "Luxembourg",
			},
			{
				region: "CH",
				label: "Switzerland",
			},
		],
	},
	{
		language: "ell",
		regions: [
			{
				region: "GR",
				label: "Greece",
			},
			{
				region: "CY",
				label: "Cyprus",
			},
		],
	},
	{
		language: "eng",
		regions: [
			{
				region: "US",
				label: "United States",
			},
			{
				region: "AS",
				label: "American Samoa",
			},
			{
				region: "AI",
				label: "Anguilla",
			},
			{
				region: "AG",
				label: "Antigua & Barbuda",
			},
			{
				region: "AU",
				label: "Australia",
			},
			{
				region: "BS",
				label: "Bahamas",
			},
			{
				region: "BB",
				label: "Barbados",
			},
			{
				region: "BZ",
				label: "Belize",
			},
			{
				region: "BM",
				label: "Bermuda",
			},
			{
				region: "BW",
				label: "Botswana",
			},
			{
				region: "IO",
				label: "British Indian Ocean Territory",
			},
			{
				region: "VG",
				label: "British Virgin Islands",
			},
			{
				region: "BI",
				label: "Burundi",
			},
			{
				region: "CM",
				label: "Cameroon",
			},
			{
				region: "CA",
				label: "Canada",
			},
			{
				region: "KY",
				label: "Cayman Islands",
			},
			{
				region: "CX",
				label: "Christmas Island",
			},
			{
				region: "CC",
				label: "Cocos (Keeling) Islands",
			},
			{
				region: "CK",
				label: "Cook Islands",
			},
			{
				region: "DG",
				label: "Diego Garcia",
			},
			{
				region: "DM",
				label: "Dominica",
			},
			{
				region: "ER",
				label: "Eritrea",
			},
			{
				region: "SZ",
				label: "Eswatini",
			},
			{
				region: "FK",
				label: "Falkland Islands",
			},
			{
				region: "FJ",
				label: "Fiji",
			},
			{
				region: "GM",
				label: "Gambia",
			},
			{
				region: "GH",
				label: "Ghana",
			},
			{
				region: "GI",
				label: "Gibraltar",
			},
			{
				region: "GD",
				label: "Grenada",
			},
			{
				region: "GU",
				label: "Guam",
			},
			{
				region: "GG",
				label: "Guernsey",
			},
			{
				region: "GY",
				label: "Guyana",
			},
			{
				region: "HK",
				label: "Hong Kong SAR China",
			},
			{
				region: "IN",
				label: "India",
			},
			{
				region: "IE",
				label: "Ireland",
			},
			{
				region: "IM",
				label: "Isle of Man",
			},
			{
				region: "JM",
				label: "Jamaica",
			},
			{
				region: "JE",
				label: "Jersey",
			},
			{
				region: "KE",
				label: "Kenya",
			},
			{
				region: "KI",
				label: "Kiribati",
			},
			{
				region: "LS",
				label: "Lesotho",
			},
			{
				region: "LR",
				label: "Liberia",
			},
			{
				region: "MG",
				label: "Madagascar",
			},
			{
				region: "MW",
				label: "Malawi",
			},
			{
				region: "MT",
				label: "Malta",
			},
			{
				region: "MH",
				label: "Marshall Islands",
			},
			{
				region: "MU",
				label: "Mauritius",
			},
			{
				region: "FM",
				label: "Micronesia",
			},
			{
				region: "MS",
				label: "Montserrat",
			},
			{
				region: "NA",
				label: "Namibia",
			},
			{
				region: "NR",
				label: "Nauru",
			},
			{
				region: "NZ",
				label: "New Zealand",
			},
			{
				region: "NG",
				label: "Nigeria",
			},
			{
				region: "NU",
				label: "Niue",
			},
			{
				region: "NF",
				label: "Norfolk Island",
			},
			{
				region: "MP",
				label: "Northern Mariana Islands",
			},
			{
				region: "PK",
				label: "Pakistan",
			},
			{
				region: "PW",
				label: "Palau",
			},
			{
				region: "PG",
				label: "Papua New Guinea",
			},
			{
				region: "PH",
				label: "Philippines",
			},
			{
				region: "PN",
				label: "Pitcairn Islands",
			},
			{
				region: "PR",
				label: "Puerto Rico",
			},
			{
				region: "RW",
				label: "Rwanda",
			},
			{
				region: "WS",
				label: "Samoa",
			},
			{
				region: "CQ",
				label: "Sark",
			},
			{
				region: "SC",
				label: "Seychelles",
			},
			{
				region: "SL",
				label: "Sierra Leone",
			},
			{
				region: "SG",
				label: "Singapore",
			},
			{
				region: "SX",
				label: "Sint Maarten",
			},
			{
				region: "SB",
				label: "Solomon Islands",
			},
			{
				region: "ZA",
				label: "South Africa",
			},
			{
				region: "GS",
				label: "South Georgia & South Sandwich Islands",
			},
			{
				region: "SS",
				label: "South Sudan",
			},
			{
				region: "SH",
				label: "St. Helena",
			},
			{
				region: "KN",
				label: "St. Kitts & Nevis",
			},
			{
				region: "LC",
				label: "St. Lucia",
			},
			{
				region: "VC",
				label: "St. Vincent & Grenadines",
			},
			{
				region: "SD",
				label: "Sudan",
			},
			{
				region: "TZ",
				label: "Tanzania",
			},
			{
				region: "TK",
				label: "Tokelau",
			},
			{
				region: "TO",
				label: "Tonga",
			},
			{
				region: "TT",
				label: "Trinidad & Tobago",
			},
			{
				region: "TC",
				label: "Turks & Caicos Islands",
			},
			{
				region: "TV",
				label: "Tuvalu",
			},
			{
				region: "UM",
				label: "U.S. Outlying Islands",
			},
			{
				region: "VI",
				label: "U.S. Virgin Islands",
			},
			{
				region: "UG",
				label: "Uganda",
			},
			{
				region: "GB",
				label: "United Kingdom",
			},
			{
				region: "VU",
				label: "Vanuatu",
			},
			{
				region: "ZM",
				label: "Zambia",
			},
			{
				region: "ZW",
				label: "Zimbabwe",
			},
		],
	},
	{
		language: "fra",
		regions: [
			{
				region: "FR",
				label: "France",
			},
			{
				region: "DZ",
				label: "Algeria",
			},
			{
				region: "BE",
				label: "Belgium",
			},
			{
				region: "BJ",
				label: "Benin",
			},
			{
				region: "BF",
				label: "Burkina Faso",
			},
			{
				region: "BI",
				label: "Burundi",
			},
			{
				region: "CM",
				label: "Cameroon",
			},
			{
				region: "CA",
				label: "Canada",
			},
			{
				region: "CF",
				label: "Central African Republic",
			},
			{
				region: "TD",
				label: "Chad",
			},
			{
				region: "KM",
				label: "Comoros",
			},
			{
				region: "CG",
				label: "Congo - Brazzaville",
			},
			{
				region: "CD",
				label: "Congo - Kinshasa",
			},
			{
				region: "CI",
				label: "Côte d’Ivoire",
			},
			{
				region: "DJ",
				label: "Djibouti",
			},
			{
				region: "GQ",
				label: "Equatorial Guinea",
			},
			{
				region: "GF",
				label: "French Guiana",
			},
			{
				region: "PF",
				label: "French Polynesia",
			},
			{
				region: "GA",
				label: "Gabon",
			},
			{
				region: "GP",
				label: "Guadeloupe",
			},
			{
				region: "GN",
				label: "Guinea",
			},
			{
				region: "HT",
				label: "Haiti",
			},
			{
				region: "LU",
				label: "Luxembourg",
			},
			{
				region: "MG",
				label: "Madagascar",
			},
			{
				region: "ML",
				label: "Mali",
			},
			{
				region: "MQ",
				label: "Martinique",
			},
			{
				region: "MU",
				label: "Mauritius",
			},
			{
				region: "YT",
				label: "Mayotte",
			},
			{
				region: "MC",
				label: "Monaco",
			},
			{
				region: "MA",
				label: "Morocco",
			},
			{
				region: "NC",
				label: "New Caledonia",
			},
			{
				region: "NE",
				label: "Niger",
			},
			{
				region: "RE",
				label: "Réunion",
			},
			{
				region: "RW",
				label: "Rwanda",
			},
			{
				region: "SN",
				label: "Senegal",
			},
			{
				region: "SC",
				label: "Seychelles",
			},
			{
				region: "BL",
				label: "St. Barthélemy",
			},
			{
				region: "MF",
				label: "St. Martin",
			},
			{
				region: "PM",
				label: "St. Pierre & Miquelon",
			},
			{
				region: "CH",
				label: "Switzerland",
			},
			{
				region: "TG",
				label: "Togo",
			},
			{
				region: "TN",
				label: "Tunisia",
			},
			{
				region: "VU",
				label: "Vanuatu",
			},
			{
				region: "WF",
				label: "Wallis & Futuna",
			},
		],
	},
	{
		language: "gsw",
		regions: [
			{
				region: "CH",
				label: "Switzerland",
			},
			{
				region: "LI",
				label: "Liechtenstein",
			},
		],
	},
	{
		language: "hrv",
		regions: [
			{
				region: "HR",
				label: "Croatia",
			},
			{
				region: "BA",
				label: "Bosnia & Herzegovina",
			},
		],
	},
	{
		language: "ita",
		regions: [
			{
				region: "IT",
				label: "Italy",
			},
			{
				region: "SM",
				label: "San Marino",
			},
			{
				region: "CH",
				label: "Switzerland",
			},
			{
				region: "VA",
				label: "Vatican City",
			},
		],
	},
	{
		language: "kor",
		regions: [
			{
				region: "KR",
				label: "South Korea",
			},
			{
				region: "KP",
				label: "North Korea",
			},
		],
	},
	{
		language: "nld",
		regions: [
			{
				region: "NL",
				label: "Netherlands",
			},
			{
				region: "AW",
				label: "Aruba",
			},
			{
				region: "BE",
				label: "Belgium",
			},
			{
				region: "BQ",
				label: "Caribbean Netherlands",
			},
			{
				region: "CW",
				label: "Curaçao",
			},
			{
				region: "SX",
				label: "Sint Maarten",
			},
			{
				region: "SR",
				label: "Suriname",
			},
		],
	},
	{
		language: "nob",
		regions: [
			{
				region: "NO",
				label: "Norway",
			},
			{
				region: "SJ",
				label: "Svalbard & Jan Mayen",
			},
		],
	},
	{
		language: "pap",
		regions: [
			{
				region: "CW",
				label: "Curaçao",
			},
			{
				region: "AW",
				label: "Aruba",
			},
		],
	},
	{
		language: "por",
		regions: [
			{
				region: "BR",
				label: "Brazil",
			},
			{
				region: "AO",
				label: "Angola",
			},
			{
				region: "CV",
				label: "Cape Verde",
			},
			{
				region: "GQ",
				label: "Equatorial Guinea",
			},
			{
				region: "GW",
				label: "Guinea-Bissau",
			},
			{
				region: "MO",
				label: "Macao SAR China",
			},
			{
				region: "MZ",
				label: "Mozambique",
			},
			{
				region: "PT",
				label: "Portugal",
			},
			{
				region: "ST",
				label: "São Tomé & Príncipe",
			},
			{
				region: "TL",
				label: "Timor-Leste",
			},
		],
	},
	{
		language: "quz",
		regions: [
			{
				region: "PE",
				label: "Peru",
			},
			{
				region: "BO",
				label: "Bolivia",
			},
			{
				region: "EC",
				label: "Ecuador",
			},
		],
	},
	{
		language: "ron",
		regions: [
			{
				region: "RO",
				label: "Romania",
			},
			{
				region: "MD",
				label: "Moldova",
			},
		],
	},
	{
		language: "rus",
		regions: [
			{
				region: "RU",
				label: "Russia",
			},
			{
				region: "BY",
				label: "Belarus",
			},
			{
				region: "KZ",
				label: "Kazakhstan",
			},
			{
				region: "KG",
				label: "Kyrgyzstan",
			},
			{
				region: "UA",
				label: "Ukraine",
			},
		],
	},
	{
		language: "smo",
		regions: [
			{
				region: "WS",
				label: "Samoa",
			},
			{
				region: "AS",
				label: "American Samoa",
			},
		],
	},
	{
		language: "spa",
		regions: [
			{
				region: "ES",
				label: "Spain",
			},
			{
				region: "AR",
				label: "Argentina",
			},
			{
				region: "BO",
				label: "Bolivia",
			},
			{
				region: "IC",
				label: "Canary Islands",
			},
			{
				region: "EA",
				label: "Ceuta & Melilla",
			},
			{
				region: "CL",
				label: "Chile",
			},
			{
				region: "CO",
				label: "Colombia",
			},
			{
				region: "CR",
				label: "Costa Rica",
			},
			{
				region: "CU",
				label: "Cuba",
			},
			{
				region: "DO",
				label: "Dominican Republic",
			},
			{
				region: "EC",
				label: "Ecuador",
			},
			{
				region: "SV",
				label: "El Salvador",
			},
			{
				region: "GQ",
				label: "Equatorial Guinea",
			},
			{
				region: "GT",
				label: "Guatemala",
			},
			{
				region: "HN",
				label: "Honduras",
			},
			{
				region: "MX",
				label: "Mexico",
			},
			{
				region: "NI",
				label: "Nicaragua",
			},
			{
				region: "PA",
				label: "Panama",
			},
			{
				region: "PY",
				label: "Paraguay",
			},
			{
				region: "PE",
				label: "Peru",
			},
			{
				region: "PR",
				label: "Puerto Rico",
			},
			{
				region: "UY",
				label: "Uruguay",
			},
			{
				region: "VE",
				label: "Venezuela",
			},
		],
	},
	{
		language: "srp",
		script: "Cyrl",
		regions: [
			{
				region: "RS",
				label: "Serbia",
			},
			{
				region: "BA",
				label: "Bosnia & Herzegovina",
			},
			{
				region: "XK",
				label: "Kosovo",
			},
		],
	},
	{
		language: "srp",
		script: "Latn",
		regions: [
			{
				region: "RS",
				label: "Serbia",
			},
			{
				region: "BA",
				label: "Bosnia & Herzegovina",
			},
			{
				region: "XK",
				label: "Kosovo",
			},
		],
	},
	{
		language: "swe",
		regions: [
			{
				region: "SE",
				label: "Sweden",
			},
			{
				region: "AX",
				label: "Åland Islands",
			},
			{
				region: "FI",
				label: "Finland",
			},
		],
	},
	{
		language: "swh",
		regions: [
			{
				region: "TZ",
				label: "Tanzania",
			},
			{
				region: "KE",
				label: "Kenya",
			},
			{
				region: "UG",
				label: "Uganda",
			},
		],
	},
	{
		language: "tam",
		regions: [
			{
				region: "SG",
				label: "Singapore",
			},
			{
				region: "LK",
				label: "Sri Lanka",
			},
		],
	},
	{
		language: "tur",
		regions: [
			{
				region: "TR",
				label: "Türkiye",
			},
			{
				region: "CY",
				label: "Cyprus",
			},
		],
	},
	{
		language: "zsm",
		script: "Latn",
		regions: [
			{
				region: "MY",
				label: "Malaysia",
			},
			{
				region: "BN",
				label: "Brunei",
			},
			{
				region: "SG",
				label: "Singapore",
			},
		],
	},
];
