// lib/domain/languageRegistry/scripts.catalog.ts
//
// AUTO-GENERATED by scripts/generate-language-registry.ts — DO NOT EDIT BY HAND.
// Regenerate: npx tsx scripts/generate-language-registry.ts
//
// Sources:
//   https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab
//   https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3-macrolanguages.tab
//   cldr-core + cldr-localenames-full 48.2.0 (npm), scriptMetadata.txt at release-48-2

/** Languages customarily written in more than one script, with their
 *  choices — the likely (default) script first. An absent language does
 *  not branch and its identities never carry a script. */
export const MULTI_SCRIPT_LANGUAGE_CATALOG: readonly {
	readonly language: string;
	readonly scripts: readonly {
		readonly script: string;
		readonly label: string;
		readonly qualifier: string;
		readonly direction: "ltr" | "rtl";
	}[];
}[] = [
	{
		language: "azj",
		scripts: [
			{
				script: "Latn",
				label: "North Azerbaijani (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
			{
				script: "Cyrl",
				label: "North Azerbaijani (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
		],
	},
	{
		language: "bam",
		scripts: [
			{
				script: "Latn",
				label: "Bambara (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
			{
				script: "Nkoo",
				label: "Bambara (N’Ko script)",
				qualifier: "N’Ko",
				direction: "rtl",
			},
		],
	},
	{
		language: "bos",
		scripts: [
			{
				script: "Latn",
				label: "Bosnian (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
			{
				script: "Cyrl",
				label: "Bosnian (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
		],
	},
	{
		language: "ccp",
		scripts: [
			{
				script: "Cakm",
				label: "Chakma (Chakma script)",
				qualifier: "Chakma",
				direction: "ltr",
			},
			{
				script: "Beng",
				label: "Chakma (Bangla script)",
				qualifier: "Bangla",
				direction: "ltr",
			},
		],
	},
	{
		language: "cmn",
		scripts: [
			{
				script: "Hans",
				label: "Simplified Chinese",
				qualifier: "Simplified",
				direction: "ltr",
			},
			{
				script: "Hant",
				label: "Traditional Chinese",
				qualifier: "Traditional",
				direction: "ltr",
			},
		],
	},
	{
		language: "cnr",
		scripts: [
			{
				script: "Cyrl",
				label: "Montenegrin (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
			{
				script: "Latn",
				label: "Montenegrin (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "cwd",
		scripts: [
			{
				script: "Cans",
				label: "Woods Cree (Unified Canadian Aboriginal Syllabics script)",
				qualifier: "Unified Canadian Aboriginal Syllabics",
				direction: "ltr",
			},
			{
				script: "Latn",
				label: "Woods Cree (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "emk",
		scripts: [
			{
				script: "Latn",
				label: "Eastern Maninkakan (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
			{
				script: "Nkoo",
				label: "Eastern Maninkakan (N’Ko script)",
				qualifier: "N’Ko",
				direction: "rtl",
			},
		],
	},
	{
		language: "gno",
		scripts: [
			{
				script: "Deva",
				label: "Northern Gondi (Devanagari script)",
				qualifier: "Devanagari",
				direction: "ltr",
			},
			{
				script: "Telu",
				label: "Northern Gondi (Telugu script)",
				qualifier: "Telugu",
				direction: "ltr",
			},
		],
	},
	{
		language: "gom",
		scripts: [
			{
				script: "Deva",
				label: "Goan Konkani (Devanagari script)",
				qualifier: "Devanagari",
				direction: "ltr",
			},
			{
				script: "Latn",
				label: "Goan Konkani (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "hak",
		scripts: [
			{
				script: "Hans",
				label: "Hakka Chinese (Simplified script)",
				qualifier: "Simplified",
				direction: "ltr",
			},
			{
				script: "Hant",
				label: "Hakka Chinese (Traditional script)",
				qualifier: "Traditional",
				direction: "ltr",
			},
		],
	},
	{
		language: "hau",
		scripts: [
			{
				script: "Latn",
				label: "Hausa (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
			{
				script: "Arab",
				label: "Hausa (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
		],
	},
	{
		language: "hif",
		scripts: [
			{
				script: "Deva",
				label: "Fiji Hindi (Devanagari script)",
				qualifier: "Devanagari",
				direction: "ltr",
			},
			{
				script: "Latn",
				label: "Fiji Hindi (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "ike",
		scripts: [
			{
				script: "Cans",
				label:
					"Eastern Canadian Inuktitut (Unified Canadian Aboriginal Syllabics script)",
				qualifier: "Unified Canadian Aboriginal Syllabics",
				direction: "ltr",
			},
			{
				script: "Latn",
				label: "Eastern Canadian Inuktitut (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "kaa",
		scripts: [
			{
				script: "Cyrl",
				label: "Kara-Kalpak (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
			{
				script: "Latn",
				label: "Kara-Kalpak (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "kas",
		scripts: [
			{
				script: "Arab",
				label: "Kashmiri (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
			{
				script: "Deva",
				label: "Kashmiri (Devanagari script)",
				qualifier: "Devanagari",
				direction: "ltr",
			},
		],
	},
	{
		language: "kaz",
		scripts: [
			{
				script: "Cyrl",
				label: "Kazakh (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
			{
				script: "Arab",
				label: "Kazakh (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
		],
	},
	{
		language: "kir",
		scripts: [
			{
				script: "Cyrl",
				label: "Kyrgyz (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
			{
				script: "Arab",
				label: "Kyrgyz (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
			{
				script: "Latn",
				label: "Kyrgyz (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "lif",
		scripts: [
			{
				script: "Deva",
				label: "Limbu (Devanagari script)",
				qualifier: "Devanagari",
				direction: "ltr",
			},
			{
				script: "Limb",
				label: "Limbu (Limbu script)",
				qualifier: "Limbu",
				direction: "ltr",
			},
		],
	},
	{
		language: "nan",
		scripts: [
			{
				script: "Hans",
				label: "Min Nan Chinese (Simplified script)",
				qualifier: "Simplified",
				direction: "ltr",
			},
			{
				script: "Hant",
				label: "Min Nan Chinese (Traditional script)",
				qualifier: "Traditional",
				direction: "ltr",
			},
		],
	},
	{
		language: "rif",
		scripts: [
			{
				script: "Latn",
				label: "Riffian (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
			{
				script: "Tfng",
				label: "Riffian (Tifinagh script)",
				qualifier: "Tifinagh",
				direction: "ltr",
			},
		],
	},
	{
		language: "shi",
		scripts: [
			{
				script: "Tfng",
				label: "Tachelhit (Tifinagh script)",
				qualifier: "Tifinagh",
				direction: "ltr",
			},
			{
				script: "Arab",
				label: "Tachelhit (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
			{
				script: "Latn",
				label: "Tachelhit (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "snd",
		scripts: [
			{
				script: "Arab",
				label: "Sindhi (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
			{
				script: "Deva",
				label: "Sindhi (Devanagari script)",
				qualifier: "Devanagari",
				direction: "ltr",
			},
		],
	},
	{
		language: "srp",
		scripts: [
			{
				script: "Cyrl",
				label: "Serbian (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
			{
				script: "Latn",
				label: "Serbian (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "tgk",
		scripts: [
			{
				script: "Cyrl",
				label: "Tajik (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
			{
				script: "Arab",
				label: "Tajik (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
			{
				script: "Latn",
				label: "Tajik (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "tuk",
		scripts: [
			{
				script: "Latn",
				label: "Turkmen (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
			{
				script: "Arab",
				label: "Turkmen (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
			{
				script: "Cyrl",
				label: "Turkmen (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
		],
	},
	{
		language: "tzm",
		scripts: [
			{
				script: "Latn",
				label: "Central Atlas Tamazight (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
			{
				script: "Tfng",
				label: "Central Atlas Tamazight (Tifinagh script)",
				qualifier: "Tifinagh",
				direction: "ltr",
			},
		],
	},
	{
		language: "uig",
		scripts: [
			{
				script: "Arab",
				label: "Uyghur (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
			{
				script: "Cyrl",
				label: "Uyghur (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
		],
	},
	{
		language: "unr",
		scripts: [
			{
				script: "Beng",
				label: "Mundari (Bangla script)",
				qualifier: "Bangla",
				direction: "ltr",
			},
			{
				script: "Deva",
				label: "Mundari (Devanagari script)",
				qualifier: "Devanagari",
				direction: "ltr",
			},
		],
	},
	{
		language: "unx",
		scripts: [
			{
				script: "Beng",
				label: "Munda (Bangla script)",
				qualifier: "Bangla",
				direction: "ltr",
			},
			{
				script: "Deva",
				label: "Munda (Devanagari script)",
				qualifier: "Devanagari",
				direction: "ltr",
			},
		],
	},
	{
		language: "uzn",
		scripts: [
			{
				script: "Latn",
				label: "Northern Uzbek (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
			{
				script: "Arab",
				label: "Northern Uzbek (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
			{
				script: "Cyrl",
				label: "Northern Uzbek (Cyrillic script)",
				qualifier: "Cyrillic",
				direction: "ltr",
			},
		],
	},
	{
		language: "vai",
		scripts: [
			{
				script: "Vaii",
				label: "Vai (Vai script)",
				qualifier: "Vai",
				direction: "ltr",
			},
			{
				script: "Latn",
				label: "Vai (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
		],
	},
	{
		language: "zsm",
		scripts: [
			{
				script: "Latn",
				label: "Standard Malay (Latin script)",
				qualifier: "Latin",
				direction: "ltr",
			},
			{
				script: "Arab",
				label: "Standard Malay (Arabic script)",
				qualifier: "Arabic",
				direction: "rtl",
			},
		],
	},
];
