-- lib/case-store/schema.sql
--
-- Source of truth for the case-store SQL schema. Atlas reads this
-- as desired state, diffs against `lib/case-store/migrations/`,
-- and autogenerates the next migration. Spec citations:
-- `docs/superpowers/specs/2026-04-30-case-list-search-design.md`
-- lines 254-284 (four base tables + indexes), 309-340
-- (`cases_quarantine`).
--
-- Lockstep with `lib/case-store/sql/database.ts` (Kysely types) —
-- any schema change updates both files in the same commit.
--
-- ## No extensions declared here
--
-- Columns are plain `text`/`uuid`/`jsonb`/`timestamptz`; the only
-- function reference is PG 18's built-in `uuidv7()`. The compiler
-- stack depends on `pg_trgm` / `fuzzystrmatch` / `postgis` at
-- query time, but `CREATE EXTENSION` requires `cloudsqlsuperuser`
-- which the runtime SA atlas runs as does not have. Production
-- installs them at provisioning time (runbook §Phase 5);
-- testcontainers does the same via container superuser. If a
-- future schema.sql adds a `geometry` column, the
-- `composite_schema` data source at
-- `https://atlasgo.io/faq/manage-extension-only` is the
-- canonical community-edition path.

-- ===================================================================
-- `cases` — spec lines 254-265
-- ===================================================================
--
-- One row per case across every app and tenant. Tenant isolation
-- is the column pair `(app_id, owner_id)`; the application
-- funnels every read/write through a `CaseStore` instance bound
-- to the request's owner id.
--
-- `DEFAULT uuidv7()` uses PG 18's built-in v7 generator
-- (`https://www.postgresql.org/docs/18/functions-uuid.html`) —
-- millisecond timestamp prefix means case_ids cluster tightly on
-- B-tree pages, so INSERTs touch fewer cold pages than uuidv4
-- and `(opened_on, case_id)` pagination is naturally
-- close-to-sorted.
CREATE TABLE "cases" (
  -- UUID v7 generated by Postgres when omitted; explicit values
  -- accepted verbatim for cross-system traceability with
  -- CCHQ-style case ids.
  "case_id" uuid PRIMARY KEY DEFAULT uuidv7(),
  -- TEXT (not UUID) — apps are root-level Firestore docs whose
  -- IDs are application-controlled strings.
  "app_id" text NOT NULL,
  "case_type" text NOT NULL,
  -- Nullable — HQ-imported cases pre-assignment carry null;
  -- sample-data fixtures may key only by app.
  "owner_id" text,
  -- Distinct from `closed_on` so domain status vocabularies round-
  -- trip without lossy derivation from a timestamp.
  "status" text,
  "opened_on" timestamptz,
  "modified_on" timestamptz,
  "closed_on" timestamptz,
  -- Top-level column (not a JSONB key) because `case_name` is
  -- platform-required on every case. The `length > 0` CHECK is the
  -- residual structural guarantee on direct writes; the JSON
  -- Schema for `properties` excludes `case_name`, so AJV at the
  -- API trust boundary is the primary defense.
  "case_name" text NOT NULL CHECK (length("case_name") > 0),
  -- Denormalized first parent for the common single-parent case;
  -- full ancestor walks go through `case_indices`.
  "parent_case_id" uuid,
  -- Validated against `case_type_schemas[app_id, case_type]` via
  -- AJV at every API-route write. The API route is the trust
  -- boundary; the database is internal and carries no validation
  -- trigger.
  "properties" jsonb NOT NULL
);

-- ===================================================================
-- `case_type_schemas` — spec lines 267-272
-- ===================================================================
--
-- Per-(app_id, case_type) JSON Schema generated by
-- `lib/domain/predicate/jsonSchema.ts` from the blueprint's
-- `CaseType.properties[]`. The case-store's AJV validator runs
-- against this row at every API-route write to `cases`.
CREATE TABLE "case_type_schemas" (
  "app_id" text NOT NULL,
  "case_type" text NOT NULL,
  -- Open `Record<string, JsonValue>` — pinning to a specific
  -- Schema-Draft TypeScript type would couple the table to a
  -- particular validator library.
  "schema" jsonb NOT NULL,
  CONSTRAINT "case_type_schemas_pkey" PRIMARY KEY ("app_id", "case_type")
);

-- ===================================================================
-- `case_indices` — spec lines 274-283
-- ===================================================================
--
-- Direct edges only (Option B from spec § "case_indices
-- materialization policy"). Multi-hop traversals compose as a
-- chain of `(case_indices, cases)` joins per AST step — the
-- architectural answer to CCHQ's `MAX_RELATED_CASES = 500_000`
-- per-hop scan.
CREATE TABLE "case_indices" (
  "case_id" uuid NOT NULL,
  "ancestor_id" uuid NOT NULL,
  -- `parent`, `host`, or any custom identifier the blueprint
  -- defines.
  "identifier" text NOT NULL,
  -- 'child' (standard parent-child) or 'extension' (host-
  -- extension where closing the host closes the extension). The
  -- explicit column lets the Postgres compiler answer direction-
  -- specific queries the wire grammars can't express.
  "relationship" text NOT NULL,
  -- `depth=1` is direct. Higher values are reserved for transitive
  -- edges; `compileRelationPath` pins every lookup to `depth = 1`
  -- so the SQL stays materialization-agnostic.
  "depth" integer NOT NULL,
  CONSTRAINT "case_indices_pkey" PRIMARY KEY ("case_id", "ancestor_id", "identifier")
);

-- The two static `case_indices` indexes from spec lines 282-283.
-- Names follow Postgres's default `<table>_<col1>_<col2>_idx`
-- shape so they're recognizable in `pg_indexes`.
--
-- - `(ancestor_id, identifier)` covers the `subcase-exists`
--   ancestor-side lookup. The PK leads with `case_id`, so without
--   this index the lookup degrades to a sequential scan.
-- - `(case_id, identifier)` covers the descendant-side relation-
--   walk leaf join. Column order matters: leading on `case_id`
--   lets the planner narrow on the parent before checking the
--   relation.
--
-- Per-property expression indexes are NOT in this static schema —
-- property names are blueprint-specific and search modes are
-- search-input-config-specific. `applySchemaChange` emits the
-- matching CREATE / DROP set in a Phase B that runs OUTSIDE the
-- schema-sync transaction; see `lib/case-store/CLAUDE.md` §
-- "`applySchemaChange` runs in two phases" for the
-- `SnapshotAny`-vs-`CONCURRENTLY` rationale.
CREATE INDEX "case_indices_ancestor_id_identifier_idx"
  ON "case_indices" ("ancestor_id", "identifier");

CREATE INDEX "case_indices_case_id_identifier_idx"
  ON "case_indices" ("case_id", "identifier");

-- ===================================================================
-- `cases_quarantine` — spec § "Schema migration policy" lines 309-340
-- ===================================================================
--
-- Failed-migration sink. `applySchemaChange` writes here when a
-- blueprint mutation produces a value the new schema rejects;
-- the original row stays preserved verbatim for author-UI review.
-- Same columns as `cases` plus `quarantine_reason` and
-- `quarantined_at`.
--
-- Composite PK `(case_id, quarantined_at)` admits the same case
-- being quarantined more than once across separate migrations.
-- Single-column `case_id` PK would conflict on the second
-- quarantine.
--
-- No indexes beyond the PK — quarantine is author-UI review, not
-- the case-list hot path. Add targeted indexes if profiling shows
-- review is slow.
CREATE TABLE "cases_quarantine" (
  -- NOT defaulted — quarantine writes carry the original case_id
  -- so the record is traceable back.
  "case_id" uuid NOT NULL,
  "app_id" text NOT NULL,
  "case_type" text NOT NULL,
  "owner_id" text,
  "status" text,
  "opened_on" timestamptz,
  "modified_on" timestamptz,
  "closed_on" timestamptz,
  -- Nullable here (unlike `cases`) — a row in quarantine has by
  -- definition failed validation, so the live-side `length > 0`
  -- invariant doesn't apply at the audit layer.
  "case_name" text,
  "parent_case_id" uuid,
  -- Captured verbatim at quarantine time (NOT normalized to the
  -- new schema) so the author UI can display the conflicting
  -- value.
  "properties" jsonb NOT NULL,
  -- E.g. "cast text→int failed for property 'age': value 'abc' is
  -- not numeric".
  "quarantine_reason" text NOT NULL,
  -- Defaulted server-side; application code omits on INSERT.
  "quarantined_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "cases_quarantine_pkey" PRIMARY KEY ("case_id", "quarantined_at")
);
