/**
 * Regenerates the built-in module/form icon library shipped with Nova.
 *
 * The 1024×1024 PNG masters + their `enum.json` catalog live in the SEPARATE
 * `nova-claude-design-icons` repo (the source of truth — gradient tiles with
 * white Tabler glyphs). This script crunches each master down to the size
 * CommCare actually renders (≤ ~540px on the largest surface — Android's grid
 * menu at 120-136dp, web/formplayer's grid icon at 130px CSS), writes the
 * shipped 512×512 copies into `public/nova-icons/`, and regenerates the
 * machine-owned catalog `lib/domain/builtinIcons.catalog.ts` (each icon's
 * content hash + byte size, used at emit time for the wire path + export
 * budget). Only the crunched 512s + the catalog land in this repo; the masters
 * stay in the source repo, so a contributor never needs to run this.
 *
 * Usage:
 *   NOVA_ICONS_SRC=/path/to/nova-claude-design-icons npx tsx scripts/build-builtin-icons.ts
 *   npx tsx scripts/build-builtin-icons.ts /path/to/nova-claude-design-icons
 *
 * Deterministic: same masters + same sharp options → identical bytes → identical
 * hashes on every run (verify with two runs + `git status`).
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

/** The size we ship. Covers every CommCare render surface up to xxhdpi and is
 *  within rounding of the rare xxxhdpi (4×) grid tile; the gradient+glyph
 *  upscales gracefully past that. */
const SHIP_SIZE = 512;

interface EnumIcon {
	key: string;
	kind: "module" | "form" | "fallback";
	label?: string;
	file: string;
	tabler: string;
}

interface EnumManifest {
	name: string;
	version: string;
	icons: EnumIcon[];
}

interface CatalogEntry {
	slug: string;
	kind: "module" | "form" | "fallback";
	label: string;
	tabler: string;
	contentHash: string;
	sizeBytes: number;
}

function resolveSourceRepo(): string {
	const fromArg = process.argv[2];
	const candidate = process.env.NOVA_ICONS_SRC ?? fromArg;
	if (!candidate) {
		throw new Error(
			"Source repo not given. Set NOVA_ICONS_SRC or pass the path:\n" +
				"  npx tsx scripts/build-builtin-icons.ts /path/to/nova-claude-design-icons",
		);
	}
	const resolved = path.resolve(candidate);
	if (!existsSync(path.join(resolved, "enum.json"))) {
		throw new Error(
			`No enum.json found under ${resolved} — is this the nova-claude-design-icons repo?`,
		);
	}
	return resolved;
}

/** Crunch one master to a shipped 512² PNG buffer. Palette + dither keeps the
 *  gradient smooth while collapsing the file from ~700KB to tens of KB. */
async function crunch(masterBytes: Buffer): Promise<Buffer> {
	return sharp(masterBytes)
		.resize(SHIP_SIZE, SHIP_SIZE, {
			fit: "contain",
			background: { r: 0, g: 0, b: 0, alpha: 0 },
		})
		.png({ compressionLevel: 9, palette: true, dither: 1.0, effort: 10 })
		.toBuffer();
}

function tsLiteral(value: string): string {
	return JSON.stringify(value);
}

function renderCatalog(
	entries: CatalogEntry[],
	manifest: EnumManifest,
): string {
	const moduleSlugs = entries
		.filter((e) => e.kind === "module")
		.map((e) => e.slug);
	const formSlugs = entries.filter((e) => e.kind === "form").map((e) => e.slug);
	const allSlugs = entries.map((e) => e.slug);
	// Module + form tool enums each include the `default` fallback so the agent
	// always has a neutral choice. ALL_ICON_SLUGS is the full set in catalog order.
	const moduleEnum = [...moduleSlugs, "default"];
	const formEnum = [...formSlugs, "default"];

	const entryLines = entries
		.map(
			(e) =>
				`\t{\n` +
				`\t\tslug: ${tsLiteral(e.slug)},\n` +
				`\t\tkind: ${tsLiteral(e.kind)},\n` +
				`\t\tlabel: ${tsLiteral(e.label)},\n` +
				`\t\ttabler: ${tsLiteral(e.tabler)},\n` +
				`\t\tcontentHash: ${tsLiteral(e.contentHash)},\n` +
				`\t\tsizeBytes: ${e.sizeBytes},\n` +
				`\t},`,
		)
		.join("\n");

	const tuple = (slugs: string[]) => slugs.map(tsLiteral).join(", ");

	return `// lib/domain/builtinIcons.catalog.ts
//
// AUTO-GENERATED by scripts/build-builtin-icons.ts — DO NOT EDIT BY HAND.
// Regenerate: NOVA_ICONS_SRC=<path-to-nova-claude-design-icons> npx tsx scripts/build-builtin-icons.ts
//
// Source: ${manifest.name} v${manifest.version} (Tabler Icons, MIT, rasterized).
// Each PNG ships at public/nova-icons/<slug>.png, ${SHIP_SIZE}×${SHIP_SIZE} RGBA.
// The hand-written helpers + types that wrap this data live in ./builtinIcons.ts.

/** One shipped built-in icon. \`contentHash\` is the SHA-256 of the crunched PNG
 *  bytes (the wire path + dedup key); \`sizeBytes\` feeds the export budget. */
export const BUILTIN_ICON_CATALOG = [
${entryLines}
] as const;

/** Slugs offered on module create/update tools — the 33 topic icons + \`default\`. */
export const MODULE_ICON_SLUGS = [${tuple(moduleEnum)}] as const;

/** Slugs offered on form create/update tools — the 13 action icons + \`default\`. */
export const FORM_ICON_SLUGS = [${tuple(formEnum)}] as const;

/** Every built-in icon slug, in catalog order. */
export const ALL_ICON_SLUGS = [${tuple(allSlugs)}] as const;
`;
}

async function main(): Promise<void> {
	const sourceRepo = resolveSourceRepo();
	const repoRoot = process.cwd();
	const outImagesDir = path.join(repoRoot, "public", "nova-icons");
	const outCatalog = path.join(
		repoRoot,
		"lib",
		"domain",
		"builtinIcons.catalog.ts",
	);

	const manifest = JSON.parse(
		await readFile(path.join(sourceRepo, "enum.json"), "utf8"),
	) as EnumManifest;

	await mkdir(outImagesDir, { recursive: true });

	const entries: CatalogEntry[] = [];
	let totalBytes = 0;

	for (const icon of manifest.icons) {
		const masterBytes = await readFile(path.join(sourceRepo, icon.file));
		const shipped = await crunch(masterBytes);
		const contentHash = createHash("sha256").update(shipped).digest("hex");

		await writeFile(path.join(outImagesDir, `${icon.key}.png`), shipped);

		entries.push({
			slug: icon.key,
			kind: icon.kind,
			label: icon.label ?? "Default",
			tabler: icon.tabler,
			contentHash,
			sizeBytes: shipped.length,
		});
		totalBytes += shipped.length;
	}

	await writeFile(outCatalog, renderCatalog(entries, manifest), "utf8");

	// Format the generated catalog with the project's Biome so regeneration is
	// idempotent with the linter (the hand-templated tuple wrapping isn't Biome's
	// preferred shape; one pass settles it, so a fresh run leaves the tree clean).
	execFileSync(
		path.join(repoRoot, "node_modules", ".bin", "biome"),
		["check", "--write", outCatalog],
		{ stdio: "inherit" },
	);

	const moduleCount = entries.filter((e) => e.kind === "module").length;
	const formCount = entries.filter((e) => e.kind === "form").length;
	console.log(
		`Built ${entries.length} icons (${moduleCount} module, ${formCount} form, ` +
			`${entries.length - moduleCount - formCount} fallback) → ${outImagesDir}`,
	);
	console.log(`Total shipped bytes: ${(totalBytes / 1024).toFixed(0)} KB`);
	console.log(`Catalog written → ${outCatalog}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
