/**
 * Tests that SA tool / structured-output schemas compile within the
 * Anthropic compiler limits. Two compiler paths share the same
 * underlying engine but accept different schema features:
 *
 *   - **Structured-output mode** (`Output.object`) — used for the
 *     `addFields` schema and any future schema that drives a
 *     non-tool generation. Rejects `oneOf`-shaped discriminated
 *     unions and `$ref` recursion at the compiler boundary; the
 *     `addFields` schema therefore uses a flat-with-discriminator
 *     shape generated by `toolSchemaGenerator.ts`.
 *
 *   - **Tool-input mode** (`tools[name].inputSchema`) — used by
 *     every SA tool in `lib/agent/tools/`. Accepts both `oneOf`
 *     discriminated unions and `$ref` recursion natively, so the
 *     case-list-config tools can pass the typed Predicate /
 *     ValueExpression AST schemas directly via Zod without
 *     restructuring.
 *
 * The 8-optional-field-per-array-item ceiling is shared across
 * both modes — both compilers time out above 8 optional fields on
 * the per-item schema.
 *
 * Usage: `npx tsx scripts/test-schema.ts [opus] [schema-name]`
 *   - Pass `opus` to test against Opus 4.7 (default Haiku 4.5).
 *   - Pass a schema name to test only that schema; omit to test every
 *     registered schema. Known names: `addFields`,
 *     `addCaseListColumn`, `updateCaseListColumn`,
 *     `removeCaseListColumn`, `reorderCaseListColumns`,
 *     `setCaseListFilter`, `addSearchInput`, `updateSearchInput`,
 *     `removeSearchInput`, `reorderSearchInputs`,
 *     `setCaseSearchClaim`, `setCaseSearchDisplay`.
 */
import "dotenv/config";
import { createAnthropic } from "@ai-sdk/anthropic";
import { generateText, Output, stepCountIs, tool } from "ai";
import { z } from "zod";
import { addFieldsSchema } from "../lib/agent/toolSchemas";
import { addCaseListColumnTool } from "../lib/agent/tools/case-list-config/addCaseListColumn";
import { addSearchInputTool } from "../lib/agent/tools/case-list-config/addSearchInput";
import { removeCaseListColumnTool } from "../lib/agent/tools/case-list-config/removeCaseListColumn";
import { removeSearchInputTool } from "../lib/agent/tools/case-list-config/removeSearchInput";
import { reorderCaseListColumnsTool } from "../lib/agent/tools/case-list-config/reorderCaseListColumns";
import { reorderSearchInputsTool } from "../lib/agent/tools/case-list-config/reorderSearchInputs";
import { setCaseListFilterTool } from "../lib/agent/tools/case-list-config/setCaseListFilter";
import { updateCaseListColumnTool } from "../lib/agent/tools/case-list-config/updateCaseListColumn";
import { updateSearchInputTool } from "../lib/agent/tools/case-list-config/updateSearchInput";
import { setCaseSearchClaimTool } from "../lib/agent/tools/case-search-config/setCaseSearchClaim";
import { setCaseSearchDisplayTool } from "../lib/agent/tools/case-search-config/setCaseSearchDisplay";

/**
 * Discriminated union of the two compiler paths. The structured-
 * output arm wraps `Output.object`; the tool-input arm wraps a
 * synthetic `tools[name]` registration with the schema as
 * `inputSchema` and a no-op `execute`. Both arms drive a single
 * `generateText` call; the failure surface is whether the model
 * accepted the schema (so the per-test return value is just
 * pass/fail).
 */
type SchemaTest =
	| {
			readonly mode: "structured-output";
			readonly name: string;
			readonly schema: z.ZodType;
			readonly prompt: string;
	  }
	| {
			readonly mode: "tool-input";
			readonly name: string;
			readonly description: string;
			readonly schema: z.ZodObject<z.ZodRawShape>;
			readonly prompt: string;
	  };

const SCHEMA_TESTS: readonly SchemaTest[] = [
	{
		mode: "structured-output",
		name: "addFields",
		schema: addFieldsSchema.schema,
		prompt:
			"A registration form with 2 fields: patient_name (text) and age (int).",
	},
	{
		mode: "tool-input",
		name: "addCaseListColumn",
		description: addCaseListColumnTool.description,
		schema: addCaseListColumnTool.inputSchema,
		prompt:
			"Use addCaseListColumn to add a plain column on module 0 for case_name with header Patient.",
	},
	{
		mode: "tool-input",
		name: "updateCaseListColumn",
		description: updateCaseListColumnTool.description,
		schema: updateCaseListColumnTool.inputSchema,
		prompt:
			"Use updateCaseListColumn on module 0, columnUuid 11111111-1111-1111-1111-111111111111, replacing it with a date column for dob with header Date of birth and pattern %Y-%m-%d.",
	},
	{
		mode: "tool-input",
		name: "removeCaseListColumn",
		description: removeCaseListColumnTool.description,
		schema: removeCaseListColumnTool.inputSchema,
		prompt:
			"Use removeCaseListColumn on module 0, columnUuid 11111111-1111-1111-1111-111111111111.",
	},
	{
		mode: "tool-input",
		name: "reorderCaseListColumns",
		description: reorderCaseListColumnsTool.description,
		schema: reorderCaseListColumnsTool.inputSchema,
		prompt:
			"Use reorderCaseListColumns on module 0 with the order [22222222-2222-2222-2222-222222222222, 11111111-1111-1111-1111-111111111111].",
	},
	{
		mode: "tool-input",
		name: "setCaseListFilter",
		description: setCaseListFilterTool.description,
		schema: setCaseListFilterTool.inputSchema,
		prompt:
			"Use setCaseListFilter to set the filter on module 0 to a comparison: the patient case status property equals the literal string active.",
	},
	{
		mode: "tool-input",
		name: "addSearchInput",
		description: addSearchInputTool.description,
		schema: addSearchInputTool.inputSchema,
		prompt:
			"Use addSearchInput on module 0 to add a simple search input named patient_name_input labeled Patient name type text targeting case property name.",
	},
	{
		mode: "tool-input",
		name: "updateSearchInput",
		description: updateSearchInputTool.description,
		schema: updateSearchInputTool.inputSchema,
		prompt:
			"Use updateSearchInput on module 0, searchInputUuid 11111111-1111-1111-1111-111111111111, replacing it with a simple search input named region labeled Region type text targeting case property region.",
	},
	{
		mode: "tool-input",
		name: "removeSearchInput",
		description: removeSearchInputTool.description,
		schema: removeSearchInputTool.inputSchema,
		prompt:
			"Use removeSearchInput on module 0, searchInputUuid 11111111-1111-1111-1111-111111111111.",
	},
	{
		mode: "tool-input",
		name: "reorderSearchInputs",
		description: reorderSearchInputsTool.description,
		schema: reorderSearchInputsTool.inputSchema,
		prompt:
			"Use reorderSearchInputs on module 0 with the order [22222222-2222-2222-2222-222222222222, 11111111-1111-1111-1111-111111111111].",
	},
	{
		mode: "tool-input",
		name: "setCaseSearchClaim",
		description: setCaseSearchClaimTool.description,
		schema: setCaseSearchClaimTool.inputSchema,
		prompt:
			"Use setCaseSearchClaim on module 0 to clear the claim condition (null) and clear the blacklisted owner ids (null).",
	},
	{
		mode: "tool-input",
		name: "setCaseSearchDisplay",
		description: setCaseSearchDisplayTool.description,
		schema: setCaseSearchDisplayTool.inputSchema,
		prompt:
			"Use setCaseSearchDisplay on module 0 to set the searchScreenTitle to 'Find a patient' and clear every other display slot (null).",
	},
];

const apiKey = process.env.ANTHROPIC_API_KEY;
if (!apiKey) {
	console.error("Set ANTHROPIC_API_KEY");
	process.exit(1);
}

const anthropic = createAnthropic({ apiKey });
const args = process.argv.slice(2);
const useOpus = args.includes("opus");
const explicitName = args.find((a) => a !== "opus");
const model = useOpus ? "claude-opus-4-7" : "claude-haiku-4-5-20251001";

const tests = explicitName
	? SCHEMA_TESTS.filter((t) => t.name === explicitName)
	: SCHEMA_TESTS;

if (tests.length === 0) {
	console.error(`Unknown schema name: ${explicitName}`);
	console.error(`Known names: ${SCHEMA_TESTS.map((t) => t.name).join(", ")}`);
	process.exit(1);
}

console.log(`Testing with ${model}...`);

/* Wrap the loop in an async IIFE — `tsx` transpiles to CJS, which
 * rejects top-level `await`. The IIFE preserves per-test sequential
 * ordering so the per-line console output stays readable. */
(async () => {
	let exitCode = 0;
	for (const test of tests) {
		const size = JSON.stringify(z.toJSONSchema(test.schema)).length;
		console.log(`\n${test.name} (${test.mode}): ${size} chars`);

		const controller = new AbortController();
		const timer = setTimeout(() => {
			console.log("TIMEOUT (180s)");
			controller.abort();
		}, 180000);

		try {
			const r =
				test.mode === "structured-output"
					? await generateText({
							model: anthropic(model),
							output: Output.object({ schema: test.schema }),
							system: "Produce minimal valid output.",
							prompt: test.prompt,
							maxOutputTokens: 1024,
							abortSignal: controller.signal,
						})
					: await generateText({
							model: anthropic(model),
							tools: {
								[test.name]: tool({
									description: test.description,
									inputSchema: test.schema,
									execute: async () => "ok",
								}),
							},
							/* `stepCountIs(2)` lets the model emit a tool call
							 * + its tool-result response without looping into
							 * a second tool call; `tool-calls` finishReason
							 * confirms the schema accepted the input. */
							stopWhen: stepCountIs(2),
							system:
								"Use the supplied tool with reasonable arguments to satisfy the prompt.",
							prompt: test.prompt,
							maxOutputTokens: 1024,
							abortSignal: controller.signal,
						});
			clearTimeout(timer);
			console.log(
				`PASS (${r.usage.inputTokens}/${r.usage.outputTokens} tokens, finishReason=${r.finishReason})`,
			);
		} catch (e) {
			clearTimeout(timer);
			const err = e as { responseBody?: string; message?: string };
			console.log(
				"FAIL:",
				(err.responseBody ?? err.message ?? "").slice(0, 500),
			);
			exitCode = 1;
		}
	}

	process.exit(exitCode);
})();
