/**
 * Tests that SA tool / structured-output schemas compile within the
 * Anthropic compiler limits. Two compiler paths share the same
 * underlying engine but accept different schema features:
 *
 *   - **Structured-output mode** (`Output.object`) — used for the
 *     `addFields` schema and any future schema that drives a
 *     non-tool generation. Rejects `oneOf`-shaped discriminated
 *     unions and `$ref` recursion at the compiler boundary; the
 *     `addFields` schema therefore uses a flat-with-discriminator
 *     shape generated by `toolSchemaGenerator.ts`.
 *
 *   - **Tool-input mode** (`tools[name].inputSchema`) — used by
 *     every SA tool in `lib/agent/tools/`. Accepts both `oneOf`
 *     discriminated unions and `$ref` recursion natively, so the
 *     case-list-config tools can pass the typed Predicate /
 *     ValueExpression AST schemas directly via Zod without
 *     restructuring.
 *
 * The 8-optional-field-per-array-item ceiling is shared across
 * both modes — both compilers time out above 8 optional fields on
 * the per-item schema.
 *
 * Usage: `npx tsx scripts/test-schema.ts [opus] [schema-name]`
 *   - Pass `opus` to test against Opus 4.7 (default Haiku 4.5).
 *   - Pass a schema name (`addFields`, `setCaseListColumns`,
 *     `setCaseListFilter`, `setCaseListSort`,
 *     `setCalculatedColumns`, `setCaseListSearchInputs`) to test
 *     only that schema; omit to test every registered schema.
 */
import "dotenv/config";
import { createAnthropic } from "@ai-sdk/anthropic";
import { generateText, Output, stepCountIs, tool } from "ai";
import { z } from "zod";
import { addFieldsSchema } from "../lib/agent/toolSchemas";
import { setCalculatedColumnsTool } from "../lib/agent/tools/case-list-config/setCalculatedColumns";
import { setCaseListColumnsTool } from "../lib/agent/tools/case-list-config/setCaseListColumns";
import { setCaseListFilterTool } from "../lib/agent/tools/case-list-config/setCaseListFilter";
import { setCaseListSearchInputsTool } from "../lib/agent/tools/case-list-config/setCaseListSearchInputs";
import { setCaseListSortTool } from "../lib/agent/tools/case-list-config/setCaseListSort";

/**
 * Discriminated union of the two compiler paths. The structured-
 * output arm wraps `Output.object`; the tool-input arm wraps a
 * synthetic `tools[name]` registration with the schema as
 * `inputSchema` and a no-op `execute`. Both arms drive a single
 * `generateText` call; the failure surface is whether the model
 * accepted the schema (so the per-test return value is just
 * pass/fail).
 */
type SchemaTest =
	| {
			readonly mode: "structured-output";
			readonly name: string;
			readonly schema: z.ZodType;
			readonly prompt: string;
	  }
	| {
			readonly mode: "tool-input";
			readonly name: string;
			readonly description: string;
			readonly schema: z.ZodObject<z.ZodRawShape>;
			readonly prompt: string;
	  };

const SCHEMA_TESTS: readonly SchemaTest[] = [
	{
		mode: "structured-output",
		name: "addFields",
		schema: addFieldsSchema.schema,
		prompt:
			"A registration form with 2 fields: patient_name (text) and age (int).",
	},
	{
		mode: "tool-input",
		name: "setCaseListColumns",
		description: setCaseListColumnsTool.description,
		schema: setCaseListColumnsTool.inputSchema,
		prompt:
			"Use setCaseListColumns to set columns on module 0 to one plain column for case_name titled Patient.",
	},
	{
		mode: "tool-input",
		name: "setCaseListFilter",
		description: setCaseListFilterTool.description,
		schema: setCaseListFilterTool.inputSchema,
		prompt:
			"Use setCaseListFilter to set the filter on module 0 to a comparison: the patient case status property equals the literal string active.",
	},
	{
		mode: "tool-input",
		name: "setCaseListSort",
		description: setCaseListSortTool.description,
		schema: setCaseListSortTool.inputSchema,
		prompt:
			"Use setCaseListSort to set the sort on module 0 to one key: property case_name ascending plain comparator.",
	},
	{
		mode: "tool-input",
		name: "setCalculatedColumns",
		description: setCalculatedColumnsTool.description,
		schema: setCalculatedColumnsTool.inputSchema,
		prompt:
			"Use setCalculatedColumns to set one calculated column on module 0 with id today_str header Today expression today.",
	},
	{
		mode: "tool-input",
		name: "setCaseListSearchInputs",
		description: setCaseListSearchInputsTool.description,
		schema: setCaseListSearchInputsTool.inputSchema,
		prompt:
			"Use setCaseListSearchInputs to set one search input on module 0 named patient_name_input labeled Patient name type text targeting case property name.",
	},
];

const apiKey = process.env.ANTHROPIC_API_KEY;
if (!apiKey) {
	console.error("Set ANTHROPIC_API_KEY");
	process.exit(1);
}

const anthropic = createAnthropic({ apiKey });
const args = process.argv.slice(2);
const useOpus = args.includes("opus");
const explicitName = args.find((a) => a !== "opus");
const model = useOpus ? "claude-opus-4-7" : "claude-haiku-4-5-20251001";

const tests = explicitName
	? SCHEMA_TESTS.filter((t) => t.name === explicitName)
	: SCHEMA_TESTS;

if (tests.length === 0) {
	console.error(`Unknown schema name: ${explicitName}`);
	console.error(`Known names: ${SCHEMA_TESTS.map((t) => t.name).join(", ")}`);
	process.exit(1);
}

console.log(`Testing with ${model}...`);

/* Wrap the loop in an async IIFE — `tsx` transpiles to CJS, which
 * rejects top-level `await`. The IIFE preserves per-test sequential
 * ordering so the per-line console output stays readable. */
(async () => {
	let exitCode = 0;
	for (const test of tests) {
		const size = JSON.stringify(z.toJSONSchema(test.schema)).length;
		console.log(`\n${test.name} (${test.mode}): ${size} chars`);

		const controller = new AbortController();
		const timer = setTimeout(() => {
			console.log("TIMEOUT (180s)");
			controller.abort();
		}, 180000);

		try {
			const r =
				test.mode === "structured-output"
					? await generateText({
							model: anthropic(model),
							output: Output.object({ schema: test.schema }),
							system: "Produce minimal valid output.",
							prompt: test.prompt,
							maxOutputTokens: 1024,
							abortSignal: controller.signal,
						})
					: await generateText({
							model: anthropic(model),
							tools: {
								[test.name]: tool({
									description: test.description,
									inputSchema: test.schema,
									execute: async () => "ok",
								}),
							},
							/* `stepCountIs(2)` lets the model emit a tool call
							 * + its tool-result response without looping into
							 * a second tool call; `tool-calls` finishReason
							 * confirms the schema accepted the input. */
							stopWhen: stepCountIs(2),
							system:
								"Use the supplied tool with reasonable arguments to satisfy the prompt.",
							prompt: test.prompt,
							maxOutputTokens: 1024,
							abortSignal: controller.signal,
						});
			clearTimeout(timer);
			console.log(
				`PASS (${r.usage.inputTokens}/${r.usage.outputTokens} tokens, finishReason=${r.finishReason})`,
			);
		} catch (e) {
			clearTimeout(timer);
			const err = e as { responseBody?: string; message?: string };
			console.log(
				"FAIL:",
				(err.responseBody ?? err.message ?? "").slice(0, 500),
			);
			exitCode = 1;
		}
	}

	process.exit(exitCode);
})();
