// Live-Postgres contract tests for the additive lookup persistence migration.
// The shared case-store global setup applies the exact production migration
// chain; each test then runs inside the harness's rollback transaction.

import type { PoolClient } from "pg";
import { describe } from "vitest";
import { expect, test } from "../../sql/__tests__/setup";

const ACTOR = "lookup-test-user";

async function expectSqlState(
	client: PoolClient,
	expectedCode: string,
	statement: string,
	parameters: unknown[] = [],
): Promise<void> {
	await client.query("SAVEPOINT lookup_expected_error");
	let error: unknown;
	try {
		await client.query(statement, parameters);
	} catch (caught) {
		error = caught;
	}
	await client.query("ROLLBACK TO SAVEPOINT lookup_expected_error");
	await client.query("RELEASE SAVEPOINT lookup_expected_error");
	expect((error as { code?: string } | undefined)?.code).toBe(expectedCode);
}

async function insertTable(
	client: PoolClient,
	{
		projectId = "project-a",
		name = "Facilities",
		tag = "facilities",
		columnCount = 1,
		definitionRevision = "1",
		rowsRevision = "1",
	}: {
		projectId?: string;
		name?: string;
		tag?: string;
		columnCount?: number;
		definitionRevision?: string;
		rowsRevision?: string;
	} = {},
): Promise<string> {
	const result = await client.query<{ id: string }>(
		`INSERT INTO lookup_tables
			(project_id, name, tag, definition_revision, rows_revision,
			 column_count, created_by, updated_by)
		 VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
		 RETURNING id`,
		[
			projectId,
			name,
			tag,
			definitionRevision,
			rowsRevision,
			columnCount,
			ACTOR,
		],
	);
	const id = result.rows[0]?.id;
	if (!id) throw new Error("lookup table insert returned no id");
	return id;
}

async function insertColumn(
	client: PoolClient,
	tableId: string,
	{
		projectId = "project-a",
		wireName = "name",
		label = "Name",
		dataType = "text",
		orderKey = "V",
	}: {
		projectId?: string;
		wireName?: string;
		label?: string;
		dataType?: string;
		orderKey?: string;
	} = {},
): Promise<string> {
	const result = await client.query<{ id: string }>(
		`INSERT INTO lookup_columns
			(project_id, table_id, wire_name, label, data_type, order_key)
		 VALUES ($1, $2, $3, $4, $5, $6)
		 RETURNING id`,
		[projectId, tableId, wireName, label, dataType, orderKey],
	);
	const id = result.rows[0]?.id;
	if (!id) throw new Error("lookup column insert returned no id");
	return id;
}

describe("lookup persistence migration", () => {
	test("creates exact-revision rows, UUIDv7 identities, C-collated order, and generated byte counts", async ({
		pgClient,
	}) => {
		await pgClient.query(
			`INSERT INTO lookup_project_state (project_id, revision)
			 VALUES ($1, $2)`,
			["project-a", "9223372036854775807"],
		);
		const tableId = await insertTable(pgClient, {
			definitionRevision: "9223372036854775807",
			rowsRevision: "9223372036854775806",
		});
		const columnId = await insertColumn(pgClient, tableId);
		const values = { [columnId]: "Clinic A" };
		const row = await pgClient.query<{
			id: string;
			value_bytes: number;
			measured_bytes: number;
		}>(
			`INSERT INTO lookup_rows
				(project_id, table_id, order_key, "values", created_by, updated_by)
			 VALUES ($1, $2, $3, $4::jsonb, $5, $5)
			 RETURNING id, value_bytes, octet_length("values"::text) AS measured_bytes`,
			["project-a", tableId, "V", JSON.stringify(values), ACTOR],
		);

		const state = await pgClient.query<{ revision: string }>(
			"SELECT revision FROM lookup_project_state WHERE project_id = $1",
			["project-a"],
		);
		const table = await pgClient.query<{
			definition_revision: string;
			rows_revision: string;
		}>(
			`SELECT definition_revision, rows_revision
			 FROM lookup_tables WHERE project_id = $1 AND id = $2`,
			["project-a", tableId],
		);
		expect(state.rows[0]?.revision).toBe("9223372036854775807");
		expect(table.rows[0]).toEqual({
			definition_revision: "9223372036854775807",
			rows_revision: "9223372036854775806",
		});
		expect(tableId).toMatch(
			/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
		);
		expect(columnId).toMatch(
			/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
		);
		expect(row.rows[0]?.id).toMatch(
			/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
		);
		expect(row.rows[0]?.value_bytes).toBe(row.rows[0]?.measured_bytes);

		const columns = await pgClient.query<{
			table_name: string;
			collation_name: string | null;
			is_generated: string;
			generation_expression: string | null;
		}>(
			`SELECT table_name, collation_name, is_generated, generation_expression
			 FROM information_schema.columns
			 WHERE table_schema = 'public'
			   AND column_name IN ('order_key', 'value_bytes')
			   AND table_name IN ('lookup_columns', 'lookup_rows')
			 ORDER BY table_name, column_name`,
		);
		const byColumn = new Map(
			columns.rows.map((item) => [
				`${item.table_name}:${item.is_generated}`,
				item,
			]),
		);
		expect(byColumn.get("lookup_columns:NEVER")?.collation_name).toBe("C");
		expect(byColumn.get("lookup_rows:NEVER")?.collation_name).toBe("C");
		expect(byColumn.get("lookup_rows:ALWAYS")?.generation_expression).toContain(
			"octet_length",
		);

		const indexes = await pgClient.query<{ indexname: string }>(
			`SELECT indexname FROM pg_indexes
			 WHERE schemaname = 'public'
			   AND tablename IN ('lookup_tables', 'lookup_columns', 'lookup_rows')`,
		);
		expect(indexes.rows.map(({ indexname }) => indexname)).toEqual(
			expect.arrayContaining([
				"lookup_tables_project_name_idx",
				"lookup_columns_order_idx",
				"lookup_rows_order_idx",
			]),
		);
	});

	test("keeps tag uniqueness exact and Project-scoped", async ({
		pgClient,
	}) => {
		await insertTable(pgClient, { tag: "Facility" });
		await insertTable(pgClient, {
			name: "Lowercase facility",
			tag: "facility",
		});
		await insertTable(pgClient, {
			projectId: "project-b",
			tag: "Facility",
		});
		await expectSqlState(
			pgClient,
			"23505",
			`INSERT INTO lookup_tables
				(project_id, name, tag, definition_revision, rows_revision,
				 column_count, created_by, updated_by)
			 VALUES ('project-a', 'Duplicate', 'Facility', 2, 2, 1, $1, $1)`,
			[ACTOR],
		);
	});

	test("enforces revision, identity, and service-maintained counter bounds", async ({
		pgClient,
	}) => {
		await expectSqlState(
			pgClient,
			"23514",
			"INSERT INTO lookup_project_state (project_id, revision) VALUES ('bad', -1)",
		);

		const baseInsert = `INSERT INTO lookup_tables
			(project_id, name, tag, definition_revision, rows_revision,
			 column_count, row_count, data_bytes, created_by, updated_by)
		 VALUES ('project-a', $1, $2, $3, $4, $5, $6, $7, $8, $8)`;
		const invalidRows: unknown[][] = [
			[" Facilities", "facilities", "1", "1", 1, 0, 0, ACTOR],
			["Facilities", "xml_table", "1", "1", 1, 0, 0, ACTOR],
			["Facilities", "1facility", "1", "1", 1, 0, 0, ACTOR],
			["Facilities", "x".repeat(33), "1", "1", 1, 0, 0, ACTOR],
			["Facilities", "facilities", "-1", "1", 1, 0, 0, ACTOR],
			["Facilities", "facilities", "1", "-1", 1, 0, 0, ACTOR],
			["Facilities", "facilities", "1", "1", 0, 0, 0, ACTOR],
			["Facilities", "facilities", "1", "1", 251, 0, 0, ACTOR],
			["Facilities", "facilities", "1", "1", 1, -1, 0, ACTOR],
			["Facilities", "facilities", "1", "1", 1, 5001, 0, ACTOR],
			["Facilities", "facilities", "1", "1", 1, 0, -1, ACTOR],
			["Facilities", "facilities", "1", "1", 1, 0, 8388609, ACTOR],
		];
		for (const parameters of invalidRows) {
			await expectSqlState(pgClient, "23514", baseInsert, parameters);
		}

		await pgClient.query(baseInsert, [
			"Boundary table",
			"boundary_table",
			"0",
			"9223372036854775807",
			250,
			5000,
			8388608,
			ACTOR,
		]);
	});

	test("enforces column wire, label, type, order, and exact per-table uniqueness", async ({
		pgClient,
	}) => {
		const tableId = await insertTable(pgClient, { columnCount: 8 });
		const insert = `INSERT INTO lookup_columns
			(project_id, table_id, wire_name, label, data_type, order_key)
		 VALUES ('project-a', $1, $2, $3, $4, $5)`;
		const invalidColumns: unknown[][] = [
			[tableId, "xml_name", "Name", "text", "1"],
			[tableId, "1name", "Name", "text", "1"],
			[tableId, "x".repeat(256), "Name", "text", "1"],
			[tableId, "name", " Name", "text", "1"],
			[tableId, "name", "Name", "boolean", "1"],
			[tableId, "name", "Name", "text", ""],
			[tableId, "name", "Name", "text", "A-"],
			[tableId, "name", "Name", "text", "A0"],
		];
		for (const parameters of invalidColumns) {
			await expectSqlState(pgClient, "23514", insert, parameters);
		}

		for (const [index, dataType] of [
			"text",
			"int",
			"decimal",
			"date",
			"time",
			"datetime",
		].entries()) {
			await pgClient.query(insert, [
				tableId,
				`column_${dataType}`,
				`Column ${dataType}`,
				dataType,
				String(index + 1),
			]);
		}
		await pgClient.query(insert, [tableId, "Code", "Code", "text", "A"]);
		await pgClient.query(insert, [tableId, "code", "Code lower", "text", "B"]);
		await expectSqlState(pgClient, "23505", insert, [
			tableId,
			"Code",
			"Duplicate",
			"text",
			"C",
		]);
	});

	test("enforces composite tenant foreign keys and row JSON/order/size checks", async ({
		pgClient,
	}) => {
		const tableId = await insertTable(pgClient);
		const columnId = await insertColumn(pgClient, tableId);

		await expectSqlState(
			pgClient,
			"23503",
			`INSERT INTO lookup_columns
				(project_id, table_id, wire_name, label, data_type, order_key)
			 VALUES ('project-b', $1, 'foreign', 'Foreign', 'text', 'V')`,
			[tableId],
		);

		const insert = `INSERT INTO lookup_rows
			(project_id, table_id, order_key, "values", created_by, updated_by)
		 VALUES ('project-a', $1, $2, $3::jsonb, $4, $4)`;
		for (const values of ["[]", '"scalar"', "null"]) {
			await expectSqlState(pgClient, "23514", insert, [
				tableId,
				"V",
				values,
				ACTOR,
			]);
		}
		for (const orderKey of ["", "A-", "A0"]) {
			await expectSqlState(pgClient, "23514", insert, [
				tableId,
				orderKey,
				"{}",
				ACTOR,
			]);
		}
		await expectSqlState(pgClient, "23514", insert, [
			tableId,
			"V",
			JSON.stringify({ [columnId]: "x".repeat(262145) }),
			ACTOR,
		]);

		const boundaryTableId = await insertTable(pgClient, {
			name: "Exact row boundary",
			tag: "exact_row_boundary",
			columnCount: 4,
		});
		const boundaryColumnIds: string[] = [];
		for (let index = 0; index < 4; index++) {
			boundaryColumnIds.push(
				await insertColumn(pgClient, boundaryTableId, {
					wireName: `boundary_${index}`,
					label: `Boundary ${index}`,
					orderKey: String(index + 1),
				}),
			);
		}
		const baseSize = await pgClient.query<{ bytes: number }>(
			`SELECT octet_length(jsonb_build_object(
				$1::text, repeat('x', 65536),
				$2::text, repeat('x', 65536),
				$3::text, repeat('x', 65536),
				$4::text, ''
			)::text) AS bytes`,
			boundaryColumnIds,
		);
		const finalCellLength = 262_144 - (baseSize.rows[0]?.bytes ?? 0);
		expect(finalCellLength).toBeGreaterThanOrEqual(0);
		expect(finalCellLength).toBeLessThanOrEqual(65_536);
		const exactBoundary = await pgClient.query<{ value_bytes: number }>(
			`INSERT INTO lookup_rows
				(project_id, table_id, order_key, "values", created_by, updated_by)
			 VALUES (
				'project-a', $1, 'W',
				jsonb_build_object(
					$2::text, repeat('x', 65536),
					$3::text, repeat('x', 65536),
					$4::text, repeat('x', 65536),
					$5::text, repeat('x', $6)
				),
				$7, $7
			 )
			 RETURNING value_bytes`,
			[boundaryTableId, ...boundaryColumnIds, finalCellLength, ACTOR],
		);
		expect(exactBoundary.rows[0]?.value_bytes).toBe(262_144);
	});

	test("cascades a table deletion to its columns and rows", async ({
		pgClient,
	}) => {
		const tableId = await insertTable(pgClient);
		const columnId = await insertColumn(pgClient, tableId);
		await pgClient.query(
			`INSERT INTO lookup_rows
				(project_id, table_id, order_key, "values", created_by, updated_by)
			 VALUES ($1, $2, 'V', $3::jsonb, $4, $4)`,
			["project-a", tableId, JSON.stringify({ [columnId]: "A" }), ACTOR],
		);

		// Destructive lookup DDL sits behind the deployed writer floor; declare
		// v1 (transaction-local, so it ends with this test's transaction).
		await pgClient.query("SELECT set_config('nova.writer_version', '1', true)");
		await pgClient.query(
			"DELETE FROM lookup_tables WHERE project_id = $1 AND id = $2",
			["project-a", tableId],
		);
		const children = await pgClient.query<{ columns: string; rows: string }>(
			`SELECT
				(SELECT count(*)::text FROM lookup_columns
				 WHERE project_id = $1 AND table_id = $2) AS columns,
				(SELECT count(*)::text FROM lookup_rows
				 WHERE project_id = $1 AND table_id = $2) AS rows`,
			["project-a", tableId],
		);
		expect(children.rows[0]).toEqual({ columns: "0", rows: "0" });
	});
});
