import AdmZip from "adm-zip";
import { expect, it } from "vitest";
import { toPersistableDoc } from "@/lib/doc/fieldParent";
import { LOOKUP_CONTEXT_UNAVAILABLE } from "@/lib/doc/lookupReferences";
import { type BlueprintDoc, blueprintDocSchema } from "@/lib/domain";
import { input, term } from "@/lib/domain/predicate";
import { compileCcz } from "../compiler";
import { expandDoc } from "../expander";
import { COMMCARE_SERVER_IDS, type CommCareServer } from "../servers";
import { runValidation } from "../validator/runner";
import {
	searchEmissionFixture,
	searchEmissionScenarios,
} from "./searchEmissionFixture";
import {
	onlyXml,
	readXmlEvidence,
	type XmlEvidence,
	xmlChildren,
} from "./xmlEvidence";

const origins = {
	production: "https://www.commcarehq.org",
	india: "https://india.commcarehq.org",
	eu: "https://eu.commcarehq.org",
};
function exported(doc: BlueprintDoc, server: CommCareServer = "production") {
	blueprintDocSchema.parse(toPersistableDoc(doc));
	expect(runValidation(doc, LOOKUP_CONTEXT_UNAVAILABLE)).toEqual([]);
	const runtimeTarget = { server, domain: "clinic", appId: "released-app" };
	const hq = expandDoc(doc, { runtimeTarget });
	const zip = new AdmZip(compileCcz(hq, doc.appName, doc, { runtimeTarget }));
	return { hq, zip, suite: readXmlEvidence(zip.readAsText("suite.xml")) };
}
const one = (node: XmlEvidence, name: string) =>
	onlyXml(xmlChildren(node, name));
function entry(suite: XmlEvidence, command: string) {
	return onlyXml(
		xmlChildren(suite, "entry").filter(
			(node) => one(node, "command").attributes.id === command,
		),
	);
}
const sessionRef = (id: string) =>
	`instance('commcaresession')/session/data/${id}`;
const claimed = (id: string) =>
	`count(instance('casedb')/casedb/case[@case_id=${sessionRef(id)}])`;
const claimUrl = "https://www.commcarehq.org/a/clinic/phone/claim-case/";

// The same twelve admitted documents are regenerated by native HQ contributors
// and executed by Core. This always-run suite checks archive and projection joins.
it.each(searchEmissionScenarios)(
	"exports the complete Search session for %s",
	(scenario) => {
		const { suite, hq, zip } = exported(searchEmissionFixture(scenario));
		const remote = scenario.startsWith("remote");
		const multiple = scenario === "multiple" || scenario === "remote-multiple";
		const browse = scenario === "browse";
		const parent = scenario === "parent";
		const primary = entry(suite, browse ? "m0-case-list" : "m0-f0");
		const requests = xmlChildren(suite, "remote-request");
		expect(requests.length).toBe(remote ? 1 : 0);
		const search = remote ? onlyXml(requests) : primary;
		if (remote)
			expect(one(search, "command").attributes).toEqual({
				id: "search_command.m0",
			});
		const session = one(search, "session");
		expect(session.children.map((node) => node.name)).toEqual([
			...(parent ? ["datum"] : []),
			"query",
			multiple ? "instance-datum" : "datum",
		]);
		const query = one(session, "query");
		const automatic = ["automatic", "hidden", "hidden-link"].includes(scenario);
		expect(query.attributes).toEqual({
			url: "https://www.commcarehq.org/a/clinic/phone/search/released-app/",
			default_search: String(automatic),
			"storage-instance": remote ? "results" : "results:inline",
			template: "case",
		});
		expect(hq.modules[0].search_config.inline_search).toBe(!remote);
		expect(hq.modules[0].search_config.auto_launch).toBe(!remote);
		expect(hq.modules[0].search_config.default_search).toBe(automatic);
		expect(one(one(one(query, "title"), "text"), "locale").attributes).toEqual({
			id: "case_search.m0.inputs",
		});
		const prompts = xmlChildren(query, "prompt");
		const promptKeys =
			scenario === "automatic"
				? []
				: scenario === "hidden" || scenario === "hidden-link"
					? ["search_time"]
					: scenario === "advanced"
						? ["first_name", "note"]
						: scenario === "remote-defaults"
							? ["first_name", "echo"]
							: ["first_name"];
		expect(prompts.map((node) => node.attributes.key)).toEqual(promptKeys);
		expect(prompts.map((node) => node.attributes.default)).toEqual(
			promptKeys.map(() =>
				scenario === "hidden" || scenario === "hidden-link"
					? "'now'"
					: scenario === "remote-defaults"
						? "instance('commcaresession')/session/user/data/default_name"
						: undefined,
			),
		);
		const data = xmlChildren(query, "data");
		expect(data.map((node) => node.attributes.key)).toEqual([
			"case_type",
			...(multiple ? ["x_commcare_include_all_related_cases"] : []),
			...(scenario === "remote-defaults"
				? ["_xpath_query", "commcare_blacklisted_owner_ids"]
				: []),
			...(parent || scenario === "advanced" ? ["_xpath_query"] : []),
		]);
		expect(data[0].attributes).toEqual({ key: "case_type", ref: "'patient'" });
		if (multiple)
			expect(data[1].attributes).toEqual({
				key: "x_commcare_include_all_related_cases",
				ref: "'true'",
			});
		if (scenario === "advanced")
			expect(data.at(-1)?.attributes.ref).toBe(
				hq.modules[0].search_config.default_properties[0].defaultValue,
			);
		if (parent)
			expect(data.at(-1)?.attributes).toEqual({
				key: "_xpath_query",
				ref: "\"ancestor-exists(parent, @case_type='parent_case')\"",
			});
		const datum = session.children.at(-1);
		if (!datum) throw new Error("Missing Search selection");
		const datumId = remote
			? multiple
				? "search_selected_cases"
				: "search_case_id"
			: multiple
				? "selected_cases"
				: "case_id";
		const detailPrefix = remote ? "m0_search" : "m0_case";
		expect(datum.attributes).toEqual({
			id: datumId,
			nodeset: `instance('${remote ? "results" : "results:inline"}')/results/case[@case_type='patient']${remote ? "" : "[@status='open']"}[not(commcare_is_related_case=true())]${parent ? "[index/*[not(@relationship='extension')]=instance('commcaresession')/session/data/parent_id]" : ""}`,
			value: "./@case_id",
			"detail-select": `${detailPrefix}_short`,
			"detail-confirm": `${detailPrefix}_long`,
			...(multiple ? { "max-select-value": "100" } : {}),
		});
		const detailIds = xmlChildren(suite, "detail").map(
			(node) => node.attributes.id,
		);
		expect(detailIds).toEqual([
			"m0_case_short",
			"m0_case_long",
			...(parent ? ["m1_case_short", "m1_case_long"] : []),
			...(scenario === "registration-link" || scenario === "hidden-link"
				? ["m1_case_short", "m1_case_long"]
				: []),
			...(remote ? ["m0_search_short", "m0_search_long"] : []),
		]);
		for (const key of ["detail-select", "detail-confirm"])
			expect(detailIds).toContain(datum.attributes[key]);
		// Every form entry launches the actual packaged form, not a copied fixture namespace.
		for (const [moduleIndex, module] of hq.modules.entries())
			for (const [formIndex, form] of module.forms.entries()) {
				const formEntry = entry(suite, `m${moduleIndex}-f${formIndex}`);
				expect(one(formEntry, "form").text).toBe(form.xmlns);
				expect(
					zip.getEntry(`modules-${moduleIndex}/forms-${formIndex}.xml`),
				).not.toBeNull();
			}
		if (browse) {
			expect(xmlChildren(primary, "post")).toEqual([]);
			expect(xmlChildren(primary, "form")).toEqual([]);
		} else {
			const post = one(search, "post");
			expect(post.attributes).toEqual({
				url: claimUrl,
				relevant:
					multiple || parent ? "$case_id != ''" : `${claimed(datumId)} = 0`,
			});
			expect(post.children.map((node) => [node.name, node.attributes])).toEqual(
				multiple
					? [
							[
								"data",
								{
									key: "case_id",
									nodeset: `instance('${datumId}')/results/value`,
									exclude:
										"count(instance('casedb')/casedb/case[@case_id=current()/.]) = 1",
									ref: ".",
								},
							],
						]
					: [
							[
								"data",
								{
									key: "case_id",
									ref: sessionRef(datumId),
									...(parent ? { exclude: `${claimed(datumId)} != 0` } : {}),
								},
							],
							...(parent
								? [
										[
											"data",
											{
												key: "case_id",
												ref: sessionRef("parent_id"),
												exclude: `${claimed("parent_id")} != 0`,
											},
										],
									]
								: []),
						],
			);
		}
		if (remote) {
			const push = one(one(search, "stack"), "push");
			expect(push.children.map((node) => [node.name, node.attributes])).toEqual(
				[["rewind", { value: sessionRef(datumId) }]],
			);
		} else if (!browse) {
			const create = one(one(primary, "stack"), "create");
			expect(
				create.children.map((node) => [node.name, node.attributes]),
			).toEqual([["command", { value: "'m0'" }]]);
		}
	},
);

it.each(["registration-link", "hidden-link"] as const)(
	"joins %s to its new case through the hydration frame",
	(scenario) => {
		const { suite } = exported(searchEmissionFixture(scenario));
		const source = entry(suite, "m1-f0");
		expect(one(one(source, "session"), "datum").attributes).toEqual({
			id: "case_id_new_patient_0",
			function: "uuid()",
		});
		const create = one(one(source, "stack"), "create");
		expect(create.children.map((node) => [node.name, node.attributes])).toEqual(
			[
				["command", { value: "'m0'" }],
				[
					"query",
					{
						id: "results:inline",
						value:
							"https://www.commcarehq.org/a/clinic/phone/case_fixture/released-app/",
					},
				],
				[
					"datum",
					{ id: "case_id", value: sessionRef("case_id_new_patient_0") },
				],
				["command", { value: "'m0-f0'" }],
			],
		);
		expect(
			one(create, "query").children.map((node) => [node.name, node.attributes]),
		).toEqual([
			["data", { key: "case_type", ref: "'patient'" }],
			["data", { key: "case_id", ref: sessionRef("case_id_new_patient_0") }],
		]);
	},
);

it.each(COMMCARE_SERVER_IDS)(
	"binds %s URLs at the actual Search, claim and hydration slots",
	(server) => {
		for (const scenario of ["registration-link", "remote"] as const) {
			const { suite } = exported(searchEmissionFixture(scenario), server);
			const search =
				scenario === "remote"
					? onlyXml(xmlChildren(suite, "remote-request"))
					: entry(suite, "m0-f0");
			expect(one(one(search, "session"), "query").attributes.url).toBe(
				`${origins[server]}/a/clinic/phone/search/released-app/`,
			);
			expect(one(search, "post").attributes.url).toBe(
				`${origins[server]}/a/clinic/phone/claim-case/`,
			);
			if (scenario === "registration-link")
				expect(
					one(one(one(entry(suite, "m1-f0"), "stack"), "create"), "query")
						.attributes.value,
				).toBe(`${origins[server]}/a/clinic/phone/case_fixture/released-app/`);
		}
	},
);

it("rejects a Search starting value that reads another answer before answers exist", () => {
	const doc = searchEmissionFixture("remote-defaults");
	const config = doc.modules[doc.moduleOrder[0]].caseListConfig;
	if (!config) throw new Error("Fixture has Search");
	const echo = config.searchInputs[1];
	if (echo.kind === "hidden" || echo.type === "date-range")
		throw new Error("Fixture has visible Echo");
	echo.default = term(input(config.searchInputs[0].uuid));
	blueprintDocSchema.parse(toPersistableDoc(doc));
	expect(
		runValidation(doc, LOOKUP_CONTEXT_UNAVAILABLE).map((finding) => [
			finding.code,
			finding.details?.slot,
		]),
	).toEqual([
		[
			"CASE_LIST_BARE_SEARCH_INPUT_REF",
			"caseListConfig.searchInputs[1].default",
		],
	]);
});
