/**
 * Tests for the built-in icon catalog + helpers. The catalog is generated by
 * `scripts/build-builtin-icons.ts`; these assertions are its integrity contract
 * (counts, kinds, hash shape) plus the ref/slug helpers every surface shares.
 */

import { describe, expect, it } from "vitest";
import {
	ALL_ICON_SLUGS,
	builtinIconPublicPath,
	builtinIconRef,
	builtinIconsForSlot,
	FORM_ICON_SLUGS,
	ICON_CATALOG,
	iconCatalogEntry,
	isBuiltinIconRef,
	MODULE_ICON_SLUGS,
	parseBuiltinIconSlug,
} from "../builtinIcons";
import { NOVA_ICON_REF_PREFIX } from "../multimedia";

describe("ICON_CATALOG integrity", () => {
	it("carries 33 module + 13 form + 1 fallback icons", () => {
		const byKind = (k: string) => ICON_CATALOG.filter((e) => e.kind === k);
		expect(ICON_CATALOG).toHaveLength(47);
		expect(byKind("module")).toHaveLength(33);
		expect(byKind("form")).toHaveLength(13);
		expect(byKind("fallback")).toHaveLength(1);
		expect(iconCatalogEntry("default")?.kind).toBe("fallback");
	});

	it("gives every icon a 64-hex content hash and a positive byte size", () => {
		for (const entry of ICON_CATALOG) {
			expect(entry.contentHash).toMatch(/^[a-f0-9]{64}$/);
			expect(entry.sizeBytes).toBeGreaterThan(0);
			expect(entry.label.length).toBeGreaterThan(0);
		}
	});

	it("has unique slugs that cover ALL_ICON_SLUGS exactly", () => {
		const slugs = ICON_CATALOG.map((e) => e.slug);
		expect(new Set(slugs).size).toBe(slugs.length);
		expect([...ALL_ICON_SLUGS].sort()).toEqual([...slugs].sort());
	});

	it("scopes the per-tool enums to their kind plus the default fallback", () => {
		// 33 module + default; 13 form + default.
		expect(MODULE_ICON_SLUGS).toHaveLength(34);
		expect(FORM_ICON_SLUGS).toHaveLength(14);
		expect(MODULE_ICON_SLUGS).toContain("default");
		expect(FORM_ICON_SLUGS).toContain("default");
		expect(MODULE_ICON_SLUGS).toContain("household");
		expect(MODULE_ICON_SLUGS).not.toContain("register");
		expect(FORM_ICON_SLUGS).toContain("register");
		expect(FORM_ICON_SLUGS).not.toContain("household");
	});
});

describe("built-in icon ref helpers", () => {
	it("round-trips a known slug through ref → parse", () => {
		const ref = builtinIconRef("household");
		expect(ref).toBe(`${NOVA_ICON_REF_PREFIX}household`);
		expect(isBuiltinIconRef(ref)).toBe(true);
		expect(parseBuiltinIconSlug(ref)).toBe("household");
	});

	it("treats a stale built-in ref (slug gone from the catalog) as unresolvable", () => {
		const stale = `${NOVA_ICON_REF_PREFIX}does_not_exist`;
		// It still LOOKS built-in (prefix) so it's routed away from Firestore...
		expect(isBuiltinIconRef(stale)).toBe(true);
		// ...but parse returns null, so it fails closed downstream like a deleted upload.
		expect(parseBuiltinIconSlug(stale)).toBeNull();
	});

	it("does not mistake an uploaded asset id (UUID) for a built-in ref", () => {
		const uuid = "a1b2c3d4-1111-2222-3333-444455556666";
		expect(isBuiltinIconRef(uuid)).toBe(false);
		expect(parseBuiltinIconSlug(uuid)).toBeNull();
	});

	it("derives the static public path for a slug", () => {
		expect(builtinIconPublicPath("patient")).toBe("/nova-icons/patient.png");
	});
});

describe("builtinIconsForSlot", () => {
	it("offers topic icons + the fallback for module slots", () => {
		const module = builtinIconsForSlot("module");
		expect(module).toHaveLength(34);
		expect(module.some((e) => e.slug === "household")).toBe(true);
		expect(module.some((e) => e.slug === "default")).toBe(true);
		expect(module.some((e) => e.slug === "register")).toBe(false);
	});

	it("offers action icons + the fallback for form slots", () => {
		const form = builtinIconsForSlot("form");
		expect(form).toHaveLength(14);
		expect(form.some((e) => e.slug === "register")).toBe(true);
		expect(form.some((e) => e.slug === "default")).toBe(true);
		expect(form.some((e) => e.slug === "household")).toBe(false);
	});
});
