// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  XPath = 1,
  HashtagRef = 2,
  VariableReference = 3,
  StringLiteral = 6,
  NumberLiteral = 7,
  NameTest = 13
